pass-culture/data-gcp

.github/workflows/CD_workflow.yml

feat: Add CD_on_dev_workflow.yml

---

orchestration/dags/data_gcp_dbt/README.md
orchestration/dags/data_gcp_dbt/macros/generate_schema_name.sql
orchestration/dags/data_gcp_dbt/macros/schema.yml
orchestration/dags/data_gcp_dbt/models/analytics/offer_moderation.sql
orchestration/dags/data_gcp_dbt/models/clean/offer_metadata.sql
orchestration/dags/data_gcp_dbt/models/clean/user_beneficiary.sql
orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__mediation.sql
orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__offer.sql
orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__offerer.sql
orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__stock.sql
orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__user.sql
orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__venue.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_event.sql
orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__collective_offer.sql
orchestration/dags/data_gcp_dbt/profiles.yml

Cette PR ajoute un profile "local" qui est le profile par défaut.
Cela permet 2 choses : 
1. lorsqu'on développe sur dbt en local => le résultat des modèles est stocké dans tmp_dev et est supprimé au bout de 24 heures.
2. lorsque le DAG dbt tourne en dev => construit les modèles dbt dans les datasets appropriés.
Tag a reviewer if necessacy  @valoumiaou @cdelabre 

(DE-521) feat/add local env to fix composer dev

---

orchestration/dags/data_gcp_dbt/macros/generate_schema_name.sql
orchestration/dags/data_gcp_dbt/macros/get_custom_alias.sql

include dev in custom alias macro and simplify macro logic

---

Makefile

Remove deprecated target in Makefile

clean: Remove deprecated job in install target

---

orchestration/dags/jobs/dbt/dbt_artifacts.py

fix/dbt change --no-write-json command position

---

orchestration/dags/jobs/dbt/dbt_artifacts.py
orchestration/dags/jobs/dbt/dbt_manual.py

Hotfix clean dbt artifacts stg dev

---

orchestration/dags/jobs/dbt/dbt_dag_run.py

fix compile task dependency

---

orchestration/dags/jobs/export/export_clickhouse.py

add waiting for firebase import in export clickhouse dag

---

Makefile

Small fixes to prevent cyclic loading since now .profile reads into .bashrc

fix: fix launch_vm

---

orchestration/dags/jobs/dbt/dbt_artifacts.py

Hotfix dbt alerting

---

orchestration/dags/jobs/ml/retrieval_vector_semantic_build.py

fix: Replace highmem by standard

---

Makefile
jobs/etl_jobs/external/qualtrics/qualtrics_survey_answers.py
orchestration/dags/jobs/dbt/dbt_artifacts.py
orchestration/dags/jobs/dbt/dbt_dag_run.py
orchestration/dags/jobs/dbt/dbt_manual.py
orchestration/dags/jobs/export/export_clickhouse.py
orchestration/dags/jobs/ml/retrieval_vector_semantic_build.py

MEP 303.1.0

---

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_daily_user_home_module.sql

add trends block conversion to home conversion tables

---

Makefile

Write in .profile instead of .bashrc so that it both works interactively or not
Working airflow run : https://6d8792da62bc4e9baa4ab936d914456f-dot-europe-west1.composer.googleusercontent.com/dags/launch_vm/graph
Screenshot pyenv working interactively :

Fix: Fix launchvm

---

orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__booking.sql
orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__stock.sql
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__booking.sql

Add isbn to booking

---

jobs/ml_jobs/retrieval_vector/utils.py

* Add batch for retrieval
* Link to the airflow dag which works : https://6d8792da62bc4e9baa4ab936d914456f-dot-europe-west1.composer.googleusercontent.com/dags/retrieval_semantic_vector_build/grid?root=&dag_run_id=manual__2024-08-20T07%3A35%3A42%2B00%3A00&task_id=containerize_retrieval_semantic_vector&tab=logs
[JIRA-ticket_number
](https://www.notion.so/passcultureapp/880351701699470cb129e4e0ad6bbcba?v=bfba95ea66224a80aed7b5291454389a&p=bd636571441f405c8db0186e7a2cde4f&pm=s)

[DE-548] (DS) fix: Add vectors by batch in retrieval

---

jobs/ml_jobs/retrieval_vector/utils.py

fix: fix typo in print

---

Makefile
jobs/ml_jobs/retrieval_vector/utils.py
orchestration/dags/data_gcp_dbt/macros/get_custom_alias.sql
orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__booking.sql
orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__stock.sql
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__booking.sql

 MEP 303.2.0 

---

orchestration/dags/dependencies/qpi/sql/analytics/enriched_qpi_answers.sql

Remove query from deleted table
[JIRA-ticket_number
](https://www.notion.so/passcultureapp/880351701699470cb129e4e0ad6bbcba?v=bfba95ea66224a80aed7b5291454389a&p=002e028c27f14d1094e0cc3d8566a40c&pm=s)

[DE-549] Fix/remove fetch from qpi historical

---

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_venue_map_event.sql
orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_venue_map_conversion.sql

This PR adds two models relative to venue map model : an intermediate table with selected events, and a mart table for conversion analysis
Tag a reviewer if necessacy  @Jules-Arbelot @carolinemestre-passculture 

create venue map conversion model

---

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__discord_user.sql
orchestration/dags/data_gcp_dbt/models/sources.yml
orchestration/dags/dependencies/applicative_database/sql/raw/discord_user.sql

(dbt) add discord user int table

---

orchestration/dags/common/dbt/utils.py
orchestration/dags/data_gcp_dbt/macros/schema.yml
orchestration/dags/data_gcp_dbt/profiles.yml
orchestration/dags/jobs/dbt/dbt_dag_run.py
orchestration/dags/jobs/dbt/dbt_manual.py

Improvement & cleaning dbt

---

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__favorite.sql
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__favorite.sql

add favorite_id field to favorite tables

---

jobs/ml_jobs/embeddings/main.py

(BSR) feat: add check in case df is empty

---

jobs/etl_jobs/external/metabase-archiving/dependencies.py

feat: add all datasets types for metabase

---

jobs/ml_jobs/ranking_endpoint/app/constants.py
jobs/ml_jobs/ranking_endpoint/app/model.py
jobs/ml_jobs/ranking_endpoint/deploy_model.py
jobs/ml_jobs/ranking_endpoint/figure.py

* import constants within the app folder
No ticket

(fix): make constants import relative

---

orchestration/dags/jobs/import/import_firebase.py

(firebase) feat: add retry for dev logic

---

jobs/ml_jobs/retrieval_vector/deploy_dummy.py
jobs/ml_jobs/retrieval_vector/deploy_model.py
jobs/ml_jobs/retrieval_vector/deploy_semantic.py
jobs/ml_jobs/retrieval_vector/utils.py

[ML] feat: add index in prod env only

---

jobs/ml_jobs/item_linkage/constants.py

(fix) linkage in dev

---

orchestration/dags/jobs/import/import_firebase.py

(firebase) feat: improve fallback logic

---

orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__collective_offer.sql
orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__offer.sql

(dbt) add last validation type to int_global tables

---

jobs/ml_jobs/offline_recommendation/requirements.in
jobs/ml_jobs/offline_recommendation/requirements.txt

Sheriff-DE/fix offline reco requirements

---

jobs/ml_jobs/retrieval_vector/deploy_dummy.py
jobs/ml_jobs/retrieval_vector/utils.py

(retrieval) fix dummy deploy (dev)

---

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__collective_booking.sql
orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__educational_deposit.sql
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__collective_booking.sql
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__educational_institution.sql

Data checks were performed on the `mrt_global__institution` model to ensure it is consistent with the original `enriched_institution_data` model. Following these checks, we are making this PR with updates to correct the discrepancies between the two tables.
Tag a reviewer if necessacy  @Jules-Arbelot 

[DE-320](dbt) Update mrt_global__institution

---

jobs/ml_jobs/algo_training/fraud/offer_compliance_model/package_api_model.py

fix: Force compliance preproc models to use cpu

---

orchestration/dags/jobs/ml/algo_training_offer_categorization.py

[HOTFIX] Update pip command in algo_training_offer_categorization.py

---

.github/workflows/CD_workflow.yml
.github/workflows/reusable_deploy_composer.yml

CD: disable bucket full-sync for MES

---

orchestration/dags/dependencies/export_clickhouse/export_clickhouse.py
orchestration/dags/jobs/export/export_clickhouse.py

fix clickhouse: add missing partition key in configs

---

orchestration/dags/dependencies/propilote/sql/tmp/taux_retention_partenaires/propilote_tmp_taux_retention_partenaires.sql

(dbt) Correct wrong alias in propilote_tmp_taux_retention_partenaires

---

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__consultation.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_home_offer_displayed.sql
orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_home_offer_displayed.sql

(dbt) Create native_home_offer_displayed model in int_firebase

---

orchestration/dags/data_gcp_dbt/models/mart/global/filtered/mrt_global__filtered_bookable_event_offer.sql
orchestration/dags/data_gcp_dbt/models/mart/global/filtered/mrt_global__filtered_bookable_event_offer.yml

In this PR, we are creating the model `mrt_global__filtered_bookable_event_offer` to reduce the costs of a Metabase card. Once the backend enables the search function within offers, this filtered model can be removed.

(dbt) Create mrt_global__filtered_bookable_event_offer.sql

---

orchestration/dags/jobs/dbt/dbt_dag_run.py
orchestration/dags/jobs/import/import_analytics.py

(BSR) feat: add longer wait schedule for dbt job

---

orchestration/dags/data_gcp_dbt/models/analytics/deprecated/institution_locations.sql
orchestration/dags/data_gcp_dbt/models/analytics/deprecated/venue_locations.sql
orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__venue.sql
orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__venue.sql
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__venue.sql

(dbt) Delete legacy location models

---

orchestration/dags/data_gcp_dbt/macros/generate_schema_name.sql
orchestration/dags/data_gcp_dbt/macros/get_custom_alias.sql

DE-540/clean-dbt-macros

---

jobs/etl_jobs/internal/export_clickhouse/core/update.py
jobs/etl_jobs/internal/export_clickhouse/main.py
jobs/etl_jobs/internal/export_clickhouse/schema/tmp/intermediate_booking.sql
jobs/etl_jobs/internal/export_clickhouse/schema/tmp/intermediate_collective_booking.sql
orchestration/dags/data_gcp_dbt/models/export/clickhouse/exp_clickhouse__booking.sql
orchestration/dags/data_gcp_dbt/models/export/clickhouse/exp_clickhouse__collective_booking.sql

fix: add update date in tmp schemas

---

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__consultation.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_home_offer_displayed.sql
orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_home_offer_displayed.sql

(dbt) Fix bucket computation in home offer display model

---

orchestration/dags/data_gcp_dbt/models/mart/native/schema/mrt_native__daily_home_recommendation_offer.yml
orchestration/dags/data_gcp_dbt/models/mart/native/schema/mrt_native__event.yml

Cette PR ajoute 3 tests de qualité de données sur la table _analytics_env.native_event_. On vérifie sur la partition de la journée de la veille que : 
- _event_name_ est non nul
- _user_pseudo_ est non nul 
- _booking_id_ existe dans la table _int_global_env.booking_ (ce test n'est pas vérifiable en ehp)

(DE-455) feat/add dbt tests on native event table

---

jobs/etl_jobs/external/batch/batch_client.py
jobs/etl_jobs/external/batch/main.py
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__consultation.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_home_offer_displayed.sql
orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_home_offer_displayed.sql
orchestration/dags/data_gcp_dbt/models/mart/native/schema/mrt_native__daily_home_recommendation_offer.yml
orchestration/dags/data_gcp_dbt/models/mart/native/schema/mrt_native__event.yml

MEP v305.2.0

---

orchestration/dags/jobs/ml/algo_default_deployment.py

[DE-514](ranking) feat: keep only one node worker

---

jobs/etl_jobs/external/gsheet/gsheet.py

[DE-478](gsheet) feat: add tiktok objectives gsheet

---

orchestration/dags/data_gcp_dbt/models/analytics/collective_offer_domain_name.sql
orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__collective_offer_domain.sql
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__collective_offer_domain.sql

The `collective_offer_domain_name` model has many key dependencies in Metabase. We are creating a model in mart/global to allow end users to filter on the columns they want.
Tag a reviewer if necessacy  @Jules-Arbelot 

(dbt) Migrate collective_offer_domain_name

---

jobs/etl_jobs/internal/import_api_referentials/main.py

change/update dataset for offer_types

---

jobs/etl_jobs/external/metabase/data/mappings.json

(dbt) Correct columns mapping

---

jobs/etl_jobs/internal/import_api_referentials/main.py

api_referentials/update types case

---

jobs/etl_jobs/external/addresses/requirements.in
jobs/etl_jobs/external/addresses/requirements.txt
orchestration/dags/jobs/import/import_addresses.py

(addresses) upgrade python version in vm

---

.github/workflows/CD_workflow.yml

[CI/CD](stg) feat: update gcs uri

---

jobs/etl_jobs/external/metabase/data/mappings.json
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_consultation.sql
orchestration/dags/data_gcp_dbt/models/intermediate/metric/discovery/int_metric__discovery_daily_consultation.sql
orchestration/dags/data_gcp_dbt/models/intermediate/metric/discovery/int_metric__discovery_score.sql
orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__consultation.sql

[DA-3762] Update consult tables and create discovery mrt models

---

orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__stock.sql
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__stock.sql

(dbt) Add stock_last_provider_id to mrt_global__stock

---

orchestration/dags/data_gcp_dbt/scripts/sqlfluff_format.sh
orchestration/dags/data_gcp_dbt/scripts/sqlfluff_lint.sh

sqlfluff/add verbose in CI

---

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_consultation.sql
orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_home_offer_displayed.sql

(dbt) Update wrong table reference

---

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__educational_deposit.sql

(dbt) Add educational_year_id column

---

orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_home_offer_displayed.sql

(dbt) Fix linter issues 

---

.github/workflows/reusable_dbt_workflow.yml

comment sqlfluff

---

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_consultation.sql

(fix) Add sync_all_columns in int_firebase__native_consultation

---

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__educational_institution.sql
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__educational_deposit.sql
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__educational_institution.sql

(dbt) Create mrt_global__educational_deposit.sql

---

orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__booking.sql

(dbt) Remove useless filter

---

orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__booking.sql
orchestration/dags/jobs/export/export_posthog.py

MEP v307.1.1

---

jobs/etl_jobs/external/metabase/main.py

(dbt) Add replace_schema_name function

---

jobs/etl_jobs/external/metabase/main.py
orchestration/dags/data_gcp_dbt/models/export/backend/exp_backend__marketing_pro_live_show_email_churned_40_days_ago.sql
orchestration/dags/data_gcp_dbt/models/export/backend/exp_backend__marketing_pro_live_show_email_last_booking_40_days_ago.sql

(dbt) Add two new tables for live show venues to export/backend pipeline

---

orchestration/dags/data_gcp_dbt/models/mart/monitoring/mrt_monitoring__bigquery_cost.sql

feat: add referenced_tables in bq monitoring

---

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__user.sql

fix: is_theme_subscribed field

---

orchestration/dags/data_gcp_dbt/macros/custom_incremental_config.sql
orchestration/dags/data_gcp_dbt/macros/custom_table_config.sql
orchestration/dags/data_gcp_dbt/models/analytics/venue_siren_offers.sql

feat: fix venue_siren_offers (add clustering fields)

---

orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__booking.sql
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__offer_criterion.sql

(dbt) Add cluster to mrt_global__booking and offer_criterion

---

orchestration/dags/data_gcp_dbt/models/analytics/eple_aggregated.sql
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__educational_institution.sql

(dbt) Correct wrong join

---

jobs/ml_jobs/algo_training/deploy_model.py
orchestration/dags/data_gcp_dbt/models/analytics/eple_aggregated.sql
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__educational_institution.sql

# MEP v308.0.0 

---

jobs/etl_jobs/external/metabase/main.py

(fix) metabase script add missing arguments

---

orchestration/airflow/Dockerfile

* Small Fix for Dockerfile of Airflow App. 
* Use uv in Docker to speedup building (4min40 -> 1min30)

[DE](fix): Fix orchestration docker and use uv

---

jobs/etl_jobs/internal/bigquery_alerts/utils.py
jobs/etl_jobs/internal/gcs_seed/tables_config.py
orchestration/dags/data_gcp_dbt/models/analytics/enriched/user_penetration.sql
orchestration/dags/data_gcp_dbt/models/analytics/offer_moderation.sql
orchestration/dags/data_gcp_dbt/models/analytics/region_department.sql
orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__offerer.sql
orchestration/dags/data_gcp_dbt/models/sources.yml

[DE-995] feat: import region_department as seed

---

orchestration/dags/data_gcp_dbt/models/clean/bookable_collective_offer_history.sql
orchestration/dags/data_gcp_dbt/models/clean/bookable_offer_history.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_consultation.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_daily_user_home_module.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_home_offer_displayed.sql
orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_home_module_conversion.sql
orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_home_offer_displayed.sql
orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_home_recommendation_offer.sql

feat: add require_partition_filter to partition tables

---

jobs/ml_jobs/algo_training/offer_categorization/package_api_model.py

Fix model registering for offer categorization model

[DE-601](DS) fix: Remove commented line

---

orchestration/docker-compose.yaml

refactor: Set restart policy for docker services to no

---

jobs/etl_jobs/external/metabase/main.py

(metabase) Table renaming logic in Metabase script

---

jobs/etl_jobs/external/siren/scripts/import_siren.py

fix: add shuffle for stg siren

---

orchestration/dags/data_gcp_dbt/models/analytics/api_logs.sql

feat: reduce api logs timeline

---

orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__educational_institution.sql

(dbt) Update id columns

---

jobs/ml_jobs/embeddings/main.py

fix: do fillna only for datetime

---

orchestration/dags/common/utils.py

fix execution date ->logical_date (airflow 2.x) & add logging

---

orchestration/dags/data_gcp_dbt/models/export/backend/exp_backend__stats_display_cum_daily_consult_per_offerer_last_180_days.sql

increase invocation timeout for long model

---

orchestration/dags/common/utils.py

airflow: delayed waiting operator clean logging

---

orchestration/dags/data_gcp_dbt/scripts/dbt_run.sh
orchestration/dags/data_gcp_dbt/scripts/dbt_run_tag.sh
orchestration/dags/data_gcp_dbt/scripts/dbt_snapshot.sh
orchestration/dags/data_gcp_dbt/scripts/dbt_test_model.sh

Set a trap to ensure the temporary folder is deleted even if the script fails

---

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_partner_retention_data.sql
orchestration/dags/data_gcp_dbt/models/analytics/history/bookable_venue_history.sql
orchestration/dags/data_gcp_dbt/models/analytics/offer_moderation.sql
orchestration/dags/data_gcp_dbt/models/clean/item_metadata.sql

In this PR, we are updating references to the `offer` model in the code. Eventually, we will need to:
- Remove the `offer.sql` model
- Update references to `clean_prod.offer` in Metabase

(dbt) Update offer dependencies

---

orchestration/Makefile
orchestration/docker-compose.yaml

(local airflow) add image for airflow init

---

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__extract_offer.sql
orchestration/dags/dependencies/applicative_database/sql/clean/history/offer_history.sql
orchestration/dags/dependencies/applicative_database/sql/raw/sequential/offer.sql

import offer description from product table

---

orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__offerer.sql

add postal code to offerer table

---

orchestration/dags/dependencies/applicative_database/sql/clean/history/offer_history.sql

[HOTFIX](applicative) fix: typo error sql in join

---

orchestration/dags/dependencies/applicative_database/sql/clean/history/offer_history.sql

[HOTFIX](applicative) fix: typo error

---

jobs/ml_jobs/algo_training/fraud/offer_compliance_model/package_api_model.py

fix: Test if embedding is str before reading with json

---

.github/workflows/reusable_dbt_workflow.yml

Hotfix ci deferal

---

orchestration/dags/common/config.py
orchestration/dags/common/operators/gce.py
orchestration/dags/launch_vm.py

De 565/uv install packages on v ms

---

.github/workflows/reusable_dbt_workflow.yml
jobs/ml_jobs/algo_training/fraud/offer_compliance_model/package_api_model.py
orchestration/dags/common/config.py
orchestration/dags/common/operators/gce.py
orchestration/dags/dependencies/applicative_database/sql/clean/history/offer_history.sql
orchestration/dags/launch_vm.py

MEP 309.0.0

---

orchestration/dags/data_gcp_dbt/dbt_project.yml

DBT: mute warning & set explicit materialization overide flag to false 

---

orchestration/dags/common/utils.py
orchestration/dags/jobs/crons.py
orchestration/dags/jobs/dbt/dbt_weekly_tables.py

(DE-589) fix dbt weekly

---

jobs/ml_jobs/ranking_endpoint/Dockerfile
jobs/ml_jobs/ranking_endpoint/api-requirements.in
jobs/ml_jobs/ranking_endpoint/api-requirements.txt
jobs/ml_jobs/ranking_endpoint/app/app.py
jobs/ml_jobs/ranking_endpoint/app/model.py
jobs/ml_jobs/ranking_endpoint/requirements.in
jobs/ml_jobs/ranking_endpoint/requirements.txt

(ranking) simplify logic, improve efficiency

---

jobs/ml_jobs/ranking_endpoint/Dockerfile
jobs/ml_jobs/ranking_endpoint/api-requirements.in
jobs/ml_jobs/ranking_endpoint/api-requirements.txt
jobs/ml_jobs/ranking_endpoint/app/app.py
jobs/ml_jobs/ranking_endpoint/app/model.py
jobs/ml_jobs/ranking_endpoint/requirements.in
jobs/ml_jobs/ranking_endpoint/requirements.txt
orchestration/dags/data_gcp_dbt/dbt_project.yml
orchestration/dags/jobs/crons.py
orchestration/dags/jobs/dbt/dbt_weekly_tables.py

MEP 309.1.0 

---

jobs/ml_jobs/algo_training/offer_categorization/package_api_model.py

feat: Fix json reading for offer_categorization

---

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__user.sql
orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__user.sql
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__deposit.sql

(dbt) Move join int_geo from int_applicative to int_global

---

orchestration/dags/jobs/dbt/dbt_manual.py

security: constrain commands input in dbt manual dag

---

orchestration/dags/dependencies/propilote/sql/tmp/taux_participation_eac_ecoles/propilote_tmp_participation_eac_ecoles.sql
orchestration/dags/dependencies/propilote/sql/tmp/taux_participation_eac_jeunes/propilote_tmp_participation_eac_jeunes.sql

(dbt) Update schema name in propilote participation queries

---

jobs/etl_jobs/external/batch/batch_client.py
jobs/etl_jobs/external/batch/utils.py

(batch) retrieve utm campaign for ab test

---

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__collective_offer.sql
orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__collective_stock.sql

(dbt) Replace history table reference with snapshot in bookable_venue_history

---

jobs/etl_jobs/external/batch/batch_client.py

(fix) batch remove unused key from dict

---

orchestration/dags/jobs/import/import_addresses.py

(addresses) feat: revert #2949 after re-run

---

Makefile
README.md

doc: Add prerequisite line for make install

---

orchestration/dags/data_gcp_dbt/models/mart/native/schema/mrt_native__event.yml

(DE-588) add volume monitoring on native event

---

Makefile
README.md
orchestration/README.md
orchestration/dags/common/operators/gce.py
orchestration/dags/jobs/import/import_addresses.py
orchestration/dags/launch_vm.py

De 565/VMs uv install

---

orchestration/dags/common/dbt/utils.py
orchestration/dags/jobs/dbt/dbt_dag_run.py

snapshots  mis en places dans (dbt) Add bookable snapshots #3147  dépendent bien de leur modèle parents

DE-577/dbt-dag/include-downstream-snapshots

---

.github/workflows/reusable_dbt_workflow.yml
.github/workflows/scripts/run_dbt_changed_models.sh

(DE-656) exclude elementary in ci

---

jobs/etl_jobs/external/gsheet/gsheet.py

Add gsheet to dwh
https://www.notion.so/passcultureapp/Import-des-effectifs-par-eple-pour-les-Arm-es-e9492cb1322f4ed4ad31a1cf0f53b106

[DE-639](EAC) feat: add missing gsheet for 2024-2025 MA

---

.github/workflows/CI_workflow.yml
.github/workflows/reusable_dbt_workflow.yml
orchestration/dags/data_gcp_dbt/models/mart/native/schema/mrt_native__event.yml

(fix) ci elementary

---

orchestration/dags/common/config.py
orchestration/dags/common/hooks/gce.py
orchestration/dags/common/operators/gce.py
orchestration/dags/jobs/ml/algo_training_offer_compliance_model.py
orchestration/dags/jobs/ml/algo_training_two_towers.py
orchestration/dags/launch_vm.py

* Remove useless gpu in compliance training
* Refacto gpu allocation in gce operator
* Add gce_zone in launch_vm
[JIRA-ticket_number](https://www.notion.so/passcultureapp/880351701699470cb129e4e0ad6bbcba?v=cfbe4b16778b47218f252bd1b5add4a0&p=dc62a1af3f80400ea342d0e5af19c890&pm=s)

[DE-642] Feat/variabilize region and gpu type in launch vm

---

.github/workflows/CI_workflow.yml

(hotfix) update composer bucket in ci workflow

---

.github/workflows/CD_workflow.yml
.github/workflows/CI_workflow.yml

RDP-CI: use github action repo variables  for composer buckets

---

jobs/etl_jobs/internal/export_clickhouse/schema/analytics/daily_aggregated_offer_event.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/monthly_aggregated_offerer_collective_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/monthly_aggregated_offerer_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_offerer_collective_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_offerer_revenue.sql

(DE-649) feat(clickhouse) improve update queries

---

orchestration/dags/common/operators/gce.py
orchestration/dags/jobs/import/import_addresses.py

DE-615/hotfix/source venv after rendering installer template

---

orchestration/dags/jobs/ml/algo_training_two_towers.py

fix(two-tower): render gpu count template

---

.github/workflows/CD_workflow.yml
.github/workflows/CI_workflow.yml
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/daily_aggregated_offer_event.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/monthly_aggregated_offerer_collective_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/monthly_aggregated_offerer_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_offerer_collective_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_offerer_revenue.sql
orchestration/dags/common/operators/gce.py
orchestration/dags/jobs/import/import_addresses.py
orchestration/dags/jobs/ml/algo_training_two_towers.py

MEP 310.4.0

---

orchestration/dags/dependencies/training_data/sql/offer_categorization_offers.sql

fix(ml): update applicative offer db

---

jobs/etl_jobs/external/gsheet/gsheet.py

(HF) feat(gsheet) fix: update gsheet ids for eac

---

.github/workflows/dev_on_pull_request_title_checker.yml

(BSR) feat(ci): add PR title checker

---

orchestration/dags/common/operators/bigquery.py
orchestration/dags/common/operators/biquery.py
orchestration/dags/common/operators/gce.py
orchestration/dags/dependencies/firebase/import_firebase.py
orchestration/dags/jobs/api/export_cloudsql_tables_to_bigquery.py
orchestration/dags/jobs/export/export_propilote.py
orchestration/dags/jobs/export/export_qualtrics_data.py
orchestration/dags/jobs/import/import_applicative_database.py
orchestration/dags/jobs/import/import_appsflyer.py
orchestration/dags/jobs/import/import_batch.py
orchestration/dags/jobs/import/import_dms_subscriptions.py
orchestration/dags/jobs/import/import_downloads.py
orchestration/dags/jobs/import/import_firebase.py
orchestration/dags/jobs/import/import_gcs_seed.py
orchestration/dags/jobs/import/import_sendinblue.py
orchestration/dags/jobs/import/import_sendinblue_historical.py
orchestration/dags/jobs/ml/artist_linkage.py
orchestration/dags/jobs/ml/link_offers.py
orchestration/dags/jobs/ml/offline_recommendations.py

Hotfix airflow operators

---

jobs/ml_jobs/algo_training/offer_categorization/split_data.py
jobs/ml_jobs/algo_training/offer_categorization/train.py
orchestration/dags/jobs/ml/algo_training_offer_categorization.py

* Fix train val split which was classes with only one sample
* Move train val split logic from train.py to split_data.py
* Small Refacto

(HF-126) fix(ds): Fix train/val split in categorization algorithm

---

orchestration/dags/data_gcp_dbt/models/export/posthog/exp_posthog__pro_event.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_event.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_event_flattened.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_visit.sql
orchestration/dags/data_gcp_dbt/models/mart/pro/mrt_pro__event.sql

(DA-3254) feat(analytics): add suggested category fields in pro event

---

orchestration/dags/dependencies/applicative_database/sql/raw/parallel/pricing.sql

This PR adds event_id to pricing table (raw and clean env)
Tag a reviewer if necessacy  @cdelabre @LucileRainteau 

DA-Finance- add event id to pricing table

---

orchestration/dags/data_gcp_dbt/models/analytics/firebase/firebase_visits.sql
orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__event.sql

(DA-3270) feat(analytics): Add ConsultArtist event to native table and posthog

---

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__collective_offer_domain.sql

This PR adds collective offer templates to mrt_global__collective_offer_domain
Tag a reviewer if necessacy  @LucileRainteau @cdelabre 
[JIRA-ticket_number](https://www.notion.so/passcultureapp/Remonter-les-educational_domain-des-offres-vitrines-collectives-5c2ae6510a4641e1967b6e39ddf3bf39?pvs=4)

(DA-1786) fix(bq_jobs): Add collective offer template domain info

---

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__extract_offer.sql

(BSR) fix(applicative): typo error

---

orchestration/dags/dependencies/applicative_database/sql/raw/parallel/pricing.sql

(HF) fix(applicative): typo error

---

orchestration/Makefile
orchestration/docker-compose.yaml

(BSR) refactor(DE): Update docker-compose commands and config

---

orchestration/dags/data_gcp_dbt/dbt_project.yml
orchestration/dags/data_gcp_dbt/macros/create_schema_dev.sql
orchestration/dags/data_gcp_dbt/macros/generate_schema_name.sql
orchestration/dags/data_gcp_dbt/macros/set_table_expiration_dev.sql

(DE-652) feat(analytics): custom schemas for local development

---

.github/pull_request_template.md

(BSR) docs(github): add PR title valid format in template

---

.github/pull_request_template.md
orchestration/Makefile
orchestration/dags/data_gcp_dbt/dbt_project.yml
orchestration/dags/data_gcp_dbt/macros/create_schema_dev.sql
orchestration/dags/data_gcp_dbt/macros/generate_schema_name.sql
orchestration/dags/data_gcp_dbt/macros/set_table_expiration_dev.sql
orchestration/dags/dependencies/applicative_database/sql/raw/parallel/pricing.sql
orchestration/dags/jobs/administration/bigquery_alerts.py
orchestration/docker-compose.yaml

MEP 311.1.0

---

jobs/etl_jobs/external/dms/utils.py

Add a procedure_id for dms pro export

---

jobs/ml_jobs/record_linkage/main.py
jobs/ml_jobs/record_linkage/postprocess.py
jobs/ml_jobs/record_linkage/tools/linkage.py

(DE) fix(linkage): Refactor variable names to use correct naming convention

---

jobs/etl_jobs/internal/export_clickhouse/schema/analytics/monthly_aggregated_venue_collective_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/monthly_aggregated_venue_individual_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/monthly_aggregated_venue_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_venue_collective_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_venue_individual_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_venue_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/intermediate/booking.sql
jobs/etl_jobs/internal/export_clickhouse/schema/intermediate/collective_booking.sql
jobs/etl_jobs/internal/export_clickhouse/schema/tmp/intermediate_booking.sql
jobs/etl_jobs/internal/export_clickhouse/schema/tmp/intermediate_collective_booking.sql
orchestration/dags/data_gcp_dbt/models/export/clickhouse/exp_clickhouse__booking.sql
orchestration/dags/data_gcp_dbt/models/export/clickhouse/exp_clickhouse__collective_booking.sql
orchestration/dags/dependencies/export_clickhouse/export_clickhouse.py
orchestration/dags/jobs/export/export_clickhouse.py

(DE-669) refactor(clickhouse): switch revenue aggregation from offerer to venue

---

Makefile

(DE-688) fix(makefile): Fix bash command not working on MacOS

---

orchestration/dags/data_gcp_dbt/models/mart/global/filtered/mrt_global__filtered_bookable_event_offer.sql

with:
- ticket surrounded by parenthesis:
The first part must be one of the following strings: DA, DE, AE, DS, HF, BSR, PC.
Optionally, a hyphen followed by one or more digits (e.g., -1234)
- type :
The second part to specify the type of change one of the following
build, lint, ci, docs, feat, fix, perf, refactor, test, core, dbt
- topic within parenthesis: 1 word e.g., (dag)
- comment: tell us your life
examples:
- :white_check_mark: (DE-124) refactor(firebase): update source field
- :x: (DE-124) refactor (firebase): update source field
- :x: (DE-504) airflow(dbt): add operator in dbt dag
- :white_check_mark: (BSR) docs(github): add PR title valid format in template
* …

(DA) feat(analytics): add field to filtered bookable event table

---

.github/PULL_REQUEST_TEMPLATE/DA_ticket_template.md
.github/PULL_REQUEST_TEMPLATE/DE_ticket_template.md
.github/PULL_REQUEST_TEMPLATE/DS_ticket_template.md
.github/PULL_REQUEST_TEMPLATE/Hotfix_template.md
.github/pull_request_template.md

(BSR) refactor(templates): Refacto github PR templates

---

orchestration/dags/jobs/export/export_clickhouse.py

(DE) fix(clickhouse): typo flag name

---

orchestration/dags/data_gcp_dbt/models/intermediate/pcapi/int_pcapi__collective_log.sql
orchestration/dags/data_gcp_dbt/models/intermediate/pcapi/int_pcapi__native_log.sql

(HF) fix(dbt): typo for incremental jobs

---

orchestration/dags/data_gcp_dbt/models/intermediate/source/int_source__offer.sql
orchestration/dags/data_gcp_dbt/models/intermediate/source/int_source__offerer.sql
orchestration/dags/data_gcp_dbt/snapshots/source/snapshot__offer_backend.sql
orchestration/dags/data_gcp_dbt/snapshots/source/snapshot__offerer_backend.sql

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(DE) fix(dbt): rename source snapshot to avoid database collision with macro

---

orchestration/dags/data_gcp_dbt/.env.buckets
orchestration/dags/data_gcp_dbt/scripts/defer_local_run.sh

(DE-519) feat(dbt): artifacts pulling and dbt hook for local dev automatic deferal

---

jobs/etl_jobs/internal/export_clickhouse/schema/analytics/monthly_aggregated_venue_collective_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/monthly_aggregated_venue_individual_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/monthly_aggregated_venue_revenue.sql

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(DE-668) fix(clickhouse): typo table names

---

orchestration/dags/data_gcp_dbt/scripts/dbt_run.sh
orchestration/dags/data_gcp_dbt/scripts/dbt_run_tag.sh
orchestration/dags/data_gcp_dbt/scripts/dbt_snapshot.sh
orchestration/dags/data_gcp_dbt/scripts/dbt_test_model.sh

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(DE-624) refactor(dbt): fix tmp_artifacts cleaning

---

.pre-commit-config.yaml

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(BSR) refactor(precommit): Move ruff and sqlfmt to precommit venv

---

orchestration/dags/jobs/export/export_clickhouse.py
orchestration/dags/jobs/export/export_posthog.py

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(BSR) feat(export): add slack alert for clickhouse+posthog

---

jobs/etl_jobs/internal/export_clickhouse/schema/analytics/daily_aggregated_offer_event.sql

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(DE) perf(clickhouse): optimize query aggregation order

---

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__stock.sql
orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__stock.sql
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__stock.sql
orchestration/dags/dependencies/applicative_database/sql/raw/parallel/stock.sql

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(DA-3309) feat(analytics): kill offerer_address_id in tables stock

---

jobs/ml_jobs/algo_training/two_towers_model/train.py
orchestration/dags/jobs/ml/algo_training_two_towers.py

https://2f1b194c7b8f433090bd319b1e2305f7-dot-europe-west1.composer.googleusercontent.com/dags/algo_training_two_towers/grid?dag_run_id=manual__2024-10-17T07%3A38%3A27%2B00%3A00&task_id=start

(BSR) fix(ml): force GPU use

---

jobs/ml_jobs/retrieval_vector/deploy_semantic.py
jobs/ml_jobs/retrieval_vector/utils.py

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(DE-233) feat(retrieval): adjust index + embedding size

---

jobs/etl_jobs/internal/export_clickhouse/schema/analytics/daily_aggregated_offer_event.sql
jobs/ml_jobs/algo_training/two_towers_model/train.py
jobs/ml_jobs/retrieval_vector/deploy_semantic.py
jobs/ml_jobs/retrieval_vector/utils.py
orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__stock.sql
orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__stock.sql
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__stock.sql
orchestration/dags/dependencies/applicative_database/sql/raw/parallel/stock.sql
orchestration/dags/jobs/export/export_clickhouse.py
orchestration/dags/jobs/export/export_posthog.py
orchestration/dags/jobs/ml/algo_training_two_towers.py

MEP 312.3.0

---

jobs/etl_jobs/external/metabase-archiving/dependencies.py

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(DE-714) fix(metabase): fix schema dependency

---

orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__outgoing_cohorts.sql

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: …

(DA-3315) feat(Analytics): Update outgoing_cohorts model

---

orchestration/dags/data_gcp_dbt/models/clean/applicative/accessibility_provider.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/bank_account.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/beneficiary_fraud_review.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/beneficiary_import.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/beneficiary_import_status.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/cashflow_log.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/educational_domain_venue.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/educational_redactor.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/login_device_history.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/offer_report.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/opening_hours.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/payment_message.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/price_category.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/price_category_label.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/recredit.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/trusted_device.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/venue_registration.sql

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(DE-723) refactor(dbt): remove clean applicative batch0

---

jobs/etl_jobs/external/siren/scripts/import_siren.py
jobs/etl_jobs/external/siren/scripts/utils.py
orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_reimbursement_data.sql
orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_suivi_dms_adage.sql
orchestration/dags/data_gcp_dbt/models/analytics/offer_moderation.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/invoice_line.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/offerer.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/venue_contact.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/venue_label.sql
orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__offerer.sql
orchestration/dags/dependencies/qualtrics/sql/analytics/enriched_qualtrics_pro.sql

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(DE-724) refactor(dbt): remove clean applicative batch0 2/2

---

orchestration/dags/dependencies/qualtrics/sql/analytics/enriched_qualtrics_pro.sql
orchestration/dags/dependencies/training_data/sql/training_data_bookings.sql

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(AE) refactor(dbt): update dependencies applicative_database_booking

---

jobs/etl_jobs/internal/export_clickhouse/core/update.py
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/daily_aggregated_offer_event.sql
jobs/etl_jobs/internal/export_clickhouse/schema/intermediate/native_event.sql
jobs/etl_jobs/internal/export_clickhouse/schema/tmp/intermediate_native_event.sql
orchestration/dags/jobs/export/export_clickhouse.py

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(DE-726) perf(clickhouse): refactor native event logic

---

orchestration/dags/data_gcp_dbt/scripts/defer_local_run.sh

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(DE-519) fix(deferal): refactor script and Notion doc

---

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__offer.sql
orchestration/dags/data_gcp_dbt/models/raw/applicative/raw_applicative__offer_lite.sql
orchestration/dags/dependencies/applicative_database/sql/clean/history/offer_history.sql
orchestration/dags/dependencies/applicative_database/sql/raw/sequential/offer.sql

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(DE) refactor(rawimport): remove column offer duration minutes

---

orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__booking.sql

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(DE) fix(dbt): Fix booking join to remove bookings with null values

---

orchestration/dags/common/operators/gce.py

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(BSR) fix(uv): Remove uv pip sync in SSHGCE operator

---

jobs/etl_jobs/external/metabase-archiving/dependencies.py

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(HF) fix(metabase): fix dependency table

---

.github/workflows/CD_workflow.yml

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(DE) fix(ci): format output

---

orchestration/dags/dependencies/qualtrics/sql/analytics/enriched_qualtrics_pro.sql

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(HF) fix(qualtrics): enriched_qualtrics_pro

---

orchestration/dags/dependencies/training_data/sql/training_data_bookings.sql
orchestration/dags/dependencies/training_data/sql/training_data_clicks.sql
orchestration/dags/dependencies/training_data/sql/training_data_favorites.sql

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(HF) fix(ml): training typo fix

---

orchestration/dags/data_gcp_dbt/scripts/dbt_clean.sh
orchestration/dags/data_gcp_dbt/scripts/dbt_compile.sh
orchestration/dags/data_gcp_dbt/scripts/dbt_deps.sh
orchestration/dags/data_gcp_dbt/scripts/dbt_manifest.sh
orchestration/dags/data_gcp_dbt/scripts/dbt_run.sh
orchestration/dags/data_gcp_dbt/scripts/dbt_run_tag.sh
orchestration/dags/data_gcp_dbt/scripts/dbt_snapshot.sh
orchestration/dags/data_gcp_dbt/scripts/dbt_test.sh
orchestration/dags/data_gcp_dbt/scripts/dbt_test_model.sh
orchestration/dags/data_gcp_dbt/scripts/elementary_send_report.sh

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(DE) fix(airflow): catch & propagate scripts exit code to airflow

---

orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__consultation.sql
orchestration/dags/dependencies/training_data/sql/compliance_offers.sql

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(DE) fix(sherrif): fix field names transfo & training

---

jobs/etl_jobs/external/qualtrics/main.py
orchestration/dags/jobs/import/import_qualtrics.py

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(HF) fix(qualtrics): remove airflow task

---

jobs/ml_jobs/artist_linkage/extract_from_wikidata.py

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(DE) feat(wikidata): add retries to wikidata queries

---

jobs/ml_jobs/artist_linkage/extract_from_wikidata.py

Reverts pass-culture/data-gcp#3358

(BSR) refactor(DE): Revert "(DE) feat(wikidata): add retries to wikidata queries"

---

orchestration/dags/data_gcp_dbt/dbt_project.yml
orchestration/dags/data_gcp_dbt/macros/custom_test/not_null_proportion_test.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_event.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_event_flattened.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/schema.yml
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/schema/int_firebase__native_event_flattened.yaml

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(DE-735) feat(dbt): add proportion_test and move tracking test to start of the transfo

---

jobs/etl_jobs/external/brevo/brevo_newsletters.py
jobs/etl_jobs/external/brevo/main.py

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(DE-718) refactor(brevo): plug to globalStatistics

---

.github/workflows/ci_gpt.yml
jobs/etl_jobs/external/brevo/brevo_newsletters.py
jobs/etl_jobs/external/brevo/main.py
jobs/ml_jobs/retrieval_vector/deploy_model.py
jobs/ml_jobs/retrieval_vector/deploy_semantic.py
orchestration/dags/data_gcp_dbt/dbt_project.yml
orchestration/dags/data_gcp_dbt/macros/custom_test/not_null_proportion_test.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_event.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_event_flattened.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/schema.yml
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/schema/int_firebase__native_event_flattened.yaml
orchestration/dags/jobs/ml/algo_default_deployment.py
orchestration/dags/jobs/ml/retrieval_vector_build.py
orchestration/dags/jobs/ml/retrieval_vector_semantic_build.py

 MEP: 314.1.1

---

orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_home_module_conversion.sql

* This PR adds a new column total_clicks to the model (currently, only total_session_with_click is displayed)
* Tag a reviewer if necessacy  @Jules-Arbelot 
with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) refactor (firebase): update source field …

(DA-888) feat(dbt): Add total click to native_daily_home_module_conversion model

---

orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__consultation.sql

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(DA-3333) feat(analytics): Fix consultation model

---

.github/workflows/CD_workflow.yml

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(DE) fix(CD): fix workflow expression evaluation 

---

Makefile

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(DE) fix(sqlmt): exclude whole dbt target folder

---

.github/PULL_REQUEST_TEMPLATE/DA_ticket_template.md
.github/PULL_REQUEST_TEMPLATE/DE_ticket_template.md
.github/PULL_REQUEST_TEMPLATE/DS_ticket_template.md
.github/PULL_REQUEST_TEMPLATE/Hotfix_template.md

* Move PR title linting description into dropdown
* tips to review: 
** you can use the "rich diff" view by clicking on the icon in the diff view🗒️ 
with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(DE-705) refactor(doc): Move PR title linting rules into dropdown

---

.github/workflows/reusable_build_image.yml
orchestration/k8s-airflow/README.md

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(DE) ci(deploy): switch image tag to version (asked by ops)

---

orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__consultation.sql

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(DA-3383) feat(Analytics): fix multi venue in consultation offer

---

.github/pull_request_template.md
orchestration/dags/dependencies/ml/linkage/sql/artists_to_link.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DE-739) fix(artist): Fix offer_number and add item_number computation

---

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_visit.sql

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(DA-3886) docs(analytics): Update a page_name in firebase pro visits

---

orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__venue.sql
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__venue.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA-3687) feat(Analytics): Add venue_image_source field

---

orchestration/dags/dependencies/ml/linkage/create_artist_table.py
orchestration/dags/dependencies/ml/linkage/create_product_artist_link_table.py
orchestration/dags/dependencies/ml/linkage/sql/artists_to_link.sql
orchestration/dags/dependencies/ml/linkage/sql/create_artist_table.sql
orchestration/dags/dependencies/ml/linkage/sql/create_product_artist_link_table.sql
orchestration/dags/jobs/ml/artist_linkage.py

* Create artist table and artist product link table
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: …

(DE-757) feat(artist): Create product artist link table

---

jobs/ml_jobs/artist_linkage/get_wikimedia_commons_license.py
orchestration/dags/dependencies/ml/linkage/sql/create_artist_table.sql
orchestration/dags/jobs/ml/artist_linkage.py

* Fetch wikimedia licenses
* Export information in artist tables
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(DE-765) feat(artist): Add license on wikimedia images

---

orchestration/dags/data_gcp_dbt/macros/custom_test/cardinality_equality.sql
orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__booking.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(DE-670) feat(dataquality): add cardinality test

---

orchestration/dags/dependencies/ml/linkage/create_artist_alias_table.py
orchestration/dags/dependencies/ml/linkage/sql/create_artist_alias_table.sql
orchestration/dags/jobs/ml/artist_linkage.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(DE-759) feat(artist): Add create artist alias table

---

orchestration/dags/data_gcp_dbt/models/mart/collective/mrt_collective__adage_log.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* …

(DA-3691) feat(Analytics): add field in collective_adage_logs

---

jobs/etl_jobs/external/gsheet/gsheet.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* …

(DA-2563) feat(Analytics): add cold data meg scholar groups

---

orchestration/dags/data_gcp_dbt/models/intermediate/pcapi/int_pcapi__log.sql
orchestration/dags/data_gcp_dbt/models/intermediate/pcapi/int_pcapi__native_user_feedback.sql
orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__log.sql

with:
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(DA-3785) feat(Analytics): Add int_pcapi__native_user_feedback model

---

.github/workflows/on_cd__workflow.yml
.github/workflows/reusable_deploy_mkdocs.yml
orchestration/dags/data_gcp_dbt/tests/generic/generic_has_no_missing_partitions.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DE) ci(deployment): temporary fix disable doc for particular test in CD

---

Makefile
README.md

- Update install doc and install targets
- Might be updated after a fresh install
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) refactor (firebase): update source …

(BSR) docs(install): Remove pyenv from install

---

Makefile
README.md

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(BSR) docs(install): Fix doc for orchestration installation

---

orchestration/dags/data_gcp_dbt/models/clean/bookable_offer_history.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(DE) refactor(dbt): improve bookable_offer_history logic

---

jobs/etl_jobs/internal/export_clickhouse/core/utils.py
orchestration/dags/common/operators/gce.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(BSR) feat(db): update clickhouse secrets

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__offer.md
orchestration/dags/data_gcp_dbt/models/clean/applicative/offer.sql
orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__offer.sql
orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__offer_item_id.sql
orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__offer.sql
orchestration/dags/data_gcp_dbt/models/intermediate/raw/int_raw__offer.sql
orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__offer.yml
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__offer.sql
orchestration/dags/data_gcp_dbt/models/raw/applicative/raw_applicative__offer_lite.sql
orchestration/dags/data_gcp_dbt/snapshots/applicative/snapshot__applicative_offer.sql
orchestration/dags/data_gcp_dbt/snapshots/raw_applicative/snapshot_raw__offer.sql
orchestration/dags/dependencies/applicative_database/sql/clean/history/offer_history.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DE) refactor(offer): align field offer_updated_date

---

orchestration/dags/data_gcp_dbt/dbt_project.yml
orchestration/dags/data_gcp_dbt/macros/database_utils/custom_snapshot_config.sql
orchestration/dags/data_gcp_dbt/snapshots/intermediate/global/snasphot_intermediate__bookable_collective_offer.sql
orchestration/dags/data_gcp_dbt/snapshots/intermediate/global/snasphot_intermediate__bookable_offer.sql
orchestration/dags/data_gcp_dbt/snapshots/raw_applicative/snapshot_raw__collective_offer.sql
orchestration/dags/data_gcp_dbt/snapshots/raw_applicative/snapshot_raw__deposit.sql
orchestration/dags/data_gcp_dbt/snapshots/raw_applicative/snapshot_raw__offer.sql

…to current_date when item disapears from snapshoted table)
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
* topic …

(DE-791) fix(snapshot): enforce invalidate_hard_deletes=true 

---

Makefile
README.md

* Udate docs for macos
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) airflow(firebase): …

(BSR) docs(install): Update doc for macos

---

orchestration/dags/data_gcp_dbt/models/raw/applicative/raw_applicative__offer_lite.sql
orchestration/dags/data_gcp_dbt/snapshots/raw_applicative/snapshot_raw__offer.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DE) fix(snapshot): applicative_offer

---

jobs/etl_jobs/internal/export_clickhouse/core/utils.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(HF) fix(clickhouse): secret typo error

---

jobs/ml_jobs/artist_linkage/extract_from_wikidata.py
jobs/ml_jobs/artist_linkage/queries/extract_gkg_artists.rq

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(BSR) fix(artist): Remove profession in gkg query

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column_educational_deposit.md

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* …

(DA-3878) fix(dbt): Add missing doc for educational deposit

---

.github/workflows/on_pr_review__gpt.yml

* Fix permissions 
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* …

(BSR) fix(gpt): Fix permissions for gpt review gh yaml

---

orchestration/dags/data_gcp_dbt/macros/test_utils/get_missing_date_partitions.sql
orchestration/dags/data_gcp_dbt/tests/generic/generic_has_no_missing_partitions.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(BSR) fix(dbt): report missing partitions in test result

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__educational_deposit.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__institution.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column_educational_deposit.md
orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__educational_deposit.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(BSR) dbt(docs): add missing column in schema

---

jobs/etl_jobs/internal/export_clickhouse/schema/analytics/monthly_aggregated_venue_individual_revenue.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DE-814) fix(clickhouse): review individual booking amount definition

---

orchestration/README.md
orchestration/docker-compose.yaml

* updated `README.md` of local airflow installation for clarity
* removed version parameter from `docker-compose.yml` because obsolete
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) refactor (firebase): update …

(BSR) fix(doc): update for airflow local installation with docker

---

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_event.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_event_flattened.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(BSR) dbt(incremental): prevent erasing native_event & flattened while running dbt in full refresh mode

---

orchestration/dags/data_gcp_dbt/dbt_project.yml
orchestration/dags/data_gcp_dbt/models/analytics/enriched/aggregated_daily_offer_consultation_data.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_consultation.sql
orchestration/dags/data_gcp_dbt/models/intermediate/metric/discovery/int_metric__discovery_daily_consultation.sql
orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__consultation.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(BSR) dbt(incremental): variabilize full_refresh_lookback and enforce partition filtering with full refresh

---

jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_venue_individual_revenue.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DE) fix(clickhouse): fix yearly revenue value

---

orchestration/README.md
orchestration/airflow/Dockerfile.netskope
orchestration/docker-compose.yaml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: …

(DE-433) fix(netskope): install airflow via netskope v2 with two dockerfiles

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__user.md
orchestration/dags/data_gcp_dbt/models/clean/user_beneficiary.sql
orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__user.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA-3876) feat(Analytics): Refacto user activity

---

Makefile

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(BSR) docs(install): Update install target to work for DA

---

jobs/etl_jobs/external/dms/utils.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DE-844) fix(dms): remove problematic entry from demarches_pro list

---

jobs/ml_jobs/artist_linkage/extract_from_wikidata.py

- Clear qlever cache before fetching wikidata to prevent resource issues
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) refactor (firebase): update source field …

(DE-837) feat(artist): Add cache reset before querying qlever

---

jobs/ml_jobs/artist_linkage/match_artists_on_wikidata.py
jobs/ml_jobs/artist_linkage/utils/gcs_utils.py
orchestration/dags/common/config.py
orchestration/dags/jobs/ml/artist_linkage.py
orchestration/dags/jobs/ml/artist_wikidata_dump.py

* Add artist_wikidata_dump DAG
* Move wikidata extraction from artist_linkage DAG to artist_wikidata_dump DAG
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(DE-855) feat(artist): Separate wikidata extraction from linkage

---

orchestration/dags/data_gcp_dbt/models/machine_learning/linkage/ml_linkage__artist_name_to_link.sql

* Set ml_linkage__artist_name_to_link as a table to allow download as parquet
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) refactor (firebase): update source field **(space between …

(BSR) fix(artist): Set ml_linkage__artist_name_to_link as a view to allow bq downloads

---

orchestration/dags/data_gcp_dbt/models/intermediate/raw/int_raw__offer.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DE-815) refactor(snapshot): reset dbt filter in int_raw__offer

---

jobs/etl_jobs/external/dms/main.py
jobs/etl_jobs/external/siren/scripts/utils.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(DE-872) fix(mob): add certificate path in siren + dms api call

---

orchestration/dags/data_gcp_dbt/models/intermediate/raw/int_raw__offer.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(HF) fix(offer): rollback int_raw__offer

---

orchestration/dags/data_gcp_dbt/models/clean/qpi_answers_v4.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(BSR) fix(qualtrics): remove order by

---

orchestration/dags/common/alerts.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(BSR) fix(alerts): fix util function to remove alerting when not needed

---

orchestration/dags/jobs/administration/bigquery_alerts.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(BSR) feat(alerting): alert when alerting fails (fix false negative)

---

orchestration/Makefile
orchestration/README.md
orchestration/airflow/.gitignore
orchestration/airflow/Dockerfile.netskope
orchestration/airflow/etc/.gitignore

* This PR refactors code with minor changes:
- move certficate file to /etc folder with gcp key
- add .pem file to gitignores
- change README.md to account for these changes
* `make build` tested locally 
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
* topic within parenthesis: 1 word e.g., …

(DS) refactor(dockerfiles): change placement of certificate file and update README and .gitignore

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/tracking/column__event.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/tracking/column__native_event.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/native/description__mrt_native__event.md

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA-3899) docs(dbt): Add dbt doc for mrt native event

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__educational_deposit.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/global/description__mrt_global__educational_deposit.md

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA-3899) docs(dbt): Add dbt doc for global educational deposit

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__favorite.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__user.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/global/description__mrt_global__favorite.md
orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__user.sql
orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__favorite.yml
orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__user.yml
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__favorite.sql
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__user.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA-3899) docs(dbt): Add dbt doc for global favorite

---

jobs/etl_jobs/internal/export_clickhouse/schema/analytics/monthly_aggregated_venue_collective_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/monthly_aggregated_venue_individual_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_venue_collective_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_venue_individual_revenue.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DE-816) fix(clickhouse): apply same revenue formula as BO

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__venue_tag.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/global/description__mrt_global__venue_tag.md

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA-3547) docs(dbt): Add doc venue_tag_label

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__cultural_partner.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/global/description__mrt_global__cultural_partner.md

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA-3526) docs(dbt): Add doc cultural partner

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__offer_criterion.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/global/description__mrt_global__offer_criterion.md

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA) feat(Analytics): Add table and column descriptions on offer_criterion

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__educational_institution.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__institution.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__metric.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/global/description__mrt_global__educational_institution.md

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA-3899) docs(dbt): Add doc for global educational institution 

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__offerer_tag.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/global/description__mrt_global__offerer_tag.md

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA-3899) docs(dbt): Add dbt doc for offerer tag table

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/pcapi/column__log.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/pro/description__mrt_pro__log.md

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA-3548) docs(dbt): Add dbt doc for pro log nouvelle version

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__local_authority.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/global/description__mrt_global__local_authority.md

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA-3899) docs(dbt): Add dbt doc for local authority

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__address.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__offerer_address.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/global/description__mrt_global__address.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/global/description__mrt_global__offerer_address.md

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA) feat(analytics): Address tables documentation

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__venue_provider.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/global/description__mrt_global__venue_provider.md

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA-3899) docs(dbt): Add dbt doc for venue provider

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__collective_offer.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__collective_offer_domain.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/global/description__mrt_global__collective_offer_domain.md

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA) feat(Analytics): Add table and column descriptions on collective offer domain

---

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__user.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA-3876) feat(Analytics): Update refacto user activity 

---

jobs/ml_jobs/algo_training/two_towers_model/utils/evaluate.py
jobs/ml_jobs/clusterisation/tools/clusterisation.py
jobs/ml_jobs/ranking_endpoint/deploy_model.py
jobs/ml_jobs/reduction/dimension_reduction.py
jobs/ml_jobs/reduction/tools/dimension_reduction.py
orchestration/airflow/Dockerfile
orchestration/airflow/Dockerfile.netskope

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(BSR) refactor(sonarqube): Sonarqube security issues (random seeds in sklearn functions and security check for curl in dockerfiles)

---

orchestration/dags/jobs/ml/link_items.py

* Switch install to uv in link items
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(BSR) fix(link_items): Migrate link_items to uv

---

orchestration/dags/jobs/import/import_social_media.py

* replace {{ ds }} by {{ yesterday() }} to enable consistency between scheduled and manual
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) refactor (firebase): update source field …

(BSR) fix(DE): Fix tiktok date

---

orchestration/dags/jobs/import/import_social_media.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(BSR) fix(social): Use ds for scheduled DAGs, yesteday for manual

---

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__offer_metadata.sql

(DE-866) feat(dbt): Enhance image URL generation logic in offer metadata model

---

jobs/etl_jobs/internal/export_clickhouse/schema/analytics/monthly_aggregated_venue_collective_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/monthly_aggregated_venue_individual_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/monthly_aggregated_venue_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_venue_collective_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_venue_individual_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_venue_revenue.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DE-814) fix(clickhouse): fix join

---

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__user.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA-3876) feat(Analytics): Fix user activity

---

orchestration/dags/data_gcp_dbt/models/intermediate/raw/int_raw__stock.sql
orchestration/dags/data_gcp_dbt/models/raw/applicative/raw_applicative__stock_lite.sql
orchestration/dags/data_gcp_dbt/snapshots/raw_applicative/snapshot_raw__stock.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DE-789) refactor(import): migrate stock snapshot

---

jobs/etl_jobs/internal/export_clickhouse/schema/analytics/monthly_aggregated_venue_collective_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/monthly_aggregated_venue_individual_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/monthly_aggregated_venue_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_venue_collective_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_venue_individual_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_venue_revenue.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(BSR) fix(clickhouse): fix join on renamed column

---

jobs/ml_jobs/artist_linkage/queries/extract_book_artists.rq
jobs/ml_jobs/artist_linkage/queries/extract_gkg_artists.rq
jobs/ml_jobs/artist_linkage/queries/extract_movie_artists.rq
jobs/ml_jobs/artist_linkage/queries/extract_music_artists.rq
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/ml/column__artist.md
orchestration/dags/data_gcp_dbt/models/export/backend/_schema/exp_backend__artist.yml
orchestration/dags/data_gcp_dbt/models/export/backend/exp_backend__artist.sql
orchestration/dags/data_gcp_dbt/models/machine_learning/linkage/_schema/ml_linkage__artist.yml
orchestration/dags/data_gcp_dbt/models/machine_learning/linkage/ml_linkage__artist.sql

* remove artist_gender from artist linkage DAG
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) …

(DE-898) refactor(artist): Remove artist gender

---

orchestration/dags/jobs/ml/algo_default_deployment.py
orchestration/dags/jobs/ml/retrieval_vector_build.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(BSR) refactor(uv): use uv in deployment dags

---

jobs/etl_jobs/internal/export_clickhouse/schema/analytics/monthly_aggregated_venue_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_venue_revenue.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(BSR) fix(clickhouse): fix  join

---

orchestration/dags/dependencies/applicative_database/sql/raw/parallel/action_history.sql

* This PR adds new columns in action_history, previously stored in the json_data column. Those columns refer to the informations updated by users in app (activity, postal_code); in order to easily measure feature usage.
* Tag a reviewer if necessacy @Jules-Arbelot 
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
* …

(DA-3788) feat(analytics): Add user status update (activity, postal_code) in action history

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__local_authority.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__offerer.md
orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__offerer.sql
orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__offerer.yml
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__offerer.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA-3906) feat(analytics): Add missing local authority info to offerer model

---

orchestration/dags/jobs/ml/embedding_extraction_item.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DE-921) refactor(uv): migrate embedding_extraction_item

---

orchestration/dags/jobs/ml/link_offers.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DE-921) refactor(uv): migrate link_offers

---

orchestration/dags/jobs/ml/embedding_reduction_item.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DE-921) refactor(uv): migrate embedding_reduction_item

---

orchestration/dags/jobs/import/import_api_referentials.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DE-921) refactor(uv): migrate import_api_referentials

---

orchestration/dags/jobs/ml/offline_recommendations.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DE-921) refactor(uv): migrate offline_recommendations

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__metric.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__offer.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__user.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/ml/column__artist.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/ml/column_embedding.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/tracking/column__event.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/machine_learning/compliance/description__ml_compliance__training_data_offer.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/machine_learning/linkage/description__ml_linkage__artist.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/machine_learning/linkage/description__ml_linkage__product_artist_link.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/machine_learning/offer_categorization/description__ml_offer_categorization__training_data_offer.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/machine_learning/recommendation/description__ml_reco__training_data_booking.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/machine_learning/recommendation/description__ml_reco__training_data_click.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/machine_learning/recommendation/description__ml_reco__training_data_favorite.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/machine_learning/recommendation/description__ml_reco__training_data_item_feature.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/machine_learning/recommendation/description__ml_reco__training_data_user_feature.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/machine_learning/retrieval/description__ml_retrieval__semantic_vector_item_embedding.md
orchestration/dags/data_gcp_dbt/models/machine_learning/compliance/_schema/ml_compliance__training_data_offer.yml
orchestration/dags/data_gcp_dbt/models/machine_learning/offer_categorization/_schema/ml_offer_categorization__training_data_offer.yml
orchestration/dags/data_gcp_dbt/models/machine_learning/offer_categorization/ml_offer_categorization__training_data_offer.sql
orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/_schema/ml_reco__training_data_booking.yml
orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/_schema/ml_reco__training_data_click.yml
orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/_schema/ml_reco__training_data_favorite.yml
orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/_schema/ml_reco__training_data_item_feature.yml
orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/_schema/ml_reco__training_data_user_feature.yml
orchestration/dags/data_gcp_dbt/models/machine_learning/retrieval/_schema/ml_retrieval__semantic_vector_item_embedding.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(DE-908) docs(dbt): Add dbt tables doc for training_data

---

orchestration/dags/jobs/ml/embedding_clusterisation_item.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DE-921) refactor(uv): migrate embedding_clusterisation_item

---

jobs/etl_jobs/internal/export_clickhouse/schema/analytics/monthly_aggregated_venue_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_venue_revenue.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(BSR) fix(clickhouse): date interval for venue revenue aggregation

---

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_daily_user_video_conversion.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_daily_user_video_module.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_video_event.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA-3796) feat(analytics): Update video models - 2

---

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_suivi_dms_adage.sql
orchestration/dags/data_gcp_dbt/models/analytics/history/bookable_venue_history.sql
orchestration/dags/data_gcp_dbt/models/analytics/offer_moderation.sql
orchestration/dags/data_gcp_dbt/models/clean/reimbursement_collective.sql
orchestration/dags/data_gcp_dbt/models/export/backend/exp_backend__adage_home_playlist_local_offerers.sql
orchestration/dags/data_gcp_dbt/models/export/backend/exp_backend__adage_home_playlist_new_template_offers.sql
orchestration/dags/data_gcp_dbt/models/export/backend/exp_backend__adage_home_playlist_new_venues.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA-3568) feat(dbt): Remove dependencies to clean venue model

---

orchestration/dags/data_gcp_dbt/models/analytics/offer_moderation.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA-3923) feat(dbt): Remove dependencies to clean offer criterion model

---

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_suivi_dms_adage.sql
orchestration/dags/data_gcp_dbt/models/analytics/history/bookable_venue_history.sql
orchestration/dags/data_gcp_dbt/models/analytics/offer_moderation.sql
orchestration/dags/data_gcp_dbt/models/clean/reimbursement_collective.sql
orchestration/dags/data_gcp_dbt/models/export/backend/exp_backend__adage_home_playlist_local_offerers.sql
orchestration/dags/data_gcp_dbt/models/export/backend/exp_backend__adage_home_playlist_new_template_offers.sql
orchestration/dags/data_gcp_dbt/models/export/backend/exp_backend__adage_home_playlist_new_venues.sql
orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__offer_metadata.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_daily_user_video_conversion.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_daily_user_video_module.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_video_event.sql

MEP v321.1.0

---

orchestration/dags/dependencies/sendinblue/sql/raw/sendinblue_transactional.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(HF) fix(brevo): fix transactional raw query

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__offerer.md
orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__offerer.sql
orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__offerer.yml
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__offerer.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA-3610) feat(analytics): Add dms adage submission date to offerer

---

jobs/ml_jobs/embeddings/utils/__init__.py
jobs/ml_jobs/embeddings/utils/file_handler.py

…
handle None URLs and improve image loading error handling
* This PR fixes the bug
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) refactor (firebase): update source field **(space …

(BSR) fix(embedding): handle None URLs and improve image loading error handling

---

jobs/ml_jobs/clusterisation/cluster/generate.py

Added two logger.info in clusterisation code to see if clusteres were exported successfully to bigquery.
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :x: (DE-124) refactor …

(BSR) refactor(logs): added logs to see if clusters were exported successfully to BigQuery

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__offer.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/ml/column__artist.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/ml/column__clustering.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/ml/column__recommendation.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/machine_learning/recommendation/description__ml_reco__recommendable_item.md
orchestration/dags/data_gcp_dbt/models/machine_learning/compliance/_schema/ml_compliance__training_data_offer.yml
orchestration/dags/data_gcp_dbt/models/machine_learning/linkage/_schema/ml_linkage__artist.yml
orchestration/dags/data_gcp_dbt/models/machine_learning/linkage/_schema/ml_linkage__artist_name_to_link.yml
orchestration/dags/data_gcp_dbt/models/machine_learning/linkage/_schema/ml_linkage__product_artist_link.yml
orchestration/dags/data_gcp_dbt/models/machine_learning/offer_categorization/_schema/ml_offer_categorization__training_data_offer.yml
orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/_schema/ml_reco__recommendable_item.yml
orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/_schema/ml_reco__training_data_click.yml

* Add sensible ML data
* dbt tests
* elementary volume anomaly tests
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(DE-909) test(ml): Add dbt and elementary tests on sensible ML data

---

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__offer_ean.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(HF) fix(isbn): fix coalsece for isbn values

---

jobs/ml_jobs/clusterisation/cluster/generate.py
jobs/ml_jobs/embeddings/utils/__init__.py
jobs/ml_jobs/embeddings/utils/file_handler.py
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__offer.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/ml/column__artist.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/ml/column__clustering.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/ml/column__recommendation.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/machine_learning/recommendation/description__ml_reco__recommendable_item.md
orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__offer_ean.sql
orchestration/dags/data_gcp_dbt/models/machine_learning/compliance/_schema/ml_compliance__training_data_offer.yml
orchestration/dags/data_gcp_dbt/models/machine_learning/linkage/_schema/ml_linkage__artist.yml
orchestration/dags/data_gcp_dbt/models/machine_learning/linkage/_schema/ml_linkage__artist_name_to_link.yml
orchestration/dags/data_gcp_dbt/models/machine_learning/linkage/_schema/ml_linkage__product_artist_link.yml
orchestration/dags/data_gcp_dbt/models/machine_learning/offer_categorization/_schema/ml_offer_categorization__training_data_offer.yml
orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/_schema/ml_reco__recommendable_item.yml
orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/_schema/ml_reco__training_data_click.yml

MEP v322.1.0

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/machine_learning/recommendation/description__ml_reco__training_data_favorite.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/machine_learning/recommendation/description__ml_reco__training_data_item_feature.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/machine_learning/recommendation/description__ml_reco__training_data_user_feature.md

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(BSR) docs(dbt): Fix typo

---

jobs/ml_jobs/artist_linkage/extract_from_wikidata.py
jobs/ml_jobs/artist_linkage/get_wikimedia_commons_license.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(DE-907) feat(artist): Remove image without adequate license

---

.github/workflows/on_pr_check_hour.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(BSR) ci(protection): restrict push protection schedule to master only

---

.github/workflows/on_pr_check_hour.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(BSR) ci(protection): convert action schedule timezone

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/brevo/column__brevo.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/brevo/description__mrt_brevo_retention_pro.md
orchestration/dags/data_gcp_dbt/models/mart/brevo/_schema/mrt_brevo__retention_pro.yml
orchestration/dags/data_gcp_dbt/models/mart/brevo/mrt_brevo__retention_pro.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA-3629) feat(analytics): Add brevo pro retention table

---

orchestration/dags/dependencies/qualtrics/sql/analytics/enriched_qualtrics_pro.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(BSR) fix(qualtrics): switch venue table dataset

---

orchestration/dags/data_gcp_dbt/macros/database_utils/create_schema_dev.sql
orchestration/dags/data_gcp_dbt/macros/database_utils/generate_schema_name.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(BSR) feat(dbt): fix edge case invalid user name

---

orchestration/dags/data_gcp_dbt/macros/database_utils/create_schema_dev.sql
orchestration/dags/data_gcp_dbt/macros/database_utils/generate_schema_name.sql

Reverts pass-culture/data-gcp#3618

Revert "(BSR) feat(dbt): fix edge case invalid user name"

---

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__offer_ean.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_event.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_event_flattened.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA-3911) feat(analytics): Refacto pro_event

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__collective_offer.md
orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__collective_offer.sql
orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__collective_offer.sql
orchestration/dags/dependencies/applicative_database/sql/raw/parallel/collective_offer.sql
orchestration/dags/dependencies/applicative_database/sql/raw/parallel/collective_offer_template.sql

* This PR adds collective_offer_rejection_reason for both bookable and template collective offers in all related models (except for mrt_global_collective_offer, where rejected offers are excluded)
* Tag a reviewer if necessacy  @lartigaud-pass 
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
* topic within …

(DA-3922) feat(dbt): Add rejection reason to collective offer models

---

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_event.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_event_flattened.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(BSR) feat(proevent): modification pro event

---

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_reimbursement_data.sql
orchestration/dags/data_gcp_dbt/models/analytics/offer_moderation.sql
orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__stock.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(BSR) refactor(clean): remove dependencies stock

---

orchestration/k8s-airflow/k8s-worker-requirements.txt

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(BSR) Add flask-openid for sso support

---

orchestration/dags/data_gcp_dbt/models/analytics/diversification/diversification_raw.sql
orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_partner_retention_data.sql
orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_reimbursement_data.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(BSR) refactor(clean): remove dependencies favorites, user & deposit

---

orchestration/dags/data_gcp_dbt/models/analytics/offer_moderation.sql
orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__offer.sql
orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__collective_offer.sql

* This PR updates pc pro url in models to use the "connect as" feature available in internal backoffice
* Tag a reviewer if necessacy  @mvey-pass 
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* :white_check_mark: (DE-124) …

(DA-3866) feat(analytics): Update pc pro url link to redirect to backoffice

---

orchestration/dags/data_gcp_dbt/models/intermediate/api_gouv/dms/int_api_gouv__dms_jeune.sql
orchestration/dags/data_gcp_dbt/models/intermediate/api_gouv/dms/int_api_gouv__dms_pro.sql
orchestration/dags/data_gcp_dbt/models/sources.yml

- add source table for dms in sources.yml
- creation of dms int tables (jeune + pro)
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* …

(DE-958) feat(dbt): Migrate dms from clean to dbt

---

orchestration/dags/data_gcp_dbt/models/intermediate/pcapi/int_pcapi__backoffice_log.sql
orchestration/dags/data_gcp_dbt/models/intermediate/pcapi/int_pcapi__log.sql

* This PR adds HTTP request backoffice logs to the corresponding model
* Tag a reviewer if necessacy  @mvey-pass 
* [x ] I have performed a self-review of my code
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples:
* …

(DA-3821) feat(dbt): Add new logs to int_pcapi__backoffice_log

---

jobs/etl_jobs/external/brevo/brevo_newsletters.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(HF) fix(brevo): change audience_size to be delivered

---

orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/ml_reco__user_statistics.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(BSR) refactor(DS): Remove internal user in training_data_click

---

orchestration/k8s-airflow/k8s-worker-requirements.in
orchestration/k8s-airflow/k8s-worker-requirements.txt

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DE) build(airflow): add flask-oidc requirement for login

---

.github/workflows/on_pr_check_hour.yml
orchestration/dags/data_gcp_dbt/dbt_project.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(DE-976) test(dbt): Set store_failures to false to reduce BQ costs on tests

---

.github/workflows/on_pr_check_hour.yml
.github/workflows/on_schedule_rerun_check_hour.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(DE) feat(ci): activate branch protection #3699

---

orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/ml_reco__training_data_user_feature.sql
orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/ml_reco__user_statistics.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
examples: …

(BSR) fix(query): Fix user theoritical credit null

---

requirements.in
requirements.txt

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(BSR) refactor(packages): Update virtualenv deps

---

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_consultation.sql
orchestration/dags/data_gcp_dbt/models/mart/native/_schema/mrt_native__consultation.yml
orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__consultation.sql

* This PR adds traffic_source column to native_consultation model, in order to identify consultations generated from transactional marketing campaigns
* Tag a reviewer if necessacy  @mvey-pass 
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt
* comment: tell us your …

(DA-3970) feat(dbt): Add traffic source to native consultation

---

.github/PULL_REQUEST_TEMPLATE/DA_ticket_template.md
.github/PULL_REQUEST_TEMPLATE/DE_ticket_template.md
.github/PULL_REQUEST_TEMPLATE/DS_ticket_template.md
.github/PULL_REQUEST_TEMPLATE/Hotfix_template.md
.github/pull_request_template.md
.github/workflows/on_pr__title_checker.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(BSR) fix(ci): Fix typo to align with precommitlint

---

orchestration/dags/dependencies/qualtrics/sql/analytics/enriched_qualtrics_pro.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(BSR) fix(qualtrics): Fix enriched_qualtrics_pro query

---

Makefile
README.md

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) docs(install): Update install doc lucille

---

.sqlfluff

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DE) feat(sqlfluff): exclude the structure.using rule

---

jobs/etl_jobs/internal/export_clickhouse/schema/intermediate/native_event.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) feat(clickhouse): compress native_event

---

.github/PULL_REQUEST_TEMPLATE/DA_ticket_template.md
.github/PULL_REQUEST_TEMPLATE/DE_ticket_template.md
.github/PULL_REQUEST_TEMPLATE/DS_ticket_template.md

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) docs(ci): remove doc conditions in Notion

---

orchestration/dags/data_gcp_dbt/models/intermediate/global/_schema/int_global__booking.yaml
orchestration/dags/data_gcp_dbt/models/intermediate/global/_schema/int_global_booking.yaml
orchestration/dags/data_gcp_dbt/models/intermediate/global/properties.yml
orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__booking.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(BSR) refactor(cardinality): set cardinality test on int_global_booking

---

jobs/etl_jobs/internal/import_api_referentials/requirements.in
jobs/etl_jobs/internal/import_api_referentials/requirements.txt

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(BSR) fix(apireferentials): Add poetry export plugin in import_api_referentials

---

jobs/etl_jobs/external/brevo/main.py
orchestration/dags/dependencies/sendinblue/sql/analytics/sendinblue_newsletters_performance.sql
orchestration/dags/jobs/import/import_sendinblue.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(DE-986) feat(brevo): separate pro and native api keys

---

orchestration/dags/common/operators/gce.py
orchestration/dags/jobs/administration/metabase_dbt.py
orchestration/dags/launch_vm.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) refactor(install): clean non uv legacy, add base dir option to launch_vm

---

jobs/etl_jobs/external/addresses/scripts/fetch_user_location.py
jobs/etl_jobs/external/brevo/main.py
orchestration/dags/common/operators/gce.py
orchestration/dags/dependencies/sendinblue/sql/analytics/sendinblue_newsletters_performance.sql
orchestration/dags/jobs/administration/metabase_dbt.py
orchestration/dags/jobs/import/import_sendinblue.py
orchestration/dags/launch_vm.py

MEP v326.1.0

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__venue.md
orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__venue.sql
orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__venue.sql
orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__venue.yml
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__venue.sql
orchestration/dags/dependencies/applicative_database/sql/raw/parallel/venue.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …

(DA-3966) feat(dbt): Add venue_adage_inscription_date to global_venue

---

orchestration/dags/data_gcp_dbt/dbt_project.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(BSR) fix(cardinality): inverse ratio

---

orchestration/dags/data_gcp_dbt/macros/database_utils/create_schema_dev.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) lint(fix): create_schema_dev dbt macro

---

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_reimbursement_data.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DA-3742) feat(Analytics): Update enriched_reimbursement_data

---

jobs/etl_jobs/external/addresses/scripts/fetch_user_location.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(BSR) refactor(addresses): reduce users to beneficiary

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/appsflyer/column__appsflyer.md
orchestration/dags/data_gcp_dbt/models/intermediate/appsflyer/_schema/int_appsflyer__daily_install_attribution.yml
orchestration/dags/data_gcp_dbt/models/intermediate/appsflyer/_schema/int_appsflyer__daily_install_cost.yml
orchestration/dags/data_gcp_dbt/models/intermediate/appsflyer/int_appsflyer__daily_install_attribution.sql
orchestration/dags/data_gcp_dbt/models/intermediate/appsflyer/int_appsflyer__daily_install_cost.sql
orchestration/dags/data_gcp_dbt/models/mart/marketing/mrt_marketing__daily_install_acquisition_campaign.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DA-3872) feat(Analytics): Fix acquisition_campaign model

---

.github/workflows/on_cd__workflow.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE) ci(build): add image build to workflow dispatch

---

orchestration/dags/data_gcp_dbt/models/intermediate/appsflyer/int_appsflyer__daily_install_cost.sql
orchestration/dags/data_gcp_dbt/models/sources.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(DA) fix(dbt): put appsflyer_import installs table in sources and referenced table from source in daily_install_cost model

---

.github/workflows/on_cd__workflow.yml
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/appsflyer/column__appsflyer.md
orchestration/dags/data_gcp_dbt/models/intermediate/appsflyer/_schema/int_appsflyer__daily_install_attribution.yml
orchestration/dags/data_gcp_dbt/models/intermediate/appsflyer/_schema/int_appsflyer__daily_install_cost.yml
orchestration/dags/data_gcp_dbt/models/intermediate/appsflyer/int_appsflyer__daily_install_attribution.sql
orchestration/dags/data_gcp_dbt/models/intermediate/appsflyer/int_appsflyer__daily_install_cost.sql
orchestration/dags/data_gcp_dbt/models/mart/marketing/mrt_marketing__daily_install_acquisition_campaign.sql
orchestration/dags/data_gcp_dbt/models/sources.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

MEP v 327.0.0

---

jobs/etl_jobs/external/adage/main.py
jobs/etl_jobs/external/adage/scripts/import_adage.py
jobs/etl_jobs/external/adage/scripts/utils.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(DS) refactor(adage): refactored main of import adage for robustness and clarity

---

orchestration/dags/jobs/administration/bigquery_alerts.py
orchestration/dags/jobs/administration/metabase_dbt.py
orchestration/dags/jobs/administration/metabase_governance.py
orchestration/dags/jobs/administration/metabase_transition.py
orchestration/dags/jobs/export/export_clickhouse.py
orchestration/dags/jobs/export/export_posthog.py
orchestration/dags/jobs/import/import_gsheet.py
orchestration/dags/jobs/import/import_qualtrics.py
orchestration/dags/jobs/import/import_sendinblue.py
orchestration/dags/jobs/import/import_sendinblue_historical.py
orchestration/dags/jobs/import/import_siren.py
orchestration/dags/jobs/import/import_social_media.py
orchestration/dags/jobs/import/import_zendesk.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(DE-939) feat(mob): add labels on dags that trigger a vm 2/2

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/ml/column__embedding.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/ml/column__mlflow.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/ml/column__two_tower.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/machine_learning/feature/description__ml_feat__two_tower_last_item_embedding.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/machine_learning/feature/description__ml_feat__two_tower_last_user_embedding.md
orchestration/dags/data_gcp_dbt/models/machine_learning/feature/_schema/ml_feat__two_tower_last_item_embedding.yml
orchestration/dags/data_gcp_dbt/models/machine_learning/feature/_schema/ml_feat__two_tower_last_user_embedding.yml
orchestration/dags/data_gcp_dbt/models/machine_learning/feature/ml_feat__two_tower_last_item_embedding.sql
orchestration/dags/data_gcp_dbt/models/machine_learning/feature/ml_feat__two_tower_last_user_embedding.sql

Added description for the views `ml_feat__two_tower_last_item_embedding` and `ml_feat__two_tower_last_user_embedding` as well as description and data_type for their columns.
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples:
* :white_check_mark: (DE-124) …

(DE) docs(historization): Document last two tower embedding views in dbt

---

orchestration/dags/data_gcp_dbt/models/analytics/enriched/user_penetration.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-1027) feat(dbt): update user_penetration legacy

---

orchestration/dags/data_gcp_dbt/models/analytics/enriched/user_penetration.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) fix(sql): remove trailing semicolon

---

orchestration/dags/data_gcp_dbt/models/analytics/enriched/user_penetration.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) fix(sql): unquote date part

---

jobs/etl_jobs/internal/export_clickhouse/refresh.py
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/daily_aggregated_offer_event.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-999) feat(clickhouse): add date filter for ehp offer_event

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/intermediate/firebase/description__int_firebase__pro_experiment.md
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_experiment.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DA-3748) feat(dbt): Create int_firebase__pro_experiment and doc

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/social_network/column__instagram.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/social_network/column__publication.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/social_network/column__tiktok.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/intermediate/instagram/description__int_instagram__publication_detail.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/intermediate/tiktok/description__int_tiktok__publication_detail.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/marketing/description__mrt_marketing__social_network_publication.md
orchestration/dags/data_gcp_dbt/models/intermediate/instagram/int_instagram__publication_detail.sql
orchestration/dags/data_gcp_dbt/models/intermediate/instagram/int_instagram_publication_detail.yml
orchestration/dags/data_gcp_dbt/models/intermediate/tiktok/int_tiktok__publication_detail.sql
orchestration/dags/data_gcp_dbt/models/intermediate/tiktok/int_tiktok__publication_detail.yml
orchestration/dags/data_gcp_dbt/models/mart/marketing/_schema/mrt_marketing__social_network_publication.yml
orchestration/dags/data_gcp_dbt/models/mart/marketing/mrt_marketing__social_network_publication.sql
orchestration/dags/data_gcp_dbt/models/sources.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DA-3956) feat(Analytics): Add social network models

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/tracking/column__pro_event.md
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_event.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_event_flattened.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_visit.sql
orchestration/dags/data_gcp_dbt/models/mart/pro/_schema/mrt_pro__event.yml
orchestration/dags/data_gcp_dbt/models/mart/pro/mrt_pro__event.sql

- Ajout d'un champs "image_creation_stage" à firebase_pro_event (paramètre d'événement)
- Modification de firebase_pro_visits (CASE WHEN pour identifier vue page stat)
- Modification du "page_name" de int_firebase_pro_event -> les devs vont changer "- pass Culture Pro" en "- Espace partenaires pass Culture" ce qui va casser tous nos DB, du coup je change direct ici

(DA-3757) feat(dbt): Update firebase_pro_event and visit (fields)

---

jobs/etl_jobs/internal/export_clickhouse/schema/intermediate/booking.sql
jobs/etl_jobs/internal/export_clickhouse/schema/intermediate/collective_booking.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(DE-998) feat(clickhouse): generalize compression to intermediate tables

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/brevo/column__brevo.md
orchestration/dags/data_gcp_dbt/models/intermediate/brevo/int_brevo__transactional_pro.sql
orchestration/dags/data_gcp_dbt/models/intermediate/brevo/int_brevo__transactional_pro.yml
orchestration/dags/data_gcp_dbt/models/mart/brevo/_schema/mrt_brevo__transactional_pro.yml
orchestration/dags/data_gcp_dbt/models/mart/brevo/mrt_brevo__transactional_pro.sql
orchestration/dags/dependencies/sendinblue/sql/raw/sendinblue_transactional.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DA-3773) feat(dbt): update sendinblue transactionnal

---

orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__offer.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-931) dbt(tests): switch global offer unicity to critical

---

orchestration/dags/common/dbt/utils.py
orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__offer.yml
orchestration/dags/data_gcp_dbt/scripts/dbt_test_model.sh

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-931) dbt(tests): critical tests only in dbt run dag

---

orchestration/dags/data_gcp_dbt/models/mart/marketing/mrt_marketing__social_network_publication.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DA-3956) feat(Analytics): Fix social network model config

---

orchestration/dags/jobs/crons.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(HF) fix(cron): change clickhouse export cron

---

orchestration/dags/data_gcp_dbt/models/mart/marketing/mrt_marketing__social_network_publication.sql
orchestration/dags/jobs/crons.py

MEP 328.3.0

---

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_experiment.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DA-1127) feat(dbt): Add AB test offres vitrines to pro_experiment

---

orchestration/dags/jobs/export/export_qualtrics_data.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(BSR) dbt(qualtrics): improve code

---

jobs/ml_jobs/algo_training/two_towers_model/utils/metrics.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(DS) refactor(precision): correct precision function (divide by len(predicted) instead of len(actual))

---

orchestration/dags/data_gcp_dbt/models/intermediate/history/int_history__bookable_offer.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(DE-1222) refactor(history): migrate bookable_offer_history

---

orchestration/dags/data_gcp_dbt/models/analytics/history/bookable_venue_history.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE) feat(dbt): fix sync_all_columns on bookable_venue_history

---

orchestration/dags/data_gcp_dbt/.gitignore
orchestration/dags/jobs/dbt/dbt_encrypted_export.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) fix(export): typo module path & git ignore

---

orchestration/dags/data_gcp_dbt/scripts/elementary_send_report.sh

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE) test(alert): remove html attachement from elementary report

---

jobs/etl_jobs/internal/bigquery_archive_partition/archive.py
jobs/etl_jobs/internal/bigquery_archive_partition/main.py
orchestration/dags/jobs/administration/bigquery_archive_partition.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-1138) fix(archive): fix json parsing in archive partitions dag

---

orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__booking.yml
orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__offer.yml
orchestration/dags/data_gcp_dbt/tests/generic/is_valid_booking_intermediary_amout.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-1150) test(dbt): critical tests v1

---

jobs/etl_jobs/external/zendesk/extract.py
jobs/etl_jobs/external/zendesk/main.py
jobs/etl_jobs/internal/bigquery_archive_partition/archive.py
jobs/etl_jobs/internal/bigquery_archive_partition/main.py
orchestration/dags/common/alerts.py
orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__booking.yml
orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__offer.yml
orchestration/dags/data_gcp_dbt/scripts/dbt_clean_tmp_folders.sh
orchestration/dags/data_gcp_dbt/scripts/elementary_send_report.sh
orchestration/dags/data_gcp_dbt/scripts/helpers.sh
orchestration/dags/data_gcp_dbt/tests/generic/is_valid_booking_intermediary_amout.sql
orchestration/dags/jobs/administration/bigquery_archive_partition.py
orchestration/dags/jobs/dbt/dbt_dag_run.py
orchestration/dags/jobs/import/import_zendesk.py

MEP v229.0.0

---

jobs/etl_jobs/external/metabase-archiving/archiving.py
jobs/etl_jobs/external/metabase-archiving/main.py
jobs/etl_jobs/external/metabase-archiving/utils.py
orchestration/dags/data_gcp_dbt/models/intermediate/metabase/int_metabase__activity.sql
orchestration/dags/data_gcp_dbt/models/intermediate/metabase/int_metabase__aggregated_card_activity.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-1247) refactor(metabase): update archiving script

---

orchestration/dags/jobs/crons.py
orchestration/dags/jobs/import/import_api_referentials.py
orchestration/dags/jobs/import/import_appsflyer.py
orchestration/dags/jobs/import/import_contentful.py
orchestration/dags/jobs/import/import_dms_subscriptions.py
orchestration/dags/jobs/import/import_downloads.py
orchestration/dags/jobs/import/import_qpi.py
orchestration/dags/jobs/import/import_social_media.py
orchestration/dags/jobs/import/import_zendesk.py
orchestration/dags/jobs/ml/algo_default_deployment.py
orchestration/dags/jobs/ml/embedding_clusterisation_item.py
orchestration/dags/jobs/ml/embedding_reduction_item.py
orchestration/dags/jobs/ml/retrieval_vector_build.py

Update dag schedule for smooth operations and avoid too much concurency on composer
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples:
* :x: (DE-124) refactor …

(DE-939) fix(schedule): update cron timings for various DAGs

---

jobs/etl_jobs/internal/bigquery_alerts/utils.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(DE-1268) feat(alert): add datasets to scan in bq alert

---

jobs/ml_jobs/ranking_endpoint/api-requirements.in
jobs/ml_jobs/ranking_endpoint/api-requirements.txt
jobs/ml_jobs/ranking_endpoint/requirements.in
jobs/ml_jobs/ranking_endpoint/requirements.txt

- Bumped LGBM in requierments.in and api-requierments.in to version 4.6.0
- compiled with uv to create .txt files compatible with linux
- tested new code in composer **dev** and dag was successful.
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* …

(BSR) fix(dependabot): upgraded lightgbm to 4.6.0 to fix remote execution alert

---

orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/ml_reco__recommendable_offer.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DS) fix(geoloc): Fix is geolocated is false

---

orchestration/dags/common/alerts.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE) feat(alert): add owner tag in slack fail alert

---

jobs/ml_jobs/algo_training/two_towers_model/models/match_model.py

*  removed normalize=True from Dot layer  in match model to not renormalize embeddings 
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples:
* :x: (DE-124) refactor (firebase): update …

(DS) fix(normalize): remove normalization from dot product

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/tracking/column__pro_event.md
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_event.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_event_flattened.sql
orchestration/dags/data_gcp_dbt/models/mart/pro/_schema/mrt_pro__event.yml
orchestration/dags/data_gcp_dbt/models/mart/pro/mrt_pro__event.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DA-3858) feat(dbt): Add an event paramater in pro event for headline offer

---

jobs/ml_jobs/retrieval_vector/requirements.in
jobs/ml_jobs/retrieval_vector/requirements.txt

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(BSR) fix(retrieval): Add async-timeout package in retrieval vector

---

orchestration/dags/data_gcp_dbt/models/intermediate/metric/diversity/int_metric__diversity_daily_booking.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(HF) fix(dbt): fix diversity score pipeline

---

orchestration/dags/dependencies/applicative_database/sql/raw/parallel/finance_event.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DA-1226) feat(dbt): Add bookingFinanceIncidentId to finance event

---

jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_venue_collective_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_venue_individual_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_venue_revenue.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-1283) fix(clickhouse): fix yearly expected revenue

---

jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_venue_collective_revenue.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(HF) fix(clickhouse): remove ending comma

---

orchestration/dags/jobs/ml/artist_linkage.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) feat(artist): Add long_task tag for artist_linkage

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__special_event.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column_special_event.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/global/description__mrt_global__special_event.md
orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__special_event.sql
orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__special_event.yml
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__special_event.sql
orchestration/dags/data_gcp_dbt/models/raw/applicative/raw_applicative__special_event.sql
orchestration/dags/data_gcp_dbt/models/raw/applicative/raw_applicative__special_event_response.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-1280) feat(dbt): Import special event models

---

jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_venue_collective_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_venue_individual_revenue.sql
jobs/etl_jobs/internal/export_clickhouse/schema/analytics/yearly_aggregated_venue_revenue.sql
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__special_event.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/global/description__mrt_global__special_event.md
orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__special_event.sql
orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__special_event.yml
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__special_event.sql
orchestration/dags/data_gcp_dbt/models/raw/applicative/raw_applicative__special_event.sql
orchestration/dags/data_gcp_dbt/models/raw/applicative/raw_applicative__special_event_response.sql
orchestration/dags/dependencies/applicative_database/sql/raw/parallel/finance_event.sql
orchestration/dags/jobs/ml/artist_linkage.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

MEP v332.0.0

---

jobs/ml_jobs/algo_training/two_towers_model/README.md

* Added two tower training logic
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples:
* :x: (DE-124) refactor (firebase): update source field …

(BSR) docs(TT): updated readme for two tower

---

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_daily_user_home_module.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_home_offer_displayed.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DS) refactor(native): Add user_id and sessions_id in native_home_offer_displayed

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/tracking/column__collective_adage_log.md
orchestration/dags/data_gcp_dbt/models/intermediate/pcapi/int_pcapi__adage_log.sql
orchestration/dags/data_gcp_dbt/models/intermediate/pcapi/int_pcapi__log.sql
orchestration/dags/data_gcp_dbt/models/mart/collective/_schema/mrt_collective__adage_log.yml
orchestration/dags/data_gcp_dbt/models/mart/collective/mrt_collective__adage_log.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DA-1276) feat(dbt): add geoloc_radius_filter to collective_adage_logs

---

orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__booking.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(HF) fix(test): add condition to exclude inactive user

---

orchestration/dags/common/hooks/image.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(BSR) feat(DS): Add gcc as default C compiler

---

orchestration/dags/data_gcp_dbt/models/intermediate/history/int_history__bookable_venue.sql
orchestration/dags/data_gcp_dbt/snapshots/intermediate/global/snasphot_intermediate__bookable_collective_offer.sql
orchestration/dags/data_gcp_dbt/snapshots/intermediate/global/snasphot_intermediate__bookable_offer.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(HF) fix(snapshot): fix invalidate hard delete

---

orchestration/airflow/Dockerfile

* This PR adds CURL_CA_BUNDLE to dockerfile to fix ssl error when launching a VM on gcloud having netskope proxy.
* The encontered error when starting gce operator was : 
`ERROR - Failed to execute job 11 for task gce_start_task ([SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol`
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* …

(DE) fix(netskope): added CURL_CA_BUNDLE to fix SSL error while launching VMs

---

orchestration/airflow/Dockerfile

- HTTPLIB2_CA_CERTS is required when doing http requests using HTTPLIB2 not the requests lib.
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples:
* :x: (DE-124) refactor (firebase): …

(DS) fix(netskope): added ENV HTTPLIB2_CA_CERTS to solve SSL error 

---

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__collective_stock.sql
orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__collective_offer.sql
orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__collective_booking.yml
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__collective_booking.sql
orchestration/dags/data_gcp_dbt/snapshots/applicative/snapshot__applicative_collective_stock.sql
orchestration/dags/dependencies/applicative_database/sql/clean/history/collective_stock_history.sql
orchestration/dags/dependencies/applicative_database/sql/raw/parallel/collective_stock.sql
orchestration/tests/data_analytics/config.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-3904) feat(dbt): remove stock_id columns on collective stock tables

---

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__collective_stock.sql
orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__collective_offer.sql
orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__collective_booking.yml
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__collective_booking.sql
orchestration/dags/data_gcp_dbt/snapshots/applicative/snapshot__applicative_collective_stock.sql
orchestration/dags/dependencies/applicative_database/sql/clean/history/collective_stock_history.sql
orchestration/dags/dependencies/applicative_database/sql/raw/parallel/collective_stock.sql
orchestration/tests/data_analytics/config.py

…es (#3904)
* remove stock_id columns on collective stock tables
* fix collective offer table
* fix'
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* …

MEP 332.0.1

---

orchestration/dags/data_gcp_dbt/snapshots/applicative/snapshot__applicative_collective_offer.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-3908) feat(dbt): fix snapshot collective offer

---

orchestration/dags/data_gcp_dbt/macros/database_utils/custom_snapshot_config.sql
orchestration/dags/data_gcp_dbt/snapshots/intermediate/global/snasphot_intermediate__bookable_collective_offer.sql
orchestration/dags/data_gcp_dbt/snapshots/intermediate/global/snasphot_intermediate__bookable_offer.sql
orchestration/dags/data_gcp_dbt/snapshots/raw_applicative/snapshot_raw__offer.sql
orchestration/dags/data_gcp_dbt/snapshots/raw_applicative/snapshot_raw__stock.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-1354) fix(dbt): typo invalidate hard delete

---

orchestration/dags/common/alerts.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE) refactor(callback): fetch instance name in task context

---

jobs/ml_jobs/algo_training/two_towers_model/evaluate.py
jobs/ml_jobs/algo_training/two_towers_model/utils/evaluate.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DS) feat(metrics): added a plot showing metrics evolution with k values

---

jobs/etl_jobs/internal/export_clickhouse/schema/tmp/intermediate_collective_booking.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE) fix(clickhouse): reorder columns collective booking

---

orchestration/dags/data_gcp_dbt/models/machine_learning/feature/ml_feat__offer_feature.sql
orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/ml_reco__home_interaction.sql
orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/ml_reco__ranking_training_data.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DS) fix(ranking query): Fix offer feature query

---

orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__booking.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-3916) feat(dbt): remove non relevant test

---

orchestration/dags/jobs/crons.py
orchestration/dags/jobs/ml/artist_linkage.py
orchestration/dags/jobs/ml/embedding_reduction_item.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(BSR) refactor(dag schedule): Move weekly dags after dbt run

---

orchestration/dags/jobs/ml/retrieval_vector_build.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(DS) fix(schedule): changed retrieval vector build dag schedule to start at 8am UTC

---

.github/workflows/reusable_dbt_workflow.yml

…tion
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
* comment: …

(DE) ci(docs): remove failing --no-compile flag from generate docs action

---

orchestration/dags/jobs/ml/algo_training_two_towers.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DS) feat(historization): added parameter not to upload embeddings to BQ

---

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__collective_offer.sql
orchestration/dags/dependencies/applicative_database/sql/raw/parallel/collective_offer_template.sql

…emplate
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
* comment: …

(DE) refactor(applicative): remove providerId from collective offer template

---

.github/workflows/on_cd__workflow.yml
.github/workflows/on_ci__workflow.yml
.github/workflows/scripts/find_tests.sh

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(BSR) fix(CI): Fix on cd workflow

---

jobs/etl_jobs/internal/import_api_referentials/README.md
jobs/etl_jobs/internal/import_api_referentials/data/subcategories_v2_20250327.csv
jobs/etl_jobs/internal/import_api_referentials/main.py
orchestration/dags/jobs/import/import_api_referentials.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(DE-1443) fix(api ref): Add subcategories merge

---

jobs/ml_jobs/algo_training/commons/constants.py
jobs/ml_jobs/algo_training/two_towers_model/evaluate.py
jobs/ml_jobs/algo_training/two_towers_model/utils/evaluate.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(DS) feat(metrics): added scann index to compute metrics

---

orchestration/dags/common/alerts.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE) fix(hook): render jinja template in stop_vm hook

---

jobs/ml_jobs/algo_training/two_towers_model/evaluate.py
jobs/ml_jobs/algo_training/two_towers_model/utils/evaluate.py

…for baselines
* This PR removes novelty from previous metrics plots to a different plot 
* new plots for each basline
* a separate plot to compare recall between baseline models and two tower model
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
* …

(DS) feat(metrics): enhanced metrics plots readibility and added baseline metrics to plots

---

orchestration/dags/data_gcp_dbt/models/intermediate/raw/int_raw__offer.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(HF) fix(filter): fix filter int_raw_offer

---

jobs/ml_jobs/algo_training/two_towers_model/evaluate.py
jobs/ml_jobs/algo_training/two_towers_model/utils/baseline_prediction.py
jobs/ml_jobs/algo_training/two_towers_model/utils/evaluate.py
jobs/ml_jobs/algo_training/two_towers_model/utils/plotting.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(DE-1442) feat(TT dummy): Add svd as dummy model

---

.github/workflows/on_dispatch__build_image.yml
orchestration/k8s-airflow/Dockerfile.k8s-worker

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE) build(elementary): fix elementary executable path & workflow dispatch

---

jobs/etl_jobs/internal/import_api_referentials/data/music_types_deprecated_20250401.csv
jobs/etl_jobs/internal/import_api_referentials/main.py
orchestration/dags/jobs/import/import_api_referentials.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-1132) feat(referentials): fix import offer_types

---

jobs/etl_jobs/internal/bigquery_archive_partition/main.py
orchestration/dags/jobs/crons.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(HF) fix(archive): reduce limit and increase schedule

---

orchestration/dags/data_gcp_dbt/models/clean/applicative/national_program_offer_link_history.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/national_program_offer_template_link_history.sql
orchestration/dags/data_gcp_dbt/models/sources.yml
orchestration/dags/dependencies/applicative_database/sql/raw/parallel/national_program_offer_link_history.sql
orchestration/dags/dependencies/applicative_database/sql/raw/parallel/national_program_offer_template_link_history.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) feat(import): remove import national program data

---

orchestration/dags/data_gcp_dbt/snapshots/raw_applicative/snapshot_raw__offer.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) fix(snapshot): dependency forcing

---

.pre-commit-config.yaml
Makefile

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(HF) fix(linter): remove snapshots folder

---

.github/workflows/on_cd__workflow.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE) ci(airflow): deploy airflow on k8s stg env

---

orchestration/dags/data_gcp_dbt/packages.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) dbt(packages): replace deprecated and update other packages

---

orchestration/dags/jobs/administration/bigquery_archive_partition.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(HF) refactor(archiving): remove past offer context archiving

---

orchestration/dags/data_gcp_dbt/models/intermediate/geolocation/int_geo__institution_location.sql
orchestration/dags/data_gcp_dbt/models/intermediate/seed/int_seed__institution_metadata.sql
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__educational_institution.sql
orchestration/dags/data_gcp_dbt/models/sources.yml
orchestration/dags/dependencies/applicative_database/sql/raw/parallel/educational_institution.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-1415) feat(dbt): update institution location source

---

.github/workflows/on_cd__workflow.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) ci(fix): remove airflow manual deployement on stg

---

orchestration/dags/data_gcp_dbt/models/clean/applicative/user_pro_flags.sql
orchestration/dags/data_gcp_dbt/scripts/elementary_send_report_k8s.sh

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) chore(cleaning): remove deprecated table user_pro_flags

---

orchestration/dags/dependencies/applicative_database/sql/raw/parallel/user_pro_flags.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) chore(cleaning): remove usr pro flags remove applicative import

---

.github/workflows/on_cd__workflow.yml

…ch on stg
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
* …

(DE) ci(airflow): fix stg deployment & temporaly enable manual dispatch on stg

---

orchestration/dags/jobs/crons.py
orchestration/dags/jobs/ml/algo_default_deployment.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(BSR) fix(schedule): Change default deployment cron from 7 to 9

---

jobs/ml_jobs/ranking_endpoint/deploy_model.py
jobs/ml_jobs/ranking_endpoint/deploy_to_docker_registery.sh
jobs/ml_jobs/retrieval_vector/deploy_model.py
jobs/ml_jobs/retrieval_vector/deploy_semantic.py
jobs/ml_jobs/retrieval_vector/deploy_to_docker_registery.sh

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(DE-1500) fix(registries): Replace container by artifact registry

---

orchestration/dags/jobs/ml/algo_training_offer_compliance_model.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) docs(dag): add missing tag to new dag

---

jobs/etl_jobs/internal/import_api_referentials/main.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(HF) fix(ref): fix env_short_name

---

orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__educational_institution.sql
orchestration/dags/data_gcp_dbt/models/sources.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE) fix(dbt): Add macro institution type

---

orchestration/dags/jobs/import/import_appsflyer.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) feat(appflyer): set dummy task for etl costs in dev/stg

---

orchestration/dags/common/alerts.py
orchestration/dags/common/config.py

… tasks
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
* comment: …

(DE) feat(vm): instance name prefix + disable stop vm hook for simple tasks

---

orchestration/dags/data_gcp_dbt/macros/database_utils/get_custom_alias.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) fix(dbt): fix macro behavior for elementary profile

---

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_event.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_event_flattened.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DA-4045) feat(dbt): Add headline offer parameter to Consultoffer event

---

orchestration/dags/data_gcp_dbt/models/analytics/aggregated_weekly_user_data.sql
orchestration/dags/data_gcp_dbt/models/analytics/firebase/firebase_aggregated_daily_campaign_events.sql
orchestration/dags/data_gcp_dbt/models/analytics/firebase/firebase_aggregated_search_events.sql
orchestration/dags/data_gcp_dbt/models/analytics/firebase_aggregated_similar_offer_events.sql
orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/ml_reco__ranking_endpoint_training.sql
orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_home_module_conversion.sql
orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_venue_map_conversion.sql
orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__outgoing_cohort.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-1279) feat(dbt): Update diversification booking dependancies

---

jobs/ml_jobs/retrieval_vector/utils.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) fix(retrieval): Use fillna to set default values properly

---

jobs/ml_jobs/retrieval_vector/utils.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(BSR) fix(retrieval vector): Fix num_batches computation

---

orchestration/dags/common/dbt/utils.py
orchestration/dags/common/utils.py
orchestration/dags/jobs/dbt/dbt_dag_run.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE) feat(airflow): assign dbt tasks to private pool

---

jobs/ml_jobs/clusterisation/requirements.in
jobs/ml_jobs/clusterisation/requirements.txt
jobs/ml_jobs/embeddings/requirements.in
jobs/ml_jobs/embeddings/requirements.txt
jobs/ml_jobs/item_linkage/requirements.in
jobs/ml_jobs/item_linkage/requirements.txt
jobs/ml_jobs/retrieval_vector/api-requirements.in
jobs/ml_jobs/retrieval_vector/api-requirements.txt
jobs/ml_jobs/retrieval_vector/requirements.in
jobs/ml_jobs/retrieval_vector/requirements.txt

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(DS-1577) chore(package): Update pytorch

---

orchestration/dags/data_gcp_dbt/models/analytics/adage_involved_institution.sql
orchestration/dags/data_gcp_dbt/models/analytics/adage_involved_student.sql
orchestration/dags/data_gcp_dbt/models/analytics/eple_aggregated.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/educational_year.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE) refactor(dbt): remove educational year in clean

---

orchestration/dags/data_gcp_dbt/models/analytics/offer_moderation.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/offerer_tag.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/offerer_tag_category.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/offerer_tag_category_mapping.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/offerer_tag_mapping.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE) refactor(ae): remove offerer_tag clean models

---

jobs/etl_jobs/external/gsheet/gsheet.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DA-3732) feat(dbt): Added gsheet with MASA schools affiliations

---

jobs/etl_jobs/internal/sync_recommendation/jobs/daily_bq_to_sql/export_to_gcs.py
jobs/etl_jobs/internal/sync_recommendation/jobs/daily_bq_to_sql/gcs_to_sql.py
jobs/etl_jobs/internal/sync_recommendation/utils/bq_config.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(BSR) fix(sync BQ CloudSQL): Import proper table to CloudSQL

---

orchestration/dags/jobs/administration/gcp_launch_vm.py
orchestration/dags/jobs/ml/algo_custom_deployment.py

…se doc
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples:
* :white_check_mark: (DE-124) …

(DE) feat(dag): add instance_name param and doc to algo_custom deployment 

---

orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__educational_institution.yml
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__educational_institution.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DA) feat(dbt): add tests on mart_global__educational_institution

---

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__offerer.sql
orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__offerer.yml
orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__venue.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DA-4113) feat(dbt): Add test to global_offerer and global_venue

---

jobs/ml_jobs/retrieval_vector/app/retrieval/client.py
jobs/ml_jobs/retrieval_vector/app/retrieval/constants.py
jobs/ml_jobs/retrieval_vector/app/retrieval/reco_client.py
jobs/ml_jobs/retrieval_vector/tests/conftest.py
jobs/ml_jobs/retrieval_vector/tests/factory/recommendation_test.py
jobs/ml_jobs/retrieval_vector/tests/factory/semantic_offer_test.py
jobs/ml_jobs/retrieval_vector/tests/factory/similar_offer_test.py
jobs/ml_jobs/retrieval_vector/tests/factory/tops_test.py
jobs/ml_jobs/retrieval_vector/tests/retrieval/core/client_test.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(DS-1647) feat(retrieval): Compute dot similarity in retrieval

---

orchestration/dags/data_gcp_dbt/models/mart/alerting/_schema/mrt_alerting__metabase_cost.yml
orchestration/dags/data_gcp_dbt/models/mart/alerting/mrt_alerting__metabase_cost.sql
orchestration/dags/jobs/dbt/dbt_artifacts.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-1636) feat(alert): add alert on Metabase

---

orchestration/dags/data_gcp_dbt/dbt_project.yml
orchestration/dags/data_gcp_dbt/models/intermediate/history/int_history__bookable_venue.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE) dbt(feat): full refresh bookable venue

---

.github/workflows/reusable_build_image.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-1641) refactor(airflow): split images on registry

---

orchestration/dags/jobs/dbt/dbt_artifacts.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(HF) feat(dbt): add recompile job to elementary end

---

orchestration/dags/data_gcp_dbt/models/analytics/eple_aggregated.sql
orchestration/dags/data_gcp_dbt/models/clean/applicative/beneficiary_fraud_check.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) refactor(clean): remove clean beneficiary fraud check

---

automations/create_microservice.py
orchestration/dags/data_gcp_dbt/.env.dbt
orchestration/dags/data_gcp_dbt/scripts/defer_local_run.sh

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) fix(miscellaneous): typo & deprecated variables

---

orchestration/Makefile
orchestration/README.md

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) fix(build): fix makefile & add docs

---

.github/workflows/on_pr_review__gpt.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(BSR) feat(code review): Update review gpt (now renamed shippie)

---

.pre-commit-config.yaml
orchestration/dags/common/hooks/image.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) feat(cloudops): added cloud ops agent to hooks to monitor RAM usage

---

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__offer_item_id.sql
orchestration/dags/data_gcp_dbt/models/sources.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(BSR-1686) refactor(linked offers): Remove unused join and remove linked_offers source

---

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/schema/int_firebase__native_event_flattened.yaml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE) feat(dbt): fix failing test on native_event_flattened

---

orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__offerer.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE) feat(dbt): Remove faling test on siren_data waiting investigation

---

.github/workflows/on_pr_review__gpt.yml
.pre-commit-config.yaml
orchestration/dags/common/hooks/gce.py
orchestration/dags/common/hooks/image.py
orchestration/dags/common/operators/gce.py
orchestration/dags/common/triggers/gce.py
orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__offer_item_id.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/schema/int_firebase__native_event_flattened.yaml
orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__offerer.yml
orchestration/dags/data_gcp_dbt/models/sources.yml
orchestration/dags/dependencies/propilote/sql/tmp/beneficiaires/propilote_tmp_beneficiaires.sql
orchestration/dags/jobs/crons.py
orchestration/dags/jobs/ml/embedding_clusterisation_item.py
orchestration/dags/jobs/ml/embedding_extraction_item.py
orchestration/dags/jobs/ml/embedding_reduction_item.py

MEP 342.0.0

---

jobs/ml_jobs/retrieval_vector/README.md
jobs/ml_jobs/retrieval_vector/app/factory/handler.py
jobs/ml_jobs/retrieval_vector/app/factory/recommendation.py
jobs/ml_jobs/retrieval_vector/app/factory/similar_offer.py
jobs/ml_jobs/retrieval_vector/app/models/prediction_result.py
jobs/ml_jobs/retrieval_vector/app/retrieval/client.py
jobs/ml_jobs/retrieval_vector/app/retrieval/constants.py
jobs/ml_jobs/retrieval_vector/app/retrieval/core/reranker.py
jobs/ml_jobs/retrieval_vector/app/routes.py
jobs/ml_jobs/retrieval_vector/tests/factory/handler_test.py
jobs/ml_jobs/retrieval_vector/tests/factory/recommendation_test.py
jobs/ml_jobs/retrieval_vector/tests/factory/semantic_offer_test.py
jobs/ml_jobs/retrieval_vector/tests/factory/similar_offer_test.py
jobs/ml_jobs/retrieval_vector/tests/factory/tops_test.py
jobs/ml_jobs/retrieval_vector/tests/retrieval/core/client_test.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(BSR-1675) refactor(retrieval): Refacto endpoints to return search_type info

---

orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__offerer.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-1697) feat(dbt): Adapt offerer_siren test

---

jobs/etl_jobs/internal/bigquery_archive_partition/archive.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(HF) fix(archive): setup look back months

---

jobs/etl_jobs/internal/bigquery_archive_partition/archive.py
jobs/etl_jobs/internal/gcs_seed/tables_config.py
orchestration/Makefile
orchestration/airflow/Dockerfile
orchestration/airflow/config/airflow.cfg
orchestration/airflow/config/pools.json
orchestration/airflow/scripts/create_pools.py
orchestration/airflow/scripts/verify_pools.py
orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__venue.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/schema/int_firebase__native_event_flattened.yaml
orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__offerer.sql
orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__offerer.yml
orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__outgoing_cohort.sql
orchestration/dags/data_gcp_dbt/models/sources.yml
orchestration/dags/dependencies/applicative_database/sql/raw/parallel/venue.sql
orchestration/dags/jobs/crons.py
orchestration/dags/jobs/ml/embedding_extraction_item.py
orchestration/docker-compose.yaml

MEP v343.1.0 

---

jobs/etl_jobs/external/metabase-archiving/utils.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-1695) refactor(archiving): fix metabase archiving rules

---

orchestration/dags/jobs/ml/embedding_extraction_item.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(BSR) fix(embedding extraction): Fix embedding_extraction_item

---

.github/workflows/reusable_build_image.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) fix(CD): fix image build tags

---

orchestration/dags/data_gcp_dbt/models/mart/monitoring/mrt_monitoring__bigquery_cost.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) feat(cost): add airflow origin for bq costs

---

jobs/etl_jobs/external/api_gouv/main.py
jobs/etl_jobs/external/api_gouv/utils/constant.py
jobs/etl_jobs/external/api_gouv/utils/geocoding.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR-1717) chore(api): migrate api address URI to geoplateforme

---

.github/workflows/reusable_deploy_mkdocs.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) fix(ci): dbt variables mkdocs build

---

orchestration/dags/common/operators/gce.py
orchestration/dags/jobs/administration/gcp_launch_vm.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) fix(ssh airflow onto vm): Set use_iap_tunnel to true

---

jobs/ml_jobs/retrieval_vector/app/retrieval/client.py

MEP 345.0.1

---

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_visit.sql
orchestration/dags/data_gcp_dbt/models/mart/pro/mrt_pro__visit.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DA-4209) feat(dbt): Update firebase pro visits

---

jobs/etl_jobs/internal/sync_recommendation/sql/create_enriched_user_mv.sql
jobs/etl_jobs/internal/sync_recommendation/sql/create_iris_france_mv.sql
jobs/etl_jobs/internal/sync_recommendation/sql/create_item_ids_mv.sql
jobs/etl_jobs/internal/sync_recommendation/sql/create_non_recommendable_items_mv.sql
jobs/etl_jobs/internal/sync_recommendation/sql/create_recommendable_offers_raw_mv.sql

* fix: Fix create_recommendable_offers_raw
* fix: Fix materialized views creation
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test …

MEP v345.3.0

---

orchestration/dags/data_gcp_dbt/models/analytics/aggregated_weekly_user_data.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_daily_user_home_module.sql
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_home_offer_displayed.sql
orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__booking.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-1398) feat(bq): add clustering config

---

orchestration/dags/data_gcp_dbt/models/export/backend/exp_backend__adage_home_playlist_local_offerers.sql
orchestration/dags/data_gcp_dbt/models/export/backend/exp_backend__adage_home_playlist_new_venues.sql
orchestration/dags/data_gcp_dbt/models/export/backend/exp_backend__marketing_pro_email_churned_40_days_ago.sql
orchestration/dags/data_gcp_dbt/models/export/backend/exp_backend__marketing_pro_email_last_booking_40_days_ago.sql
orchestration/dags/data_gcp_dbt/models/export/backend/exp_backend__marketing_pro_live_show_email_churned_40_days_ago.sql
orchestration/dags/data_gcp_dbt/models/export/backend/exp_backend__marketing_pro_live_show_email_last_booking_40_days_ago.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DA-4226) feat(dbt): Update backend tables with venue_is_open_to_public

---

jobs/ml_jobs/retrieval_vector/pyproject.toml

Reverts pass-culture/data-gcp#4237

(BSR) chore(prrevert): debug: fake pyporjct description"

---

jobs/etl_jobs/internal/sync_recommendation/sql/create_enriched_user_mv.sql
jobs/etl_jobs/internal/sync_recommendation/sql/create_iris_france_mv.sql
jobs/etl_jobs/internal/sync_recommendation/sql/create_item_ids_mv.sql
jobs/etl_jobs/internal/sync_recommendation/sql/create_non_recommendable_items_mv.sql
jobs/etl_jobs/internal/sync_recommendation/sql/create_recommendable_offers_raw_mv.sql
orchestration/dags/jobs/api/sync_bigquery_to_cloudsql_recommendation_tables.py

* Move renaming of db in a transaction
* Make the refresh sequentials to be less computer intensive
* 
* at the left : before the sequentiallity : all requests are long
* at the right: with sequentiality + 3 min sleep
* at the left : before the sequentiallity : 100% cpu usage
* at the right: with sequentiality 50% max cpu usage
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor …

(DS-1866) fix(sync bq to cloudsql): Make sync cloud sql be less resource intensive on the postgres DB

---

orchestration/dags/data_gcp_dbt/models/export/qualtrics/exp_qualtrics__beneficiary_account.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-1657) feat(dbt): Add user current deposit reform category field to qualtric model

---

jobs/ml_jobs/retrieval_vector/app/retrieval/client.py
orchestration/dags/common/config.py
orchestration/dags/jobs/ml/algo_training_two_towers.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-1807) refactor(storage): bucket migration two towers training

---

orchestration/dags/data_gcp_dbt/models/sources.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-1772) feat(dbt): add volume anomaly test to source booking

---

orchestration/dags/jobs/ml/artist_linkage.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DS-1969) fix(artists): Read test sets from artists folder

---

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__deposit.sql

… pre reform
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
* …

(DE) feat(dbt): fix deposit_reform_category

---

orchestration/dags/data_gcp_dbt/profiles.yml
orchestration/dags/jobs/ml/algo_training_two_towers.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(BSR) feat(twotowers): defer training & evaluation to triggerer

---

orchestration/dags/jobs/ml/algo_training_two_towers.py
orchestration/dags/jobs/ml/embedding_clusterisation_item.py
orchestration/dags/jobs/ml/embedding_extraction_item.py
orchestration/dags/jobs/ml/embedding_reduction_item.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(DE) fix(triggerer): disable deferred airflow task

---

orchestration/dags/jobs/import/import_firebase.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(HF) fix(firebase): add deepcopy firebase performance config

---

orchestration/dags/common/dbt/dbt_executors.py
orchestration/dags/jobs/dbt/dbt_encrypted_export.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE) fix(dbt): type management global cli flags

---

orchestration/dags/common/dbt/dbt_executors.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(HF) fix(dbt): fix cli args

---

orchestration/dags/common/dbt/dbt_executors.py
orchestration/dags/jobs/dbt/dbt_encrypted_export.py

version: v349.0.1
- [] ⚠️ I will click on **Merge Pull Request** and **NOT** *on Squash and merge*

MEP v349.0.1

---

orchestration/dags/data_gcp_dbt/models/export/backend/exp_backend__artist_alias_delta.sql
orchestration/dags/data_gcp_dbt/models/export/backend/exp_backend__artist_delta.sql
orchestration/dags/data_gcp_dbt/models/export/backend/exp_backend__product_artist_link_delta.sql
orchestration/dags/data_gcp_dbt/models/machine_learning/linkage/ml_linkage__delta_artist.sql
orchestration/dags/data_gcp_dbt/models/machine_learning/linkage/ml_linkage__delta_artist_alias.sql
orchestration/dags/data_gcp_dbt/models/machine_learning/linkage/ml_linkage__delta_product_artist_link.sql
orchestration/dags/data_gcp_dbt/models/sources.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(DS-1917) feat(artist): Export delta tables to backend

---

jobs/etl_jobs/external/siren/scripts/import_siren.py
jobs/etl_jobs/external/siren/scripts/utils.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-1880) fix(siren): Modify siren API route

---

.github/workflows/README.md
.github/workflows/on_cd__workflow.yml
.github/workflows/reusable_deploy_airflow.yml
jobs/etl_jobs/external/metabase-dbt/main.py
orchestration/README.md
orchestration/dags/data_gcp_dbt/.env.dbt
orchestration/dags/data_gcp_dbt/scripts/defer_local_run.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) refactor(CI): Clean CI from Composer to Airflow

---

.github/workflows/reusable_dbt_workflow.yml
.github/workflows/scripts/run_dbt_changed_models.sh

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE) ci(dbt): skip model testing when no models have been modified

---

orchestration/dags/common/dbt/dbt_executors.py
orchestration/dags/data_gcp_dbt/macros/airflow/is_first_day_of_month.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(HF) fix(dbt): inject scheduled date in SQL from airflow context python

---

orchestration/dags/data_gcp_dbt/models/analytics/aggregated_weekly_user_data.sql
orchestration/dags/data_gcp_dbt/models/intermediate/seed/int_seed__monthly_france_population.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) dbt(schedule): enforce models schedules in config

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__offer.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/export/ministry/description__exp_ministry__favorite.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/export/ministry/description__exp_ministry__offer.md

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DA-2156) docs(dbt): Add dbt doc for global offer

---

Makefile
jobs/etl_jobs/external/contentful/contentful_client.py
jobs/etl_jobs/external/contentful/main.py
jobs/etl_jobs/external/contentful/pyproject.toml
jobs/etl_jobs/external/contentful/requirements.in
jobs/etl_jobs/external/contentful/requirements.txt
orchestration/dags/jobs/crons.py
orchestration/dags/jobs/import/import_contentful.py
orchestration/dags/jobs/import/import_sendinblue.py

MEP v352.1.0

---

jobs/ml_jobs/artist_linkage/queries/extract_book_artists.rq
jobs/ml_jobs/artist_linkage/queries/extract_music_artists.rq
jobs/ml_jobs/artist_linkage/streamlits/st_analyze_linkage_from_scratch.py
jobs/ml_jobs/artist_linkage/utils/gcs_utils.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(DS-1929) feat(artist): Update wikidata queries

---

orchestration/dags/jobs/import/import_social_media.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(HF) fix(tiktok): increase dag timeout

---

orchestration/dags/data_gcp_dbt/models/machine_learning/linkage/_schema/ml_linkage__artist_alias.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DS-2265) fix(artists): Fix artist_alias dbt tests

---

orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/_schema/ml_reco__recommendable_item.yml
orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/_schema/ml_reco__recommendable_offer.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-2326) fix(elementary): fixed dimension anomalies false warning by tolerating 5% spike and drop

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/tracking/column__event.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/monitoring/description__mrt_monitoring__firebase_performance_tti.md
orchestration/dags/data_gcp_dbt/models/intermediate/firebase/performance/int_firebase__performance.sql
orchestration/dags/data_gcp_dbt/models/mart/monitoring/_schema/mrt_monitoring__firebase_performance_tti.yml
orchestration/dags/data_gcp_dbt/models/mart/monitoring/mrt_monitoring__firebase_performance_tti.sql
orchestration/dags/data_gcp_dbt/models/sources.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-1770) feat(dbt): add mart firebase performance model

---

.github/workflows/scripts/run_dbt_changed_models.sh
orchestration/dags/data_gcp_dbt/dbt_project.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(HF) dbt(ci): reduce dev TTL & fix ci dbt run model step to fail when model error 

---

.sqlfluff

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(AE-2001) lint(sqlfluff): add variable to dbt precommit templater

---

orchestration/dags/data_gcp_dbt/tests/generic/not_null_proportion_test.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) fix(not_null_proportion): fix mrt_global_user not_null_proportion test keyword error

---

orchestration/dags/data_gcp_dbt/models/mart/external_reporting/top/mrt_external_reporting__top_offer.sql
orchestration/dags/data_gcp_dbt/models/mart/external_reporting/top/mrt_external_reporting__top_offer_category.sql
orchestration/dags/data_gcp_dbt/models/mart/external_reporting/top/mrt_external_reporting__top_venue.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE) feat(dbt): Fix mrt external reporting top

---

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/performance/int_firebase__performance.sql
orchestration/dags/data_gcp_dbt/models/mart/monitoring/mrt_monitoring__firebase_performance_tti.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(HF) fix(firebase): performance load data at D-2

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/pcapi/column__log.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/pro/description__mrt_pro__log.md
orchestration/dags/data_gcp_dbt/models/intermediate/pcapi/int_pcapi__log.sql
orchestration/dags/data_gcp_dbt/models/mart/pro/_schema/mrt_pro__log.yml
orchestration/dags/data_gcp_dbt/models/mart/pro/mrt_pro__log.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DA-4390) feat(dbt): Update mrt_pro__log and its doc

---

.github/workflows/on_pr_check_hour.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(BSR) fix(code_injection): fix code injection in PR title env variable

---

jobs/etl_jobs/external/titelive/Makefile
jobs/etl_jobs/external/titelive/README.md
jobs/etl_jobs/external/titelive/pyproject.toml
jobs/etl_jobs/external/titelive/scripts/upload_titelive_images_to_gcs.py
jobs/etl_jobs/external/titelive/src/utils/gcp.py
jobs/etl_jobs/external/titelive/uv.lock
orchestration/dags/jobs/import/import_titelive.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(DE-2254) feat(titelive): Extract titelive image to gcs

---

jobs/etl_jobs/external/titelive/scripts/parse_products.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(BSR) fix(titelive): Fix titelive parsing

---

jobs/etl_jobs/external/titelive/scripts/parse_products.py
jobs/ml_jobs/artist_linkage/constants.py
jobs/ml_jobs/artist_linkage/get_wikimedia_commons_license.py
jobs/ml_jobs/artist_linkage/link_new_products_to_artists.py
jobs/ml_jobs/artist_linkage/utils/matching.py
orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__offerer.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/external_reporting/collective/description__mrt_external_reporting__eac_credit_usage.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/external_reporting/collective/description__mrt_external_reporting__eac_cultural_partner.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/external_reporting/collective/description__mrt_external_reporting__eac_domain.md
orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/external_reporting/collective/description__mrt_external_reporting__eac_offer_booking.md
orchestration/dags/data_gcp_dbt/models/analytics/eple_aggregated.sql
orchestration/dags/data_gcp_dbt/models/mart/external_reporting/collective/ephemerals_kpis/_schema/mrt_external_reporting__eac_credit_usage.yml
orchestration/dags/data_gcp_dbt/models/mart/external_reporting/collective/ephemerals_kpis/_schema/mrt_external_reporting__eac_cultural_partner.yml
orchestration/dags/data_gcp_dbt/models/mart/external_reporting/collective/ephemerals_kpis/_schema/mrt_external_reporting__eac_domain.yml
orchestration/dags/data_gcp_dbt/models/mart/external_reporting/collective/ephemerals_kpis/_schema/mrt_external_reporting__eac_offer_booking.yml
orchestration/dags/data_gcp_dbt/models/mart/external_reporting/collective/ephemerals_kpis/mrt_external_reporting__eac_credit_usage.sql
orchestration/dags/data_gcp_dbt/models/mart/external_reporting/collective/ephemerals_kpis/mrt_external_reporting__eac_cultural_partner.sql
orchestration/dags/data_gcp_dbt/models/mart/external_reporting/collective/ephemerals_kpis/mrt_external_reporting__eac_domain.sql
orchestration/dags/data_gcp_dbt/models/mart/external_reporting/collective/ephemerals_kpis/mrt_external_reporting__eac_offer_booking.sql
orchestration/dags/data_gcp_dbt/models/mart/external_reporting/individual/ephemerals_kpis/mrt_external_reporting__cultural_partner.sql
orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__offerer.yml
orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__offerer.sql

MEP 455.2.0

---

orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/external_reporting/collective/description__mrt_external_reporting__eac.md
orchestration/dags/data_gcp_dbt/models/mart/external_reporting/collective/mrt_external_reporting__eac.sql
orchestration/dags/data_gcp_dbt/models/mart/external_reporting/collective/mrt_external_reporting__eac.yml

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE-2286) dbt(propilote): create one big table propilote eac kpis

---

orchestration/dags/data_gcp_dbt/models/mart/external_reporting/collective/ephemerals_kpis/mrt_external_reporting__eac_domain.sql

…ain model
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
* …

(BSR) fix(propilote): use domain.label in where condition for eac_domain model

---

orchestration/dags/data_gcp_dbt/models/mart/external_reporting/collective/ephemerals_kpis/mrt_external_reporting__eac_cultural_partner.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE) feat(dbt): Propilote - fix eac cultural partner model

---

orchestration/k8s-airflow/Dockerfile.k8s-worker

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(HF) build(workers): update gg cli version for airflow workers

---

orchestration/dags/common/utils.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(HF) fix(airflow): remove unused import from unexisting package

---

orchestration/dags/dependencies/applicative_database/sql/raw/parallel/bank_account.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(HF) refactor(import): remove bic in bank account

---

orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__offerer.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE) feat(dbt): Change epn tag to MC only

---

orchestration/dags/jobs/export/export_ppg.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(DE) fix(ppg): instance type

---

jobs/ml_jobs/artist_linkage/link_new_products_to_artists.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(BSR) fix(artists): fix artist alias sanity check

---

orchestration/dags/data_gcp_dbt/models/export/ministry/exp_ministry__deposit.sql

…filtering from mart
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(HF) dbt(ministry): fix references in deposit export to include role filtering from mart

---

orchestration/dags/data_gcp_dbt/models/export/backend/exp_backend__artist_delta.sql

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt
examples: …

(BSR) fix(artist): Add missing wikidata_id in artist_delta table

---

orchestration/dags/jobs/import/import_qpi.py

<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* chore
* dbt …

(HF) fix(qpi): fix bucket name in QPI_exports

---

orchestration/dags/jobs/import/import_qpi.py

MEP v 461.1.2
