pass-culture/data-gcp

orchestration/dags/dependencies/monitoring.py, orchestration/dags/import_analytics.py, orchestration/tests/dags_test.py
=> MEP v144.0.0

additional_data_sources/dms-function-source/main.py, additional_data_sources/siren-function-source/scripts/import_siren.py, analytics/tests/config.py, analytics/tests/data.py, orchestration/dags/dependencies/data_analytics/enriched_data/user.py, orchestration/dags/dependencies/data_analytics/import_tables.py, orchestration/dags/extract_offer_tags.py
=> MEP v155.1.0

algo_training/choose_training_period.py, algo_training/data_collect.py, algo_training/models/metrics.py, orchestration/dags/dependencies/monitoring.py, orchestration/dags/monitoring.py, recommendation/api/recommendation.py, recommendation/api/tests/recommendation_test.py, recommendation/db/scripts/create_recommendable_offers.sql
=> MEP v158.0.0

analytics/tests/config.py, analytics/tests/data.py, orchestration/dags/dependencies/data_analytics/enriched_data/user.py, orchestration/dags/dependencies/data_analytics/import_tables.py
* remove dependency to user_is_beneficiary
* remove ALL dependencies in subqueries
* fix tests
* fix linter
* fix user_role type in config
* test bigquery schema function
* cancel changes
* import only first user role as string in user table
* fix input data in test
* remove unnests in enriched_user_data script
Co-authored-by: adrienlin <lin.adrien@gmail.com>
=> MEP v162.0.0

orchestration/dags/recommendation_cloud_sql.py
Co-authored-by: Colin ZACCOMER <c.zaccomer@groupeonepoint.com>
=> MEP 171.0.0

recommendation/api/not_eac/scoring.py
=> MEP 172.1.0

recommendation/api/eac/eac_scoring.py, recommendation/api/not_eac/scoring.py
=> MEP 172.1.1

algo_training/tools/v2/deep_reco/preprocess_tools.py, algo_training/train_v2_deep_reco.py, algo_training/train_v2_mf_reco.py, algo_training/utils.py, orchestration/dags/algo_training_v2_mf_reco.py, orchestration/dags/dependencies/data_analytics/import_tables.py, recommendation/api/eac/eac_scoring.py, recommendation/api/not_eac/scoring.py
MEP rapide pour intégrer le debugging de booking_status import
=> MEP 172.2.0

orchestration/dags/monitoring.py
=> MEP 179.1.1

additional_data_sources/cni_fraude_algo-function-source/requirements.txt, additional_data_sources/siren-function-source/scripts/import_siren.py, algo_training/requirements.txt, orchestration/dags/dependencies/slack_alert_analytics.py, orchestration/dags/import_analytics.py, recommendation/api/app.py, recommendation/api/eac/eac_scoring.py, recommendation/api/not_eac/scoring.py, recommendation/api/recommendation.py, recommendation/api/tests/api_test.py, recommendation/api/tests/recommendation_test.py
=> MEP v183.0.0

.circleci/config.yml, .gitignore, orchestration/orchestration-requirements.txt, orchestration/tests/analytics/config.py, orchestration/tests/analytics/data.py, orchestration/tests/analytics/utils/gcp.py, orchestration/tests/analytics/utils/json.py, orchestration/tests/dags_test.py, orchestration/tests/test_queries.py
**Done** 
- Move analytics test into orchestration and remove CircleCI analytics job.
- Clean comparison of json for analytics_tests
- Remove test that are testing number of jobs in dags. 
**Still needs to be done into another PR:**
- Refactor orchestration tests naming in order to keep code hierarchy naming
- Simplify test_dags into one functions
=> [PC-9130] Refactor Tests v1

.circleci/config.yml, .gitignore, orchestration/dags/dependencies/config.py, orchestration/dags/dependencies/monitoring.py, orchestration/dags/export_cloudsql_tables_to_bigquery.py, orchestration/dags/monitoring.py, orchestration/orchestration-requirements.txt, orchestration/tests/analytics/config.py, orchestration/tests/analytics/data.py, orchestration/tests/analytics/utils/gcp.py, orchestration/tests/analytics/utils/json.py, orchestration/tests/dags_test.py, orchestration/tests/test_queries.py
=> MEP v185.1.0

orchestration/dags/dependencies/data_analytics/enriched_data/enriched_firebase.py, orchestration/dags/import_analytics_incremental.py, orchestration/tests/dags_test.py
=> MEP v185.2.0

orchestration/dags/common/alerts.py
This does not work with Airflow 1.X
=> [PC-14757] Remove run_id

additional_data_sources/dms-function-source/main.py, orchestration/dags/algo_training_v1.py, orchestration/dags/algo_training_v2_deep_reco.py, orchestration/dags/algo_training_v2_mf_reco.py, orchestration/dags/dependencies/data_analytics/enriched_data/enriched_firebase.py, orchestration/dags/dependencies/data_analytics/enriched_data/offerer.py, orchestration/dags/dependencies/data_analytics/enriched_data/venue.py, orchestration/dags/dependencies/data_analytics/import_tables.py, orchestration/dags/dependencies/dms_import.py, orchestration/dags/import_dms_subscriptions.py, orchestration/tests/data_analytics/data.py
=> MEP 189.0.0

orchestration/dags/dependencies/data_analytics/enriched_data/collective_booking.py
=> MEP v189.0.3 

orchestration/dags/algo_training_v1.py, orchestration/dags/algo_training_v2_mf_reco.py
Keep morning time for diversification jobs
=> Update train hour models

additional_data_sources/downloads-function-source/apple_client.py, additional_data_sources/downloads-function-source/google_client.py, additional_data_sources/downloads-function-source/main.py, additional_data_sources/downloads-function-source/requirements.txt, additional_data_sources/downloads-function-source/utils.py
If you want to test:
```sh
-- SELECT * FROM `passculture-data-ehp.raw_dev.apple_download_stats` LIMIT 1000
-- SELECT * FROM `passculture-data-ehp.raw_dev.google_download_stats` LIMIT 1000
```
**Next steps:**
Recreate another table that joins the two bases tables into clean_xxx with:
```
date, provider, total_downloads
```
And link old tables to this new tables if any.
=> [PC-15148] Daily downloads apple and google

additional_data_sources/downloads-function-source/apple_client.py, additional_data_sources/downloads-function-source/main.py, additional_data_sources/downloads-function-source/utils.py
Add params to the cloud function in order to re-run _by-hand_ historical data
=> [PC-15591] historical data for downloads

orchestration/dags/airflow_monitoring.py, orchestration/dags/common/macros.py, orchestration/dags/dependencies/data_analytics/enriched_data/enriched_firebase.py, orchestration/dags/dependencies/data_analytics/import_historical.py, orchestration/dags/import_firebase_data.py, orchestration/tests/dags_test.py
When MES or MEP, need to change firebase_pro_table to partitionned one. 
IE,
```sql 
CREATE TABLE `passculture-data-ehp.analytics_dev.firebase_pro_events_cp`
PARTITION BY event_date
AS SELECT * FROM `passculture-data-ehp.analytics_dev.firebase_pro_events`;
```
then delete, 
then copy again
=> [PC-15337] firebase intraday import

.circleci/config.yml, orchestration/dags/dependencies/config.py, orchestration/dags/dependencies/metabase/import_metabase.py, orchestration/dags/dependencies/metabase/sql/raw/core_session.sql, orchestration/dags/dependencies/metabase/sql/raw/core_user.sql, orchestration/dags/dependencies/metabase/sql/raw/login_history.sql, orchestration/dags/dependencies/metabase/sql/raw/query.sql, orchestration/dags/dependencies/metabase/sql/raw/query_execution.sql, orchestration/dags/dependencies/metabase/sql/raw/report_card.sql, orchestration/dags/dependencies/metabase/sql/raw/report_dashboard.sql, orchestration/dags/import_metabase.py
Import tables from Metabase in order to see top dashboards
Query example with results from stagging: 
```sql
SELECT 
qe.id,
qe.started_at,
qe.hash,
qe.running_time,
qe.result_rows,
qe.context,
qe.error,
qe.cache_hit,
q.average_execution_time, 
q.query,
qe.executor_id,
cu.email  as executor_email,
qe.dashboard_id,
rd.dashboard_name,
rd.dashboard_description,
rd.dashboard_creator_id,
qe.card_id,
rc.card_name,
rc.card_description,
rc.card_creator_id
FROM `passculture-data-ehp.raw_dev.metabase_query_execution` qe 
LEFT JOIN `passculture-data-ehp.raw_dev.metabase_query`  q on qe.hash = q.query_hash
LEFT JOIN`passculture-data-ehp.raw_dev.metabase_report_dashboard` rd  on rd.id = qe.dashboard_id
LEFT JOIN `passculture-data-ehp.raw_dev.metabase_report_card` rc  on rc.id = qe.card_id
LEFT JOIN …
```
=> [PC-15649] Import Metabase DB to BQ

additional_data_sources/downloads-function-source/main.py, diversification_kpi/diversification_data.py, diversification_kpi/tools/diversification_kpi.py, orchestration/dags/dependencies/data_analytics/enriched_data/deposit.py, orchestration/dags/diversification_kpi_v1.py
=> MEP v193.0.0 

orchestration/dags/dependencies/logs/import_logs.py, orchestration/dags/dependencies/logs/sql/analytics/collective_logs.sql
Import collective logs to analytics
=> [PC-15919] Collective logs

additional_data_sources/siren-function-source/scripts/import_siren.py, algo_training/train_v1.py, orchestration/dags/dependencies/firebase/import_firebase.py, orchestration/dags/jobs/ml/algo_training_v1.py, recommendation/api/src/pcreco/core/scoring.py, recommendation/api/src/pcreco/core/utils/diversification.py, recommendation/api/src/tests/diversification_test.py, recommendation/db/scripts/create_recommendable_offers.sql
=> MEP v197.2.0

orchestration/dags/dependencies/import_analytics/sql/analytics/aggregated_daily_user_used_activity.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/aggregated_monthly_user_used_booking_activity.sql, orchestration/dags/dependencies/open_data/export_open_data.py, orchestration/dags/dependencies/open_data/sql/open_data/aggregated_usage_and_intensity.sql
- Add department and region into intensification table for open data
- Partition table in order to historize it.
=> [PC-16269] Improve Datasources for open data

algo_training/evaluate.py, algo_training/metrics.py, algo_training/tools/diversification.py, algo_training/tools/v1/data_collect_queries.py
- Add diversification features to raw training data
- Add diversification score to training metrics , before and after 'panachage'
- Update personalization metrics : 'panachage' effect 
- Update panachage rule to match pcreco : switch from 'categoryId' to 'subcategoryId'
=> [PC-15876] add diversification score to training metrics

additional_data_sources/typeform-adage-reference-request-source/requirements.txt, algo_training/evaluate.py, algo_training/metrics.py, algo_training/tools/diversification.py, algo_training/tools/v1/data_collect_queries.py, diversification_kpi/requirements.txt, orchestration/dags/dependencies/open_data/sql/open_data/aggregated_monthly_used_booking.sql, orchestration/dags/dependencies/open_data/sql/open_data/aggregated_monthly_user_data.sql, orchestration/dags/dependencies/open_data/sql/open_data/aggregated_usage_and_intensity.sql, orchestration/dags/jobs/import/import_typeform_adage_reference_request.py, recommendation/api/Dockerfile, recommendation/api/src/app.py, recommendation/api/src/pcreco/core/scoring.py, recommendation/api/src/pcreco/utils/ai_platform/get_ai_platform_service.py, recommendation/api/src/pcreco/utils/env_vars.py
=> MEP v198.0.0

recommendation/api/api-dev-requirements.txt, recommendation/api/api-requirements.txt, recommendation/api/src/pcreco/core/scoring.py, recommendation/api/src/pcreco/core/utils/vertex_ai.py, recommendation/api/src/pcreco/utils/env_vars.py
=> MEP v199.0.0

algo_training/clean_model_versions.py, algo_training/deploy_model.py, algo_training/requirements.txt, orchestration/dags/jobs/ml/algo_training_v1.py
- import model to model registery after training 
- deploy model to endpoint 
- undeploy the previous version 
- clear old versions
=> [fix-auto-deploy-to-vertex-ai]

orchestration/dags/dependencies/firebase/import_firebase.py, orchestration/dags/dependencies/firebase/sql/analytics/firebase_home_events.sql
=> MEP 202.1.0

.gitignore, orchestration/dags/dependencies/import_analytics/import_tables.py, orchestration/dags/dependencies/import_analytics/sql/clean/iris_venues.sql, orchestration/dags/jobs/api/recommendation_cloud_sql.py, recommendation/api/src/app.py, recommendation/api/src/pcreco/core/scoring.py, recommendation/api/src/pcreco/core/user.py, recommendation/api/src/pcreco/models/reco/recommendation.py, recommendation/api/src/tests/conftest.py, recommendation/db/scripts/create_enriched_user.sql
=> MEP v202.2.0

orchestration/dags/dependencies/firebase/sql/analytics/firebase_events.sql
- Added new reco firebase parameter
- Removed old ab_test field
```
ALTER TABLE `xxx.firebase_events` DROP COLUMN IF EXISTS ab_test
```
=> [PC-17045](reco) add firebase events

additional_data_sources/dms-function-source/main.py, orchestration/dags/dependencies/firebase/sql/analytics/firebase_home_events.sql, orchestration/dags/dependencies/import_dms_subscriptions.py, orchestration/dags/jobs/api/recommendation_cloud_sql.py
=> MEP 204.1.0

orchestration/dags/common/operator.py, orchestration/dags/dependencies/qualtrics/export_qualtrics_data.py, orchestration/dags/dependencies/qualtrics/sql/clean/qualtrics_ir_jeunes.sql, orchestration/dags/jobs/export/export_qualtrics_data.py, orchestration/dags/jobs/import/import_contentful.py
- Première étape pour l'export des données automatiquement via Qualtrics par mois.
- - Export des IR Jeunes (18 - 15_17) sans prendre en compte s'ils ont déjà été contactés par le passé (ce sera en V1)
=> [PC-15041] Export Survey to Qualtrics Data

additional_data_sources/adage-function-source/main.py, additional_data_sources/adage-function-source/scripts/import_adage.py, additional_data_sources/adage-function-source/scripts/utils.py, diversification_kpi/diversification_data.py, diversification_kpi/tools/diversification_kpi.py, orchestration/dags/common/operator.py, orchestration/dags/dependencies/qualtrics/export_qualtrics_data.py, orchestration/dags/dependencies/qualtrics/sql/clean/qualtrics_ir_jeunes.sql, orchestration/dags/dependencies/typeform/enriched_qpi_answers_v4.py, orchestration/dags/jobs/export/export_qualtrics_data.py, orchestration/dags/jobs/import/import_adage.py, orchestration/dags/jobs/import/import_contentful.py, recommendation/db/scripts/create_recommendable_offers_eac_15.sql
=> MEP v204.1.0

orchestration/dags/dependencies/firebase/import_firebase.py, orchestration/dags/dependencies/metabase/sql/analytics/metabase_activity.sql
=> MEP v212.2.0

recommendation/api/src/pcreco/core/recommendation.py
=> MEP v212.2.1

diversification_kpi/diversification_data.py, diversification_kpi/tools/diversification_kpi.py, orchestration/dags/dependencies/import_analytics/sql/analytics/aggregated_daily_user_used_activity.sql
- Add diversification score in _aggregated_daily_user_used_activity_
- Fix mismatch for digital offers in _calculate_diversification_per_feature_ function
=> [PC-17927] ingest diversification score in aggregated table

orchestration/dags/common/config.py, orchestration/dags/dependencies/import_analytics/import_tables.py, orchestration/dags/dependencies/import_analytics/sql/analytics/top_items_data.sql, orchestration/dags/dependencies/propilote/sql/tmp/propilote_tmp_kpis.sql, orchestration/dags/jobs/api/export_cloudsql_tables_to_bigquery.py, orchestration/dags/jobs/api/recommendation_cloud_sql.py, recommendation/api/postman/api_integration_tests.postman_collection.json, recommendation/db/scripts/create_iris_france.sql, recommendation/db/scripts/create_qpi_answers.sql
=> MEP v215.1.0

algo_training/data_collect.py, algo_training/requirements.txt, algo_training/tools/data_collect_queries.py, orchestration/dags/common/config.py, orchestration/dags/jobs/ml/algo_training_r_and_d.py, orchestration/dags/jobs/ml/constants.py, orchestration/dags/jobs/ml/process_training_data.py
Le evaluate fail car il n'a pas assez de donnée :
=> Pc 18997 add dag training algo r and d

orchestration/dags/jobs/ml/algo_training_r_and_d.py, orchestration/dags/jobs/ml/algo_training_v1.py
Reverts pass-culture/data-gcp#1203
=> Revert "[HOTFIX](airflow) Fix fetch-code-cmd"

orchestration/dags/dependencies/import_analytics/import_clean.py, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_deposit_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_user_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/user_penetration.sql, orchestration/dags/dependencies/import_analytics/sql/clean/user_beneficiary.sql, orchestration/dags/dependencies/propilote/sql/analytics/propilote_kpis.sql, orchestration/tests/data_analytics/config.py, orchestration/tests/data_analytics/data.py
- Création de la table user_beneficiary en zone "clean" 
- Ajout des départements 2A & 2B dans la table enriched_user_data
=> (PC-19439) Distinguer 2A/2B en corse + optimiser query

orchestration/dags/dependencies/import_analytics/import_analytics.py, orchestration/dags/dependencies/import_analytics/sql/analytics/diversification_booking_v2.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/diversification_raw_v2.sql
[Ici ](https://www.notion.so/passcultureapp/Diversification-des-pratiques-culturelles-3f7fc6efd8c04eb6bf93f570e3bf8ae7): règles de gestion du calcul de la diversification en V2.
=> (PC-19857) Diversification table v2

orchestration/dags/dependencies/import_analytics/sql/raw/cashflow.sql, orchestration/dags/dependencies/sendinblue/import_sendinblue.py, orchestration/dags/jobs/import/import_sendinblue.py
related to this [PR](https://github.com/pass-culture/pass-culture-main/pull/5527)
=> (PC-20991) remove transaction id in cashflow table

additional_data_sources/appsflyer-function-source/main.py, additional_data_sources/sendinblue-function-source/main.py, additional_data_sources/sendinblue-function-source/sendinblue_transactional.py, additional_data_sources/sendinblue-function-source/utils.py, algo_training/evaluate.py, orchestration/dags/dependencies/firebase/sql/analytics/firebase_aggregated_search_events.sql, orchestration/dags/dependencies/firebase/sql/analytics/firebase_events.sql, orchestration/dags/dependencies/import_analytics/sql/raw/cashflow.sql, orchestration/dags/jobs/import/import_appsflyer.py, recommendation/api/postman/api_integration_tests.postman_collection.json
=> MEP v231.0.0

orchestration/dags/dependencies/import_analytics/import_analytics.py, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_suivi_dms_adage.sql
- retirer les dépendances avec les tables enrichies (row64 + row76-78)
- remplacer les dépendances à la zone analytics : analytics_{env}.applicative_database_ par clean_{env}.applicative_database_
=> (PC-20999) dependencies enriched_dms_adage

orchestration/dags/dependencies/firebase/import_firebase.py, orchestration/dags/dependencies/firebase/sql/analytics/firebase_bookings.sql, orchestration/dags/dependencies/firebase/sql/analytics/firebase_home_funnel_conversion.sql
=> MEP v241.1.0

orchestration/dags/dependencies/firebase/sql/analytics/firebase_home_funnel_conversion.sql
- add user_id
- rank on the first module displayed + the first special module clicked
=> firebase_home_funnel_conversion v2

apps/recommendation/api/src/app.py, apps/recommendation/api/src/pcreco/core/model_selection/__init__.py, apps/recommendation/api/src/pcreco/core/model_selection/recommendation.py, apps/recommendation/api/src/pcreco/core/model_selection/similar_offer.py, apps/recommendation/api/src/pcreco/core/recommendation.py, apps/recommendation/api/src/pcreco/core/scorer/similar_offer.py, apps/recommendation/api/src/pcreco/core/similar_offer.py, apps/recommendation/api/src/pcreco/core/utils/query_builder.py, apps/recommendation/api/src/pcreco/core/utils/vertex_ai.py, apps/recommendation/api/src/pcreco/models/reco/playlist_params.py, apps/recommendation/api/src/pcreco/utils/health_check_queries.py, orchestration/dags/dependencies/import_analytics/import_analytics.py, orchestration/dags/dependencies/import_analytics/sql/analytics/firebase_home_macro_conversion.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/firebase_home_micro_conversion.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/firebase_home_whole_path_conversion.sql
=> MEP v244.0.0

orchestration/dags/dependencies/import_analytics/import_analytics.py, orchestration/dags/dependencies/import_analytics/import_clean.py, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_cultural_partner_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_cultural_partner_data_v2.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_offerer_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_offerer_tags_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_venue_data.sql, orchestration/dags/dependencies/import_analytics/sql/clean/bookable_collective_offer.sql, orchestration/tests/data_analytics/config.py, orchestration/tests/data_analytics/data.py
To do : 
- fix typos, column aliases etc
- fix analytics tests
=> [PC-22819] wip enriched cultural partner v2 + refacto

jobs/etl_jobs/external/dms/utils.py, orchestration/dags/dependencies/import_analytics/sql/analytics/bookable_collective_offer_history.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_collective_offer_data.sql, orchestration/dags/dependencies/import_analytics/sql/raw/collective_offer.sql, orchestration/tests/data_analytics/config.py, orchestration/tests/data_analytics/data.py
=> MEP 250.2.0

orchestration/dags/dependencies/logs/sql/analytics/adage_logs.sql
(other filters will soon be added)
=> Add new search parameters to adage_logs 

orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_offerer_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_stock_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_suivi_dms_adage.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_venue_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/firebase_aggregated_search_events.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/funnel_subscription_beneficiary.sql, orchestration/dags/dependencies/logs/sql/analytics/adage_logs.sql, orchestration/tests/data_analytics/config.py, orchestration/tests/data_analytics/data.py
=> MEP v259.0.0

.github/PULL_REQUEST_TEMPLATE/DA_ticket_template.md, .github/PULL_REQUEST_TEMPLATE/DE_ticket_template.md, .github/PULL_REQUEST_TEMPLATE/DS_ticket_template.md, .github/PULL_REQUEST_TEMPLATE/hotfix_template.md, .github/pull_request_template.md
pull request template first draft
=> (github) Create pull_request_template.md

orchestration/dags/dependencies/import_analytics/sql/clean/booking.sql
=> PC-24699-bis Add offer_id to booking

jobs/etl_jobs/external/gsheet/gsheet.py, jobs/etl_jobs/external/gsheet/main.py, jobs/etl_jobs/external/gsheet/requirements.txt, orchestration/dags/jobs/import/import_gsheet.py
Add gsheet VM dag to import external files in a recurrent way. 
[PC-24806]: https://passculture.atlassian.net/browse/PC-24806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-24806](import) Gsheet import 

orchestration/dags/common/hooks/gce.py
=> hotfix vm-labels

orchestration/dags/common/utils.py, orchestration/dags/dependencies/backend/create_tables.py, orchestration/dags/dependencies/contentful/import_contentful.py, orchestration/dags/jobs/export/export_backend_tables.py, orchestration/dags/jobs/export/export_propilote.py, orchestration/dags/jobs/export/export_qualtrics_data.py, orchestration/dags/jobs/import/import_analytics.py, orchestration/dags/jobs/import/import_appsflyer.py, orchestration/dags/jobs/import/import_batch.py, orchestration/dags/jobs/import/import_cold_data.py, orchestration/dags/jobs/import/import_contentful.py, orchestration/dags/jobs/import/import_firebase.py, orchestration/dags/jobs/import/import_qpi.py, orchestration/dags/jobs/import/import_sendinblue.py, orchestration/dags/jobs/import/metabase_governance.py
This PR fixes the duplicated tasks of waiting for the completion of other airflow dags. 
Logique : au lieu de définir les dépendances en partant de chaque table qu'on importe, cette modification de code permet de récupérer les tâches dépendantes et de leur associer la liste des tables qui nécessitent leur succès.
/!\ pas encore fix : certaines liaisons des dags sont inutiles, rendant le graph moins lisible mais reste fonctionnel.
https://passculture.atlassian.net/jira/software/c/projects/PC/boards/24?modal=detail&selectedIssue=PC-24565
=> (PC-24565) data ameliorer les taches dattente dautres dag dans import analytics

orchestration/dags/dependencies/import_analytics/sql/analytics/aggregated_cinema_details.sql
this PR aggregates the 3 sources of cinema within a new analytic table
[PC-24430](https://passculture.atlassian.net/jira/software/c/projects/PC/boards/33?modal=detail&selectedIssue=PC-24430)
[PC-24430]: https://passculture.atlassian.net/browse/PC-24430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> cine details aggregation

jobs/etl_jobs/external/adage/scripts/import_adage.py, jobs/etl_jobs/external/adage/scripts/utils.py, jobs/etl_jobs/internal/cold-data/tables_config.py
- créer la table froide institution_scholar_level avec les différents niveaux d'éducation
- adapter l'import de la table clean_env.adage_involved_students de manière à récupérer les statistiques adage par niveau d'élèves
https://passculture.atlassian.net/browse/PC-24937
<summary>DE PR</summary>
=> (PC-24937) add adage stats per school level

orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_venue_data.sql, orchestration/dags/dependencies/import_analytics/sql/raw/venue.sql, orchestration/dags/dependencies/logs/sql/analytics/adage_logs.sql, orchestration/tests/data_analytics/config.py, orchestration/tests/data_analytics/data.py
<details>
<summary>Hotfix</summary>
</details>
<details>
<summary>DA PR</summary>
</details>
<details>
<summary>DE PR</summary>
</details>
<details>
<summary>DS PR</summary>
</details>
<details>
<summary>MEP</summary>
version:
-[ ] version number
-[ ] CI/CD tests pass
-[ ] Add message on data review slack channel
=> Add fields in adage_logs and enriched_venue_data

.github/PULL_REQUEST_TEMPLATE/DA_ticket_template.md, .github/PULL_REQUEST_TEMPLATE/DE_ticket_template.md, .github/PULL_REQUEST_TEMPLATE/DS_ticket_template.md, .github/PULL_REQUEST_TEMPLATE/Hotfix_template.md, .github/PULL_REQUEST_TEMPLATE/MEP_template.md, .github/pull_request_template.md
Simpler templates: 1 more clic, 10x less headache
<summary>Hotfix</summary>
=> PR templates selection

orchestration/dags/jobs/import/import_dms_subscriptions.py
This PR adds a desynchronization lag between dms jeunes & dms pro to prevent random dag failure of one of them
<summary>DE PR</summary>
=> Dms dag async

orchestration/dags/dependencies/import_analytics/import_analytics.py, orchestration/dags/jobs/airflow_cleaning.py, orchestration/dags/jobs/import/import_dms_subscriptions.py
This PR add a long task label to increase timeout and prevent early instances cleaning.
e.g. querying DMS from the beginning has become too long since we reduced the number of results per query 100->10
and the instance keeps dying before the end of the job
<summary>DE PR</summary>
=> Add label for long task

orchestration/dags/dependencies/logs/sql/analytics/adage_logs.sql
This PR remove duplicate column in adage logs
=> remove duplicate column name

orchestration/dags/dependencies/cold_data/import_cold_data.py, orchestration/dags/dependencies/cold_data/sql/clean/institution_scholar_level.sql, orchestration/dags/jobs/import/import_cold_data.py
=> (cold-data) add institution_scholar_level in clean env

orchestration/dags/dependencies/import_analytics/import_analytics.py, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_cultural_partner_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_local_authority_data.sql
=> Pc 24599 create enriched local authority data

orchestration/dags/dependencies/logs/sql/analytics/adage_logs.sql
=> Add new parameter adage_logs

orchestration/dags/dependencies/qualtrics/export_qualtrics_data.py, orchestration/dags/dependencies/qualtrics/sql/analytics/enriched_qualtrics_pro.sql
=> enriched_qualtrics_pro

orchestration/dags/dependencies/cold_data/sql/clean/institutional_scholar_level.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/adage_involved_student.sql
=> add level_code to adage_involved_student

jobs/etl_jobs/internal/cold-data/tables_config.py, orchestration/dags/dependencies/cold_data/sql/clean/institutional_scholar_level.sql, orchestration/dags/dependencies/import_analytics/import_analytics.py, orchestration/dags/dependencies/import_analytics/sql/analytics/adage_involved_institution.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/adage_involved_student.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/aggregated_weekly_user_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_local_authority_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_offerer_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/firebase_aggregated_search_events.sql, orchestration/dags/dependencies/import_analytics/sql/raw/offerer.sql, orchestration/dags/dependencies/logs/sql/analytics/adage_logs.sql, orchestration/dags/dependencies/training_data/sql/recommendation_user_features.sql, orchestration/dags/jobs/import/rewind_import_dms.py, orchestration/tests/data_analytics/config.py, orchestration/tests/data_analytics/data.py
=> MEP v262.0.0

orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_booking_data.sql, orchestration/tests/data_analytics/data.py
Ajoute le partner_type dans enriched_booking_data
JIRA-25261
=> PC-25261 added partner_id in enriched_booking_data

orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_booking_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_cultural_partner_data.sql, orchestration/tests/data_analytics/data.py
Cette PR corrige le fail sur enriched_cultural_partner_data en modifier le champ filtré qui avait été modifié.
JIRA-25277
=> Pc 25277 fix enriched cultural partner data

orchestration/dags/dependencies/logs/import_logs.py, orchestration/dags/dependencies/logs/sql/analytics/backoffice_logs.sql
=> Add new table to study backoffice tracking

orchestration/dags/dependencies/firebase/sql/analytics/firebase_visits.sql, orchestration/dags/dependencies/import_analytics/import_analytics.py, orchestration/dags/dependencies/import_analytics/sql/analytics/firebase_aggregated_daily_campaign_events.sql, orchestration/dags/dependencies/logs/import_logs.py, orchestration/dags/dependencies/logs/sql/analytics/backoffice_logs.sql
=> MEP v262.1.1

orchestration/dags/dependencies/logs/sql/analytics/backoffice_logs.sql
=> Anonymize email in backoffice_logs

jobs/etl_jobs/internal/export_posthog/bq.py, jobs/etl_jobs/internal/export_posthog/event.py, jobs/etl_jobs/internal/export_posthog/main.py, jobs/etl_jobs/internal/export_posthog/requirements.txt, jobs/etl_jobs/internal/export_posthog/utils.py, orchestration/dags/dependencies/export_posthog/sql/export_firebase_native_events.sql, orchestration/dags/dependencies/export_posthog/sql/export_firebase_pro_events.sql, orchestration/dags/jobs/export/export_posthog.py
This PR adds a DAG to push firebase data to posthog.
JIRA = PC-251551
=> [PC-251551](posthog) Export firebase data to posthog

orchestration/dags/dependencies/import_analytics/sql/analytics/funnel_subscription_beneficiary.sql
This PR amends age selection in firebase_subscription_beneficary_funnel to account for new tracking event
=> update selected age in subscription beneficiary

orchestration/dags/dependencies/import_analytics/sql/analytics/aggregated_weekly_user_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/firebase_aggregated_search_events.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/funnel_subscription_beneficiary.sql
…#1962)
* create firebase venue data table
* fix last filter and clean code
version: v262.3.0
=> MEP v262.3.0

orchestration/dags/dependencies/logs/sql/analytics/backoffice_logs.sql
=> update searchquery field

jobs/etl_jobs/external/appsflyer/main.py
=> [HOTFIX](appsflyer) typo fix

orchestration/dags/dependencies/propilote/sql/analytics/propilote_kpis.sql, orchestration/dags/dependencies/propilote/sql/tmp/taux_participation_eac_ecoles/propilote_tmp_participation_eac_ecoles.sql, orchestration/dags/dependencies/propilote/sql/tmp/taux_participation_eac_jeunes/propilote_tmp_participation_eac_jeunes.sql
This PR fixes the propilote kpis so the is_current_year column has the expected behaviour
=> Hotfix propilote kpis

jobs/etl_jobs/external/appsflyer/main.py, jobs/etl_jobs/internal/import_api_referentials/main.py, jobs/ml_jobs/retrieval_vector/api-requirements.txt, orchestration/dags/dependencies/propilote/sql/analytics/propilote_kpis.sql
=> MEP 263.1.0

orchestration/dags/dependencies/propilote/sql/tmp/taux_participation_eac_ecoles/propilote_tmp_participation_eac_ecoles.sql, orchestration/dags/dependencies/propilote/sql/tmp/taux_participation_eac_jeunes/propilote_tmp_participation_eac_jeunes.sql
This PR quickfix propilote tmp files.
=> quickfix tmp_eac

orchestration/dags/dependencies/propilote/sql/tmp/taux_participation_eac_ecoles/propilote_tmp_participation_eac_ecoles.sql, orchestration/dags/dependencies/propilote/sql/tmp/taux_participation_eac_jeunes/propilote_tmp_participation_eac_jeunes.sql
=> MEP 263.1.1

jobs/etl_jobs/external/appsflyer/main.py, orchestration/dags/dependencies/appsflyer/sql/analytics/appsflyer_daily_report.sql
=> [HOTFIX](appsflyer) Fix appsflyer status

jobs/ml_jobs/retrieval_vector/app/model.py
=> [HOTFIX](retrieval) Fix hnne encoding vector 

jobs/etl_jobs/external/appsflyer/main.py, jobs/ml_jobs/retrieval_vector/app/model.py, orchestration/dags/dependencies/appsflyer/sql/analytics/appsflyer_daily_report.sql
=> MEP 263.1.2

orchestration/dags/dependencies/firebase/sql/analytics/firebase_visits.sql
=> add screen view bookings to firebase visit

jobs/etl_jobs/external/qualtrics/main.py
=> (Qualtrics) Temporarly disable qualtrics ir answers for grant18

jobs/etl_jobs/external/qualtrics/main.py, orchestration/dags/dependencies/export_posthog/sql/export_firebase_native_events.sql, orchestration/dags/dependencies/firebase/sql/analytics/firebase_visits.sql, orchestration/dags/jobs/ml/algo_default_deployment.py
=> MEP 263.2.0

jobs/etl_jobs/internal/export_posthog/bq.py, orchestration/dags/jobs/export/export_posthog.py
=> MEP 263.2.1 

jobs/etl_jobs/internal/export_posthog/main.py, orchestration/dags/jobs/export/export_posthog.py
=> [DE](posthog) feat : add catchup job

orchestration/dags/dependencies/appsflyer/import_appsflyer.py, orchestration/dags/dependencies/appsflyer/sql/analytics/appsflyer_users.sql, orchestration/dags/dependencies/appsflyer/sql/clean/appsflyer_users.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/funnel_subscription_beneficiary.sql, orchestration/dags/jobs/import/import_appsflyer.py
- Updates SQL Appsflyer users to include ad / campaign etc for restricted ones based on stats we have globally. 
- Here we take only installs as input but later we will include beneficiary costs
- Moved old query to clean env
- Added costs to the query
=> [PC-25339](appsflyer) Add SQL query to include costs

jobs/etl_jobs/external/appsflyer/appsflyer.py, jobs/etl_jobs/internal/export_posthog/main.py, orchestration/dags/dependencies/appsflyer/import_appsflyer.py, orchestration/dags/dependencies/appsflyer/sql/analytics/appsflyer_users.sql, orchestration/dags/dependencies/appsflyer/sql/clean/appsflyer_users.sql, orchestration/dags/dependencies/backend/create_tables.py, orchestration/dags/dependencies/backend/sql/adage_home_playlist_local_offerers.sql, orchestration/dags/dependencies/backend/sql/adage_home_playlist_moving_offerers.sql, orchestration/dags/dependencies/backend/sql/adage_home_playlist_new_template_offers.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_collective_offer_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_institution_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/funnel_subscription_beneficiary.sql, orchestration/dags/jobs/export/export_posthog.py, orchestration/dags/jobs/import/import_appsflyer.py, orchestration/tests/data_analytics/config.py, orchestration/tests/data_analytics/data.py
=>  MEP 263.3.0

orchestration/dags/dependencies/firebase/sql/analytics/firebase_events.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/aggregated_weekly_user_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/firebase_aggregated_search_events.sql
=> MEP v263.3.1

jobs/etl_jobs/internal/export_posthog/bq.py, jobs/etl_jobs/internal/export_posthog/event.py, jobs/etl_jobs/internal/export_posthog/utils.py, orchestration/dags/dependencies/export_posthog/sql/export_firebase_native_events.sql, orchestration/dags/dependencies/export_posthog/sql/export_firebase_pro_events.sql
=> [DE](export) Add Screen views to PH

orchestration/dags/dependencies/logs/sql/analytics/adage_logs.sql
This PR replaces the origin parameters from jsonPayload.extra.adageheaderfrom to jsonPayload.extra.from (they share the same info, they don't use the first one anymore, don't know why, as usual)
- x Fix (non-breaking change which corrects expected behavior)
- x I have performed a self-review of my code
- x Fields have been snake_cased
- x I have checked my modifications don't break downstream models
=> Update origin params of adage_logs

orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_offer_data.sql, orchestration/tests/data_analytics/config.py, orchestration/tests/data_analytics/data.py
Cette PR ajoute le champ offer_description dans enriched_offer_data
=> PC-25577 ajout de offer_description dans enriched_offer_data

jobs/etl_jobs/internal/export_posthog/bq.py, jobs/etl_jobs/internal/export_posthog/event.py, jobs/etl_jobs/internal/export_posthog/utils.py, orchestration/dags/dependencies/export_posthog/sql/export_firebase_native_events.sql, orchestration/dags/dependencies/export_posthog/sql/export_firebase_pro_events.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_offer_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/funnel_subscription_beneficiary.sql, orchestration/dags/dependencies/logs/sql/analytics/adage_logs.sql, orchestration/tests/data_analytics/config.py, orchestration/tests/data_analytics/data.py
=> MEP v263.4.0

jobs/etl_jobs/external/contentful/contentful_client.py
This PR adds a type of bloc in contentful_entries table : Playlists GTL 
Tag a reviewer if necessacy  @MatthieuRipollPass
=> (PC-25073) Add GTL Playlists to contentful_entries

jobs/ml_jobs/algo_training/two_towers_model/models/match_model.py, jobs/ml_jobs/algo_training/two_towers_model/train.py
=> (reco) Improve two towers logic

jobs/ml_jobs/offline_recommendation/access_gcp_secrets.py, jobs/ml_jobs/offline_recommendation/main.py, jobs/ml_jobs/offline_recommendation/requirements.txt, jobs/ml_jobs/offline_recommendation/tests/offline_recommendation_test.py, jobs/ml_jobs/offline_recommendation/utils.py, orchestration/dags/dependencies/ml/offline_recommendation/export_to_backend.py, orchestration/dags/dependencies/ml/offline_recommendation/import_users.py, orchestration/dags/dependencies/ml/offline_recommendation/sql/export_backend/day_plus_two_after_booking.sql, orchestration/dags/dependencies/ml/offline_recommendation/sql/export_backend/first_booking.sql, orchestration/dags/dependencies/ml/offline_recommendation/sql/import/day_plus_two_after_booking.sql, orchestration/dags/dependencies/ml/offline_recommendation/sql/import/first_booking.sql, orchestration/dags/jobs/ml/offline_recommendations.py
Add script to calculate offline recommendation based on a input table: 
* v0: calculate similar offers with user_id/offer_id pair 
This PR adds the feature 
JIRA-PC-23471
=> [PC-23471] offline recommendation

jobs/etl_jobs/external/contentful/contentful_client.py, jobs/etl_jobs/external/sendinblue/main.py, jobs/etl_jobs/external/sendinblue/sendinblue_transactional.py, jobs/etl_jobs/external/sendinblue/utils.py, jobs/ml_jobs/algo_training/two_towers_model/models/match_model.py, jobs/ml_jobs/algo_training/two_towers_model/train.py, jobs/ml_jobs/offline_recommendation/access_gcp_secrets.py, jobs/ml_jobs/offline_recommendation/main.py, jobs/ml_jobs/offline_recommendation/requirements.txt, jobs/ml_jobs/offline_recommendation/tests/offline_recommendation_test.py, jobs/ml_jobs/offline_recommendation/utils.py, orchestration/dags/common/config.py, orchestration/dags/common/macros.py, orchestration/dags/dependencies/ml/offline_recommendation/export_to_backend.py, orchestration/dags/dependencies/ml/offline_recommendation/import_users.py, orchestration/dags/dependencies/ml/offline_recommendation/sql/export_backend/day_plus_two_after_booking.sql, orchestration/dags/dependencies/ml/offline_recommendation/sql/export_backend/first_booking.sql, orchestration/dags/dependencies/ml/offline_recommendation/sql/import/day_plus_two_after_booking.sql, orchestration/dags/dependencies/ml/offline_recommendation/sql/import/first_booking.sql, orchestration/dags/dependencies/sendinblue/import_sendinblue.py, orchestration/dags/dependencies/sendinblue/sql/analytics/sendinblue_transactional_performance.sql, orchestration/dags/dependencies/sendinblue/sql/clean/sendinblue_transactional.sql, orchestration/dags/dependencies/sendinblue/sql/raw/sendinblue_transactional.sql, orchestration/dags/jobs/import/import_sendinblue.py, orchestration/dags/jobs/ml/offline_recommendations.py
=> MEP 264.2.O

orchestration/dags/dependencies/import_analytics/sql/raw/offer_validation_rule.sql, orchestration/dags/dependencies/import_analytics/sql/raw/offer_validation_sub_rule.sql, orchestration/dags/dependencies/import_analytics/sql/raw/validation_rule_collective_offer_link.sql, orchestration/dags/dependencies/import_analytics/sql/raw/validation_rule_collective_offer_template_link.sql, orchestration/dags/dependencies/import_analytics/sql/raw/validation_rule_offer_link.sql
import validation rules related tables into BQ raw
JIRA-23413
=> import offer validation tables to raw

orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_offer_metadata.sql, orchestration/dags/dependencies/ml/embeddings/sql/item_to_extract_embedding.sql
This PR calls clean applicative tables in erniched_offer_metadata.
=> (hotfix) call clean dataset for applicative tables

orchestration/dags/dependencies/import_analytics/sql/analytics/recommendable_items_raw.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/recommendable_offers_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/recommendable_offers_raw.sql
=> (reco) feat: add sensitive table + change forbidden logic

orchestration/dags/dependencies/firebase/sql/analytics/firebase_bookings.sql, orchestration/dags/dependencies/firebase/sql/analytics/firebase_events.sql, orchestration/dags/dependencies/firebase/sql/analytics/firebase_home_funnel_conversion.sql, orchestration/dags/dependencies/firebase/sql/analytics/firebase_session_origin.sql, orchestration/dags/dependencies/firebase/sql/analytics/firebase_visits.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_offer_metadata.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/firebase_aggregated_search_events.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/firebase_aggregated_similar_offer_events.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/firebase_booking_origin.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/firebase_similar_offer_events.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/recommendable_items_raw.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/recommendable_offers_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/recommendable_offers_raw.sql, orchestration/dags/dependencies/import_analytics/sql/raw/offer_validation_rule.sql, orchestration/dags/dependencies/import_analytics/sql/raw/offer_validation_sub_rule.sql, orchestration/dags/dependencies/import_analytics/sql/raw/validation_rule_collective_offer_link.sql, orchestration/dags/dependencies/import_analytics/sql/raw/validation_rule_collective_offer_template_link.sql, orchestration/dags/dependencies/import_analytics/sql/raw/validation_rule_offer_link.sql, orchestration/dags/dependencies/ml/embeddings/sql/item_to_extract_embedding.sql
=> MEP v265.1.0

jobs/ml_jobs/retrieval_vector/api-requirements.txt, jobs/ml_jobs/retrieval_vector/app/model.py, jobs/ml_jobs/retrieval_vector/requirements.txt
=> (reco) feat: add prefiltering

orchestration/dags/dependencies/backend/sql/stats_display_top_3_most_consulted_offers_last_30_days.sql
=> (hotfix) stats backend query

jobs/etl_jobs/external/sendinblue/main.py, jobs/etl_jobs/external/sendinblue/sendinblue_transactional.py, orchestration/dags/dependencies/sendinblue/sql/raw/sendinblue_transactional.sql, orchestration/dags/jobs/import/import_sendinblue.py
=> (fix) update to be able to run sendinblue transtional historical

jobs/etl_jobs/external/gsheet/gsheet.py, jobs/etl_jobs/external/gsheet/main.py, orchestration/dags/dependencies/export_cloudsql_tables_to_bigquery/import_cloudsql.py, orchestration/dags/dependencies/export_cloudsql_tables_to_bigquery/sql/clean/past_offer_context.sql, orchestration/dags/dependencies/export_cloudsql_tables_to_bigquery/sql/raw/past_offer_context.sql
=> Update past_offers + sensitive offers

jobs/etl_jobs/external/gsheet/gsheet.py, jobs/etl_jobs/external/gsheet/main.py, orchestration/dags/dependencies/export_cloudsql_tables_to_bigquery/import_cloudsql.py, orchestration/dags/dependencies/export_cloudsql_tables_to_bigquery/sql/clean/past_offer_context.sql, orchestration/dags/dependencies/export_cloudsql_tables_to_bigquery/sql/raw/past_offer_context.sql
=> MEP v266.0.0

orchestration/dags/dependencies/import_analytics/import_analytics.py, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_local_authority_data.sql
Cette PR enrichie la table enriched_local_authority_data
JIRA-25791
=> PC-25791 enriched_local_authority_data v2

jobs/ml_jobs/retrieval_vector/app/app.py, jobs/ml_jobs/retrieval_vector/app/model.py
Please include a summary of the changes: Change the search metric for retrieval to 'dot' instead of 'L2' 
This PR replaces the feature
Tag a reviewer if necessacy  @github/username
=> (reco)(update) retrieval search metric

jobs/ml_jobs/retrieval_vector/app/app.py, jobs/ml_jobs/retrieval_vector/app/model.py, orchestration/dags/dependencies/firebase/sql/analytics/firebase_events.sql, orchestration/dags/dependencies/import_analytics/import_analytics.py, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_local_authority_data.sql
=> MEP v267.0.0

orchestration/dags/dependencies/backend/create_tables.py, orchestration/dags/dependencies/backend/sql/stats_display_top_3_most_consulted_offers_last_30_days.sql
=> MEP v267.1.0

orchestration/dags/dependencies/backend/create_tables.py, orchestration/dags/dependencies/backend/sql/booking_per_ean_last_30_days.sql
=> Create backend table booking_per_ean_last_30_days

orchestration/dags/jobs/ml/embedding_extraction_items.py
=> embedding-extraction-reduce-batch-size

orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_collective_offer_data.sql, orchestration/dags/dependencies/import_analytics/sql/raw/collective_offer.sql, orchestration/dags/dependencies/import_analytics/sql/raw/collective_offer_template.sql, orchestration/tests/data_analytics/config.py, orchestration/tests/data_analytics/data.py
=> Add format in collective offer tables

jobs/etl_jobs/external/dms/utils.py
Please include a summary of the changes: Rajouter à l'import les procédures DMS pro 'fermé' mais pas archivé
=> [rollback-dms-closed-procedure-deletion]

jobs/etl_jobs/external/dms/utils.py, orchestration/dags/dependencies/backend/create_tables.py, orchestration/dags/dependencies/backend/sql/booking_per_ean_last_30_days.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_collective_offer_data.sql, orchestration/dags/dependencies/import_analytics/sql/raw/collective_offer.sql, orchestration/dags/dependencies/import_analytics/sql/raw/collective_offer_template.sql, orchestration/dags/jobs/ml/embedding_extraction_items.py, orchestration/tests/data_analytics/config.py, orchestration/tests/data_analytics/data.py
=> MEP v_267.2.0

orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_collective_booking_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_collective_offer_data.sql, orchestration/dags/dependencies/import_analytics/sql/raw/collective_offer.sql, orchestration/dags/dependencies/import_analytics/sql/raw/collective_offer_template.sql, orchestration/tests/data_analytics/config.py, orchestration/tests/data_analytics/data.py
=> Add format to collective booking

jobs/ml_jobs/ranking_endpoint/app/app.py, jobs/ml_jobs/ranking_endpoint/app/model.py
=> (reco) fix: Fail Silently

orchestration/dags/dependencies/import_analytics/sql/raw/collective_offer.sql, orchestration/dags/dependencies/import_analytics/sql/raw/collective_offer_template.sql
=> update raw collective_offer and collective_offer_template

orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_user_offerer.sql
=> Exclude deactivated users from enriched_user_offerer

jobs/ml_jobs/ranking_endpoint/deploy_model.py, jobs/ml_jobs/ranking_endpoint/figure.py, jobs/ml_jobs/ranking_endpoint/requirements.txt
=> (reco) feat: ranking / add more metrics + keep base objective

jobs/ml_jobs/retrieval_vector/app/app.py, jobs/ml_jobs/retrieval_vector/app/model.py
=> (retrieval) Add vector_column_name

jobs/ml_jobs/retrieval_vector/app/app.py, jobs/ml_jobs/retrieval_vector/app/model.py
=> MEP v268.1.0 

orchestration/dags/dependencies/firebase/sql/analytics/firebase_pro_events.sql
(waiting for review to update schema in BQ)
=> Add new fields in firebase_pro_events 

orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_offerer_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_suivi_dms_adage.sql, orchestration/tests/data_analytics/config.py, orchestration/tests/data_analytics/data.py
=> enriched_suivi_dms_adage updated

orchestration/dags/dependencies/backend/sql/stats_display_top_3_most_consulted_offers_last_30_days.sql
be consistent in dates intervals with table  stats_display_cum_daily_consult_per_offerer_last_180_days
=> (fix) decalage dates stats backend

orchestration/dags/dependencies/backend/sql/stats_display_top_3_most_consulted_offers_last_30_days.sql, orchestration/dags/dependencies/firebase/sql/analytics/firebase_pro_events.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_offerer_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_suivi_dms_adage.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_venue_provider_data.sql, orchestration/tests/data_analytics/config.py, orchestration/tests/data_analytics/data.py
=> MEP v268.2.0

orchestration/dags/dependencies/backend/create_tables.py, orchestration/dags/dependencies/backend/sql/adage_home_playlist_local_offerers.sql, orchestration/dags/dependencies/backend/sql/adage_home_playlist_moving_offerers.sql
=> MEP v269.0.0

orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_collective_booking_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_reimbursement_data.sql, orchestration/dags/dependencies/import_analytics/sql/clean/applicative_database/collective_booking_history.sql
=> (fix) remove dependencies with booking id in collective booking tables

jobs/ml_jobs/ranking_endpoint/deploy_model.py, orchestration/dags/dependencies/import_analytics/sql/analytics/non_recommendable_items_data.sql, orchestration/dags/dependencies/training_data/sql/ranking_endpoint_training_data.sql
=> MEP v269.1.1 

jobs/etl_jobs/external/gsheet/gsheet.py
=> (fix) remove empty rows in raw table gsheet_eac_webinar

orchestration/dags/dependencies/import_analytics/import_analytics.py, orchestration/dags/dependencies/import_analytics/sql/analytics/partner_type_bookability_frequency.sql
=> PC-26262 created partner_type_bookability_frequency

orchestration/dags/dependencies/import_analytics/sql/analytics/eple_aggregated.sql
=> correction institution_deposit_amount

jobs/etl_jobs/external/gsheet/gsheet.py, jobs/etl_jobs/internal/cold-data/tables_config.py, orchestration/dags/common/access_gcp_secrets.py, orchestration/dags/dependencies/cold_data/import_cold_data.py, orchestration/dags/dependencies/cold_data/sql/clean/iris_france.sql, orchestration/dags/dependencies/import_analytics/import_analytics.py, orchestration/dags/dependencies/import_analytics/import_clean.py, orchestration/dags/dependencies/import_analytics/sql/analytics/eple_aggregated.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/user_iris_per_month.sql, orchestration/dags/dependencies/import_analytics/sql/clean/user_declared_iris.sql, orchestration/dags/dependencies/import_analytics/sql/clean/user_ip_iris.sql, orchestration/dags/dependencies/import_analytics/sql/clean/user_reco_iris.sql
=> MEP v269.2.1

jobs/etl_jobs/external/sendinblue/sendinblue_transactional.py, orchestration/dags/dependencies/sendinblue/import_sendinblue.py, orchestration/dags/dependencies/sendinblue/sql/raw/sendinblue_transactional.sql, orchestration/dags/jobs/import/import_sendinblue_historical.py
=> Create dag to compute historical transactional data

orchestration/dags/dependencies/import_analytics/sql/analytics/user_iris_per_month.sql
=> fix log error on user_iris_per_month dag

jobs/ml_jobs/clusterisation/requirements.txt, orchestration/dags/dependencies/backend/sql/adage_home_playlist_local_offerers.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/user_iris_per_month.sql
=> MEP v269.3.1

orchestration/dags/dependencies/import_analytics/sql/analytics/non_recommendable_items_data.sql, orchestration/dags/dependencies/training_data/sql/retrieval_semantic_vector.sql, orchestration/dags/jobs/dbt/dbt_dag_run.py
=> MEP v270.0.0

orchestration/dags/common/config.py, orchestration/dags/common/dbt/manifest.py, orchestration/dags/jobs/dbt/dbt_dag_run.py
=> (dbt) change target path in gcs

orchestration/dags/dependencies/import_analytics/import_analytics.py, orchestration/dags/dependencies/import_analytics/import_clean.py
=> incremental in import_analytics and import_clean

orchestration/dags/dependencies/import_analytics/sql/analytics/user_iris_per_month.sql
=> Fix most_freq_iris is null

orchestration/dags/data_gcp_dbt/dbt_project.yml, orchestration/dags/data_gcp_dbt/dbt_run.sh, orchestration/dags/data_gcp_dbt/dbt_test.sh, orchestration/dags/jobs/dbt/dbt_dag_run.py
=> (dbt) add target-path config to dbt run commands

orchestration/dags/dependencies/import_analytics/sql/analytics/user_iris_per_month.sql
=> modification user_iris_per_month

orchestration/dags/dependencies/import_analytics/sql/analytics/user_iris_per_month.sql
=> quickfix most_freq_department

orchestration/dags/dependencies/logs/sql/analytics/adage_logs.sql
=> add new parameters concerning adage playlists

orchestration/dags/jobs/api/export_cloudsql_tables_to_bigquery.py
=> (reco) :fix update import dag with tmp tables

jobs/ml_jobs/ranking_endpoint/app/model.py, jobs/ml_jobs/ranking_endpoint/deploy_model.py, orchestration/dags/dependencies/training_data/sql/ranking_endpoint_training_data.sql
=> (ranking) Add context to ranking + fix sql

orchestration/dags/jobs/api/export_cloudsql_tables_to_bigquery.py
=> (fix) reco tables : fix destination dataset to tmp

jobs/ml_jobs/retrieval_vector/app/app.py, orchestration/dags/jobs/ml/retrieval_vector_semantic_build.py
=> (retrieval) :feat add similarity metric as input

orchestration/dags/data_gcp_dbt/dbt_project.yml
=> (dbt) configure specific dbt schema for raw zone

jobs/ml_jobs/record_linkage/main.py, jobs/ml_jobs/record_linkage/postprocess.py, jobs/ml_jobs/record_linkage/tools/config.py, jobs/ml_jobs/record_linkage/tools/linkage.py
Fix empty case handling
This PR fixes the feature
=> [ML](item linkage) improve empty case handling

jobs/ml_jobs/ranking_endpoint/app/model.py, jobs/ml_jobs/record_linkage/main.py, jobs/ml_jobs/record_linkage/postprocess.py, jobs/ml_jobs/record_linkage/tools/config.py, jobs/ml_jobs/record_linkage/tools/linkage.py, jobs/ml_jobs/retrieval_vector/app/app.py, orchestration/dags/data_gcp_dbt/dbt_project.yml, orchestration/dags/jobs/api/recommendation_cloud_sql.py, orchestration/dags/jobs/ml/retrieval_vector_semantic_build.py
=> MEP v271.2.0

orchestration/dags/common/alerts.py, orchestration/dags/common/dbt/utils.py, orchestration/dags/dependencies/import_analytics/import_analytics.py, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_partner_retention_data.sql
This PR crée la table enriched_partner_retention_data 
JIRA-26443
=> PC-26443 enriched_partner_retention_data creation

orchestration/dags/dependencies/import_analytics/sql/raw/venue.sql
- Ajout du champ id BAN dans les imports de Venue pour y accéder depuis métabase
- Lié au ticket Jira 25824
=> (PC-25824) import BAN ID (id at Base Adresse Nationale)

orchestration/dags/jobs/import/import_sendinblue_historical.py
=> (sendinblue historical) change schedule time

orchestration/dags/data_gcp_dbt/macros/udf_js/dehumanize_id_function.sql, orchestration/dags/data_gcp_dbt/macros/udf_js/humanize_id_function.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_collective_offer_data.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_offer_data.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_offerer_data.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_venue_data.sql
=> (dbt) fix javascript function call in bq

jobs/etl_jobs/internal/export_posthog/bq.py, jobs/etl_jobs/internal/export_posthog/event.py, jobs/ml_jobs/ranking_endpoint/deploy_model.py, jobs/ml_jobs/retrieval_vector/app/model.py, jobs/ml_jobs/retrieval_vector/utils.py, orchestration/dags/data_gcp_dbt/macros/udf_js/dehumanize_id_function.sql, orchestration/dags/data_gcp_dbt/macros/udf_js/humanize_id_function.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_collective_offer_data.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_offer_data.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_offerer_data.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_venue_data.sql, orchestration/dags/dependencies/export_cloudsql_tables_to_bigquery/sql/clean/past_offer_context.sql, orchestration/dags/dependencies/export_cloudsql_tables_to_bigquery/sql/clean/past_recommended_offers.sql, orchestration/dags/dependencies/export_cloudsql_tables_to_bigquery/sql/clean/past_similar_offers.sql, orchestration/dags/dependencies/training_data/sql/ranking_endpoint_training_data.sql, orchestration/dags/jobs/import/import_sendinblue_historical.py
=> MEP v272.0.0 

orchestration/dags/jobs/api/recommendation_cloud_sql.py, orchestration/dags/jobs/import/import_analytics.py
=> import misc fixes

orchestration/dags/dependencies/export_cloudsql_tables_to_bigquery/sql/clean/past_similar_offers.sql, orchestration/dags/dependencies/training_data/sql/ranking_endpoint_training_data.sql, orchestration/dags/jobs/api/recommendation_cloud_sql.py, orchestration/dags/jobs/import/import_analytics.py
=> MEP v272.1.0 

jobs/ml_jobs/retrieval_vector/utils.py
=> MEP v272.0.2 

orchestration/dags/data_gcp_dbt/dbt_project.yml, orchestration/dags/data_gcp_dbt/packages.yml, orchestration/dags/data_gcp_dbt/profiles.yml
=> (dbt) re_data data quality tool

orchestration/dags/dependencies/import_analytics/sql/raw/product.sql
This PR adds new columns to product export
=> (BSR) Add new columns to product import

orchestration/dags/dependencies/export_cloudsql_tables_to_bigquery/import_cloudsql.py, orchestration/dags/dependencies/export_cloudsql_tables_to_bigquery/sql/clean/past_recommended_offers.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/firebase_recommendation_events.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/user_iris_per_month.sql, orchestration/dags/dependencies/import_analytics/sql/clean/user_reco_iris.sql
=> (analytics) Improve past_recommended_offers

orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_partner_retention_data.sql
=> modification enriched_partner_retention

jobs/ml_jobs/retrieval_vector/app/model.py, jobs/ml_jobs/retrieval_vector/utils.py, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_item_metadata.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/recommendable_items_raw.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/recommendable_offers_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/recommendable_offers_raw.sql
=> (retrieval) :reco Add new fields to retrieval 

jobs/ml_jobs/retrieval_vector/app/model.py, jobs/ml_jobs/retrieval_vector/utils.py, orchestration/dags/data_gcp_dbt/dbt_project.yml, orchestration/dags/data_gcp_dbt/packages.yml, orchestration/dags/dependencies/export_cloudsql_tables_to_bigquery/import_cloudsql.py, orchestration/dags/dependencies/export_cloudsql_tables_to_bigquery/sql/clean/past_recommended_offers.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_item_metadata.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_partner_retention_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/firebase_recommendation_events.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/recommendable_items_raw.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/recommendable_offers_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/recommendable_offers_raw.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/user_iris_per_month.sql, orchestration/dags/dependencies/import_analytics/sql/clean/user_reco_iris.sql, orchestration/dags/dependencies/import_analytics/sql/raw/product.sql, orchestration/dags/jobs/export/export_posthog.py
=> MEP v272.1.0

orchestration/dags/dependencies/backend/create_tables.py, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_item_metadata.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/firebase_recommendation_events.sql
=> MEP v272.1.1

orchestration/dags/dependencies/export_cloudsql_tables_to_bigquery/sql/clean/past_offer_context.sql, orchestration/dags/dependencies/export_cloudsql_tables_to_bigquery/sql/clean/past_recommended_offers.sql, orchestration/dags/dependencies/export_cloudsql_tables_to_bigquery/sql/clean/past_similar_offers.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/firebase_recommendation_events.sql
=> MEP v272.1.2

jobs/ml_jobs/clusterisation/topics/generate.py, jobs/ml_jobs/retrieval_vector/utils.py, orchestration/dags/dependencies/import_analytics/sql/clean/user_reco_iris.sql, orchestration/dags/dependencies/import_analytics/sql/raw/product.sql, orchestration/dags/jobs/import/import_analytics.py
=> MEP v272.2.0

orchestration/dags/dependencies/import_analytics/sql/analytics/recommendable_items_raw.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/user_iris.sql
=> MEP v272.2.1

orchestration/dags/dependencies/import_analytics/sql/analytics/firebase_recommendation_events.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/recommendable_items_raw.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/user_iris.sql
=>  MEP v272.2.2

orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_partner_retention_data.sql
=> PC-26618-correction-enriched-retention-partner-data

jobs/ml_jobs/retrieval_vector/app/model.py, jobs/ml_jobs/retrieval_vector/utils.py
=> (reco) fix retrieval

orchestration/dags/dependencies/import_recommendation_cloudsql/sql/create_recommendable_offers_raw_mv.sql
=> (reco) Simplify Recommendable Offer Raw mv

orchestration/dags/dependencies/views/sql/analytics/backend_events.sql
=> add fields about stock modification logs to backend_events

orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_partner_retention_data.sql
=> add consultation and adage_status

orchestration/dags/dependencies/import_analytics/sql/clean/applicative_database/collective_offer_template_history.sql
=> add fields in collective_offer_template_history

orchestration/dags/jobs/ml/embedding_extraction_items.py
Fix tables name inputs 
This PR fixes the bug
=> [ML](embedding extraction) fix ehp tables 

jobs/ml_jobs/clusterisation/cluster/generate.py, jobs/ml_jobs/clusterisation/cluster/preprocess.py, jobs/ml_jobs/clusterisation/configs/default-config.json, jobs/ml_jobs/clusterisation/tools/preprocessing.py, jobs/ml_jobs/clusterisation/topics/clean.py, jobs/ml_jobs/clusterisation/topics/generate.py, jobs/ml_jobs/embeddings/dimension_reduction.py, jobs/ml_jobs/embeddings/main.py, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_item_metadata.sql, orchestration/dags/dependencies/ml/clusterisation/sql/import_item_embeddings.sql
=> (ml) Fix reduce embeddings batch + clustering logic

jobs/ml_jobs/clusterisation/cluster/generate.py, jobs/ml_jobs/clusterisation/cluster/preprocess.py, jobs/ml_jobs/clusterisation/configs/default-config.json, jobs/ml_jobs/clusterisation/tools/preprocessing.py, jobs/ml_jobs/clusterisation/topics/clean.py, jobs/ml_jobs/clusterisation/topics/generate.py, jobs/ml_jobs/embeddings/dimension_reduction.py, jobs/ml_jobs/embeddings/main.py, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_item_metadata.sql, orchestration/dags/dependencies/ml/clusterisation/sql/import_item_embeddings.sql
=> MEP 272.4.2

orchestration/dags/dependencies/import_analytics/sql/clean/applicative_database/collective_offer_template_history.sql
=> fix ambiguous field

jobs/etl_jobs/external/adage/scripts/utils.py
=> cast synchropass as STRING

orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_offerer_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_suivi_dms_adage.sql, orchestration/tests/data_analytics/data.py
=> fix synchropass in enriched_offerer_data and enriched_suivi_dms_adage

orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_offerer_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_suivi_dms_adage.sql, orchestration/dags/dependencies/import_analytics/sql/raw/collective_offer_template.sql, orchestration/tests/data_analytics/config.py, orchestration/tests/data_analytics/data.py
=> MEP v273.2.0

.github/workflows/base_workflow.yml, .github/workflows/deploy_composer.yml, .github/workflows/reusable_deploy_composer.yml, .github/workflows/reusable_job_test.yml, .github/workflows/reusable_linter.yml, .github/workflows/reusable_test_orchestration.yml
=> (PC-26704) ci: do not use self-hosted runners

orchestration/dags/dependencies/import_analytics/sql/analytics/adage_involved_institution.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/adage_involved_student.sql
=> remove NaN values from adage_involved tables

.github/workflows/reusable_deploy_composer.yml, .github/workflows/reusable_test_orchestration.yml
=> (BSR) ci: fix secret path

jobs/ml_jobs/clusterisation/cluster/generate.py, jobs/ml_jobs/clusterisation/cluster/preprocess.py, jobs/ml_jobs/clusterisation/configs/default-config.json, jobs/ml_jobs/clusterisation/tools/clusterisation.py, jobs/ml_jobs/clusterisation/tools/utils.py, jobs/ml_jobs/clusterisation/topics/clean.py, jobs/ml_jobs/clusterisation/topics/generate.py, jobs/ml_jobs/embeddings/configs/default-config-item.json, jobs/ml_jobs/embeddings/dimension_reduction.py, jobs/ml_jobs/embeddings/main.py, jobs/ml_jobs/embeddings/requirements.txt, jobs/ml_jobs/embeddings/tools/dimension_reduction.py, orchestration/dags/dependencies/ml/clusterisation/sql/import_item_embeddings.sql, orchestration/dags/dependencies/training_data/sql/recommendation_item_features.sql, orchestration/dags/jobs/ml/clusterisation_items.py, orchestration/dags/jobs/ml/embedding_extraction_items.py
=> (item embeddings) fix item reductions

orchestration/dags/dependencies/import_analytics/sql/analytics/adage_involved_institution.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/adage_involved_student.sql
=> remove NaN Float values

jobs/etl_jobs/external/batch/requirements.txt, jobs/etl_jobs/external/downloads/requirements.txt, jobs/etl_jobs/external/gsheet/requirements.txt, jobs/etl_jobs/external/notion/requirements.txt, jobs/etl_jobs/external/qualtrics/requirements.txt, jobs/etl_jobs/internal/export_posthog/requirements.txt, jobs/ml_jobs/algo_training/requirements.txt
This PR does what it's title says
=> latest numpy version and above for all

.github/workflows/reusable_deploy_composer.yml, .github/workflows/reusable_test_orchestration.yml
=> MEP v273.3.1

orchestration/dags/dependencies/backend/sql/marketing_pro_email_churned_40_days_ago.sql
=> Exclude venues without booking email from marketing listing

orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_partner_retention_data.sql
=> add indicator on since_last_bookable_offer

orchestration/dags/common/dbt/utils.py
=> (dbt) fix dict call to build manifest

orchestration/dags/dependencies/import_analytics/import_clean.py, orchestration/dags/dependencies/import_analytics/sql/clean/collective_offer_domain_name.sql
=> create collective_offer_domain_name in clean

orchestration/dags/dependencies/import_analytics/sql/analytics/user_penetration.sql
=> include 2024 in user_penetration

orchestration/dags/dependencies/import_analytics/sql/clean/applicative_database/venue_history.sql
=> add new fields venue_history

orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_venue_provider_data.sql, orchestration/dags/dependencies/import_analytics/sql/clean/applicative_database/venue_history.sql
=> MEP v274.2.0

orchestration/dags/dependencies/import_analytics/import_analytics.py, orchestration/dags/dependencies/import_analytics/sql/analytics/collective_offer_domain_name.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/user_penetration.sql
=> Pc 27009 create collective offer domain name in analytics

orchestration/dags/data_gcp_dbt/dbt_project.yml, orchestration/dags/jobs/dbt/dbt_artifacts.py, orchestration/dags/jobs/dbt/dbt_dag_run.py
=> (dbt) fix dags

orchestration/dags/dependencies/import_analytics/sql/raw/product.sql, orchestration/tests/data_analytics/config.py
=> Add ean fields to product table

jobs/ml_jobs/retrieval_vector/app/app.py, jobs/ml_jobs/retrieval_vector/app/model.py, jobs/ml_jobs/retrieval_vector/utils.py, orchestration/dags/dependencies/import_analytics/sql/analytics/recommendable_items_raw.sql, orchestration/dags/jobs/ml/clusterisation_items.py
=> (reco) Add trends for retrieval

jobs/ml_jobs/retrieval_vector/app/app.py, jobs/ml_jobs/retrieval_vector/app/model.py, jobs/ml_jobs/retrieval_vector/utils.py, orchestration/dags/dependencies/import_analytics/sql/analytics/recommendable_items_raw.sql, orchestration/dags/dependencies/import_analytics/sql/clean/user_ip_iris.sql, orchestration/dags/dependencies/import_analytics/sql/raw/product.sql, orchestration/dags/jobs/ml/algo_training.py, orchestration/dags/jobs/ml/clusterisation_items.py, orchestration/tests/data_analytics/config.py
=> MEP 275.0.0

orchestration/dags/jobs/dbt/dbt_init.py
=> (dbt) remove run re_data from init & add sleep task

orchestration/dags/dependencies/contentful/sql/analytics/enriched_contentful_home_tags.sql
=> Clean tags in enriched_contentful_home_tags.sql

orchestration/dags/dependencies/contentful/sql/analytics/enriched_contentful_playlist_tags.sql
=> Clean tags in enriched_contentful_playlist_tags.sql

orchestration/dags/dependencies/contentful/sql/analytics/enriched_contentful_home_tags.sql, orchestration/dags/dependencies/contentful/sql/analytics/enriched_contentful_playlist_tags.sql, orchestration/dags/jobs/dbt/dbt_init.py
=> MEP v274.1.0

orchestration/dags/common/hooks/gce.py, orchestration/dags/common/operators/gce.py, orchestration/dags/launch_vm.py
This PR sets playground vm default parameters
@github/cdelabre
JIRA-25946
=> JIRA-25946 - Playground vm default params

orchestration/dags/common/hooks/gce.py
=> contextmanager failure removal

orchestration/dags/dbt-requirements.txt
=> Dbt fix requirements

orchestration/dags/data_gcp_dbt/scripts/dbt_manifest.sh, orchestration/dags/data_gcp_dbt/scripts/dbt_run.sh, orchestration/dags/data_gcp_dbt/scripts/dbt_run_package.sh, orchestration/dags/data_gcp_dbt/scripts/dbt_test.sh, orchestration/dags/data_gcp_dbt/scripts/dbt_test_model.sh, orchestration/dags/jobs/dbt/dbt_artifacts.py, orchestration/dags/jobs/dbt/dbt_dag_run.py, orchestration/dags/jobs/dbt/dbt_init.py
=> (dbt) add env_short_name vars flag in cli commands

orchestration/dags/jobs/import/import_analytics.py, orchestration/dags/jobs/import/import_raw.py
=> (import_analytics) extract raw from dag analytics

orchestration/dags/dependencies/firebase/import_firebase.py, orchestration/dags/dependencies/firebase/sql/clean/firebase_pro_visits.sql, orchestration/dags/dependencies/import_analytics/import_clean.py
This PR move firebase pro visits from import analytics dag
=> move firebase pro visits from import analytics dag

orchestration/dags/data_gcp_dbt/dbt_project.yml, orchestration/dags/data_gcp_dbt/macros/audit/compare_relations.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_collective_offer_data.sql, orchestration/dags/data_gcp_dbt/tests/audit/analytics/enriched/enriched_collective_offer_data_test.sql, orchestration/dags/data_gcp_dbt/tests/audit/analytics/enriched/enriched_cultural_partner_data_test.sql, orchestration/dags/data_gcp_dbt/tests/audit/analytics/enriched/enriched_offer_data_test.sql, orchestration/dags/data_gcp_dbt/tests/audit/analytics/enriched/enriched_offerer_data_test.sql, orchestration/dags/data_gcp_dbt/tests/audit/analytics/enriched/enriched_offerer_tags_data_test.sql, orchestration/dags/data_gcp_dbt/tests/audit/analytics/enriched/enriched_venue_data_test.sql, orchestration/dags/data_gcp_dbt/tests/audit/analytics/enriched/enriched_venue_tags_data_test.sql, orchestration/dags/data_gcp_dbt/tests/audit/clean/available_stock_test.sql, orchestration/dags/data_gcp_dbt/tests/audit/clean/bookable_collective_offer_test.sql, orchestration/dags/data_gcp_dbt/tests/audit/clean/bookable_offer_test.sql, orchestration/dags/data_gcp_dbt/tests/audit/clean/booking_test.sql, orchestration/dags/data_gcp_dbt/tests/audit/clean/cleaned_stock_test.sql, orchestration/dags/data_gcp_dbt/tests/audit/clean/collective_offer_domain_name_test.sql, orchestration/dags/data_gcp_dbt/tests/audit/clean/educational_institution_test.sql, orchestration/dags/data_gcp_dbt/tests/audit/clean/isbn_rayon_editor_test.sql, orchestration/dags/data_gcp_dbt/tests/audit/clean/offer_extracted_data_test.sql, orchestration/dags/data_gcp_dbt/tests/audit/clean/offer_item_ids_test.sql, orchestration/dags/data_gcp_dbt/tests/audit/clean/offer_test.sql, orchestration/dags/data_gcp_dbt/tests/audit/clean/user_beneficiary_test.sql, orchestration/dags/data_gcp_dbt/tests/audit/clean/user_declared_iris_test.sql, orchestration/dags/data_gcp_dbt/tests/audit/clean/user_ip_iris_test.sql, orchestration/dags/data_gcp_dbt/tests/audit/clean/user_reco_iris_test.sql, orchestration/dags/data_gcp_dbt/tests/audit/clean/user_suspension_test.sql, orchestration/dags/data_gcp_dbt/tests/audit/clean/venue_test.sql, orchestration/dags/dbt-requirements.txt
=> (dbt) setup audit tests for clean and enriched

orchestration/dags/dependencies/firebase/import_firebase.py, orchestration/dags/dependencies/firebase/sql/clean/firebase_pro_visits.sql, orchestration/dags/dependencies/import_analytics/import_clean.py
=> move firebase pro visits from import analytics dag to firebase dag

orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_collective_booking_data.sql, orchestration/tests/data_analytics/data.py
=> add partner_id to enriched_collective_booking_date

orchestration/dags/dependencies/logs/sql/analytics/adage_logs.sql
=> add field rank to adage_logs

orchestration/dags/data_gcp_dbt/scripts/dbt_run.sh, orchestration/dags/jobs/dbt/dbt_dag_run.py
**Dans le dag dbt_dag_run, les jobs fail lorsqu'éxécutés en // avec l'erreeur : "manifest.json not found"
=> un dbt run réécrit dans le manifest.json le rendant indisponible pour d'autres tâches qui s'éxécutent en même temps que la réécriture du manifets
=> ajouter le flag --no-write-json en faisant un dbt run** 
=> (dbt airflow) add no write json to fix dag

jobs/etl_jobs/internal/import_api_referentials/main.py
Please include a summary of the changes: Update method to import movie types 
This PR fixes the bug
=> [update] pcapi referential: movie-type

orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_partner_retention_data.sql
=> update field partner_id

orchestration/dags/data_gcp_dbt/dbt_project.yml
disable re_data and elementary to avoid random fails in airflow 
Tag a reviewer if necessacy  @valoumiaou 
=> (dbt) disable re_data and elementary

orchestration/dags/dependencies/firebase/import_firebase.py, orchestration/dags/dependencies/firebase/sql/analytics/firebase_pro_visits.sql
=> Add firebase_pro_visits in analytics env

orchestration/dags/jobs/api/export_cloudsql_tables_to_bigquery.py
Please include a summary of the changes: 
Update RECO DB export to BQ -> db instance name is now retrieve from a gcp secret
This PR adds the feature
=> [reco] export to BQ

orchestration/dags/data_gcp_dbt/models/clean/bookable_collective_offer_history.sql, orchestration/dags/data_gcp_dbt/models/clean/bookable_offer_history.sql, orchestration/dags/dependencies/firebase/import_firebase.py, orchestration/dags/dependencies/firebase/sql/analytics/firebase_pro_visits.sql
=> Hotfix firebase pro visits partitioning

orchestration/airflow/orchestration-requirements.txt, orchestration/dags/common/operators/gce.py
=> add urllib3 to install script

orchestration/dags/common/dbt/utils.py, orchestration/dags/data_gcp_dbt/.gitignore, orchestration/dags/jobs/dbt/dbt_dag_run.py, orchestration/dags/jobs/dbt/dbt_dynamic_dag.py, orchestration/dags/jobs/dbt/dbt_dynamic_dag_2.py
=> Refacto dbt dags

orchestration/dags/data_gcp_dbt/models/clean/bookable_collective_offer_history.sql, orchestration/dags/dependencies/import_analytics/import_clean.py, orchestration/dags/jobs/import/import_analytics.py
=> (legacy) remove applicative clean copy in legacy code

orchestration/dags/common/config.py, orchestration/dags/jobs/api/export_cloudsql_tables_to_bigquery.py
Unify connection to BQ method
This PR fixes the feature
=> [fix] reco to BQ connection discrepancies

orchestration/dags/data_gcp_dbt/dbt_project.yml, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_venue_data.yml, orchestration/dags/data_gcp_dbt/models/clean/bookable_offer_history.sql, orchestration/dags/dependencies/firebase/sql/analytics/firebase_pro_visits.sql
=> Hotfix conflicts master

orchestration/dags/dependencies/firebase/import_firebase.py, orchestration/dags/dependencies/firebase/sql/clean/firebase_pro_visits.sql
=> fix firebase pro visits partitions

orchestration/dags/data_gcp_dbt/dbt_project.yml, orchestration/dags/data_gcp_dbt/scripts/dbt_run_tag.sh, orchestration/dags/jobs/dbt/dbt_dag_run.py, orchestration/dags/jobs/dbt/dbt_monthly_tables.py, orchestration/dags/jobs/dbt/dbt_weekly_tables.py
This PR adds weekly and monthly table runs
=> Non daily dbt dags

orchestration/dags/dependencies/import_analytics/sql/analytics/adage_involved_student.sql
=> Pc 27981 regrouper les niveaux deducation par college lycee

orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_venue_provider_data.sql
=> Update offer fields of enriched_venue_provider_data

orchestration/dags/dependencies/import_analytics/sql/raw/favorite.sql, orchestration/tests/data_analytics/config.py
=> (applicative) remove mediationId from favorite table

orchestration/dags/jobs/dbt/dbt_dag_run.py, orchestration/dags/jobs/dbt/dbt_monthly_tables.py, orchestration/dags/jobs/dbt/dbt_weekly_tables.py
=> (hotfix) set dbt dag at 1am to enable waiting tasks

orchestration/dags/jobs/dbt/dbt_dag_run.py
=> end task trigger set to none failed

orchestration/dags/jobs/dbt/dbt_artifacts.py, orchestration/dags/jobs/dbt/dbt_init.py
=> hotFix dbt run follow-up dags at 1am

jobs/etl_jobs/external/qualtrics/main.py, jobs/etl_jobs/external/qualtrics/qualtrics_survey_answers.py
=> (qualtrics) reactivate import for grant_18

orchestration/dags/dependencies/qualtrics/export_qualtrics_data.py
=> fix import_analytics dag name in export qualtric dependencies

orchestration/dags/jobs/dbt/dbt_dag_run.py
=> MEP v280.0.1

orchestration/dags/jobs/dbt/dbt_monthly_tables.py, orchestration/dags/jobs/dbt/dbt_weekly_tables.py
=> (dbt weekly monthly) add dbt working dir & remove unused lib import

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_monthly_bookable_item_discoverability.sql, orchestration/dags/data_gcp_dbt/scripts/dbt_test.sh, orchestration/dags/jobs/dbt/dbt_artifacts.py, orchestration/dags/jobs/dbt/dbt_dag_run.py
=> (fix) exclusion tests & partition filter

orchestration/dags/data_gcp_dbt/dbt_project.yml, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_monthly_bookable_item_discoverability.sql, orchestration/dags/data_gcp_dbt/models/analytics/firebase/firebase_daily_offer_consultation_data.sql, orchestration/dags/data_gcp_dbt/models/clean/bookable_offer_history.sql, orchestration/dags/data_gcp_dbt/scripts/dbt_test.sh, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_booking_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_deposit_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_item_metadata.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_offer_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_offerer_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_reimbursement_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_user_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_venue_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/firebase_booking_origin.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/non_recommendable_offers_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/offer_moderation.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/recommendable_offers_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/stock_booking_information.sql, orchestration/dags/dependencies/qualtrics/sql/analytics/enriched_qualtrics_pro.sql, orchestration/dags/jobs/dbt/dbt_artifacts.py, orchestration/dags/jobs/dbt/dbt_dag_run.py, orchestration/dags/jobs/dbt/dbt_monthly_tables.py, orchestration/dags/jobs/dbt/dbt_weekly_tables.py, orchestration/tests/data_analytics/config.py, orchestration/tests/data_analytics/data.py
=> MEP v280.1.0

orchestration/dags/dependencies/firebase/sql/analytics/firebase_pro_visits.sql, orchestration/dags/dependencies/firebase/sql/clean/firebase_pro_visits.sql
=> update bank fields of firebase_pro_visits

orchestration/dags/data_gcp_dbt/dbt_project.yml
=> (dbt_project) remove unnecessary config & add owner config

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_collective_booking_data.sql, orchestration/dags/data_gcp_dbt/models/sources.yml
=> (dbt) add enriched_collective_booking_data

orchestration/dags/data_gcp_dbt/tests/audit/analytics/enriched/enriched_user_offerer_test.sql
=> rename model name

orchestration/dags/data_gcp_dbt/models/clean/bookable_collective_offer_history.sql, orchestration/dags/data_gcp_dbt/models/clean/bookable_offer_history.sql
=> (dbt) add incremental config to bookable_offer

orchestration/dags/data_gcp_dbt/dbt_project.yml, orchestration/dags/data_gcp_dbt/models/clean/bookable_collective_offer_history.sql, orchestration/dags/data_gcp_dbt/models/clean/bookable_offer_history.sql, orchestration/dags/data_gcp_dbt/models/properties.yml
=> MEP v282.0.0

orchestration/dags/dependencies/propilote/sql/analytics/propilote_kpis.sql
=> (propilote) fix stg by replacing cast

orchestration/dags/dependencies/firebase/sql/clean/firebase_pro_visits.sql
=> update nb_start_venue_edition field

orchestration/dags/dependencies/export_cloudsql_tables_to_bigquery/sql/clean/past_recommended_offers.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/firebase_recommendation_events.sql
=> (reco) Decrease import time for recommendation events

orchestration/dags/dependencies/firebase/sql/analytics/firebase_pro_events.sql, orchestration/dags/dependencies/firebase/sql/clean/firebase_pro_visits.sql
=> (firebase) fixes - remove parse_date in pro tables

jobs/etl_jobs/internal/export_clickhouse/main.py, jobs/etl_jobs/internal/export_clickhouse/requirements.txt, jobs/etl_jobs/internal/export_clickhouse/schema/analytics/offer_consultation.sql, jobs/etl_jobs/internal/export_clickhouse/schema/analytics/venue_offer_statistics.sql, jobs/etl_jobs/internal/export_clickhouse/schema/recommendation/user_consultation.sql, jobs/etl_jobs/internal/export_clickhouse/schema/tmp/analytics_offer_consultation.sql, jobs/etl_jobs/internal/export_clickhouse/schema/tmp/analytics_venue_offer_statistics.sql, jobs/etl_jobs/internal/export_clickhouse/schema/tmp/recommendation_user_consultation.sql, jobs/etl_jobs/internal/export_clickhouse/utils.py, orchestration/dags/dependencies/export_clickhouse/export_clickhouse.py, orchestration/dags/dependencies/export_clickhouse/sql/export_offer_consultation.sql, orchestration/dags/dependencies/export_clickhouse/sql/export_user_consultation.sql, orchestration/dags/dependencies/export_clickhouse/sql/export_venue_offer_statistics.sql, orchestration/dags/jobs/export/export_clickhouse.py
Add table samples for (wip) OLAP db projet in order to test multiple uses cases. 
This code will likely change if we deploy the entire project into production, including push logic data tables.
PC-28556
=> [PC-28556](clickhouse) Add table samples

orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_offer_metadata.sql
=> add dirty case when category book then join on gtl

orchestration/dags/data_gcp_dbt/models/clean/user_item_discovery.sql
=> (discovery) replace null values & compute discovery_delta

orchestration/dags/data_gcp_dbt/models/clean/applicative/deposit.sql
This PR is linked to [this ticket](https://passculture.atlassian.net/browse/PC-28521).
Tag a reviewer if necessacy @Jules-Arbelot 
PC-28521
=> [PC-28521] Clean wrong deposit amount

orchestration/dags/dependencies/firebase/import_firebase.py
=> hotfix firebase pro visits deduplication

orchestration/dags/dependencies/export_posthog/sql/export_firebase_native_events.sql
This PR amends the existing firebase native export to posthog by adding extra event parameters and focusing on key events.
Tag a reviewer if necessacy  @LucileRainteau @carolinemestre-passculture  
[JIRA-ticket_number](https://passculture.atlassian.net/browse/PC-28393)
=> Pc 28393 data post hog jeunes

orchestration/dags/dependencies/views/import_views.py, orchestration/dags/dependencies/views/sql/analytics/api_logs.sql, orchestration/dags/dependencies/views/sql/clean/api_logs.sql
=> (backend) Create view for api_logs in analytics and add new fields

orchestration/dags/data_gcp_dbt/models/analytics/firebase/firebase_aggregated_daily_campaign_events.sql
Nous ajoutons `on_schema_change = "sync_all_columns"` afin que le schéma de la table s'ajuste automatiquement quand nous ajoutons ou supprimons des colonnes à notre modèle. 
=> Add on_schema_change parameter

jobs/ml_jobs/clusterisation/cluster/generate.py, jobs/ml_jobs/clusterisation/cluster/preprocess.py, jobs/ml_jobs/clusterisation/configs/cluster/default-config.json, jobs/ml_jobs/clusterisation/configs/cluster/simple-config.json, jobs/ml_jobs/clusterisation/configs/cluster/unconstrained-config.json, jobs/ml_jobs/clusterisation/configs/labels.py, jobs/ml_jobs/clusterisation/configs/prompts.py, jobs/ml_jobs/clusterisation/configs/reduction/default-config.json, jobs/ml_jobs/clusterisation/reduction/dimension_reduction.py, jobs/ml_jobs/clusterisation/tools/utils.py, jobs/ml_jobs/clusterisation/topics/clean.py, jobs/ml_jobs/clusterisation/topics/generate.py, orchestration/dags/dependencies/ml/clusterisation/sql/import_item_clusters.sql, orchestration/dags/jobs/ml/clusterisation_items.py
Add new clustering methods in order to test distinct uses cases in production for diversificatio purposes
=> [ML](clusters) Add new configs for clusters

orchestration/dags/data_gcp_dbt/models/clean/bookable_collective_offer_history.sql
There was a small mistake in the where clause of the collective_offer_history model.
=> (dbt) Update where clause in collective_offer_history

orchestration/dags/dependencies/views/sql/analytics/backend_events.sql, orchestration/dags/dependencies/views/sql/clean/api_logs.sql
=> (backend) fix: update sql for views

jobs/etl_jobs/external/metabase-archiving/metabase_api.py, orchestration/dags/jobs/ml/clusterisation_items.py
=> hotfix clusterisation

jobs/etl_jobs/external/metabase-archiving/metabase_api.py
=> revert exception empty body metabase api class

jobs/etl_jobs/external/gsheet/requirements.txt, jobs/etl_jobs/external/metabase-archiving/metabase_api.py, orchestration/dags/jobs/ml/clusterisation_items.py
=> MEP 285.0.0

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_cultural_partner_data.yml, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_venue_data.yml, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_venue_tags_data.yml, orchestration/dags/data_gcp_dbt/models/properties.yml
=> (dbt) Update config files

orchestration/dags/jobs/ml/algo_default_deployment.py
This endpoint is not used right now, and we don't need to deploy every day a new model.
=> (reco) VertexAI: remove fallback deployment

jobs/etl_jobs/external/metabase-archiving/main.py, jobs/etl_jobs/external/metabase-archiving/metabase_api.py, orchestration/dags/dependencies/metabase/import_metabase.py, orchestration/dags/dependencies/metabase/sql/raw/view_log.sql, orchestration/dags/dependencies/metabase/sql/raw/view_logs.sql
=> (metabase) :feat add new SQL table + IAP logic

orchestration/dags/data_gcp_dbt/macros/generate_schema_name.sql, orchestration/dags/data_gcp_dbt/macros/get_custom_alias.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__gtl.sql, orchestration/dags/dependencies/import_analytics/sql/clean/applicative_database/titelive_gtl_mapping.sql, orchestration/dags/dependencies/import_analytics/sql/raw/titelive_gtl_mapping.sql
=> MEP v286.0.0

orchestration/dags/data_gcp_dbt/models/properties.yml
We are adding`firebase_daily_offer_consultation_data` to analytics_prod in properties.yml so that the table is created in `ANALYTICS_PROD` (before, they were created in `ANALYTICS_DBT_PROD`).
Tag a reviewer if necessacy  @MatthieuRipollPass @MatthieuRipollPassCulture 
=> Add firebase_daily_offer_consultation_data to analytics_prod

orchestration/dags/data_gcp_dbt/models/properties.yml
We are adding `mrt_global__firebase_pro_event` in `properties.yml` so that the table is created in `ANALYTICS_PROD`.
Tag a reviewer if necessacy  @mathilde-vey 
=> (dbt) Add mrt_global__firebase_pro_event to analytics_prod

orchestration/dags/data_gcp_dbt/models/sources.yml, orchestration/dags/dependencies/import_analytics/sql/analytics/forbidden_item_recommendation.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/recommendable_offers_data.sql
This PR fix gtl references and join logic
=> fix branches conflict

orchestration/dags/jobs/dbt/dbt_dag_run.py
=> fix: dbt airflow task naming

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__titelive_gtl.sql, orchestration/dags/data_gcp_dbt/models/sources.yml, orchestration/dags/jobs/dbt/dbt_dag_run.py
=> MEP v286.1.1

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_event.sql
=> fix: add pre hook to int_firbase__pro_event

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_event.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/recommendable_offers_data.sql
=> MEP v286.1.2

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_event.sql
This PR changes udf created in firebase model pre hook to the one used in the query
=> fix: create correct UDF in BQ schema

jobs/etl_jobs/internal/cold-data/bucket.py
Fix: Take only the specified folder bucket files.
This PR [fixes] the cold-data import bucket
=> (import) :fix cold-data bucket prefix folder

orchestration/dags/data_gcp_dbt/profiles.yml
This PR increases dbt jobs timeout in prod
- [ x I will create a review on slack and ensure to specify the duration of the review task: short (<10min), medium (<30min), long (>30min)
=> (dbt) feat: increase dbt prod jobs timeout

orchestration/dags/data_gcp_dbt/models/clean/applicative/user_pro_new_nav_state.sql, orchestration/dags/data_gcp_dbt/models/properties.yml, orchestration/dags/data_gcp_dbt/models/sources.yml, orchestration/dags/dependencies/import_analytics/sql/raw/user_pro_new_nav_state.sql
=> add new table for new nav AB and Beta tests

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_cultural_partner_data.sql
=> (dbt) Add new fields in enriched_cultural_partner_data

jobs/ml_jobs/ranking_endpoint/app/model.py, orchestration/dags/dependencies/training_data/sql/ranking_endpoint_training_data.sql
* Add a preprocessing step in ranking training script for embedding features 
* v0: Calculates mean over the full embedding  
* Add 3 features to ranking input : 
* day_of_the_week
* hour_of_the_day
* semantic_emb_mean
This PR adds the features
=> (reco) Update ranking features 

orchestration/dags/data_gcp_dbt/models/analytics/diversification/diversification_raw.sql
We are adding the column offer_type_domain to the subquery and updating the field names in the final query of the `diversification_raw` model.
Tag a reviewer if necessacy  @valoumiaou  
=> (dbt) Add missing column and update columns names 

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__venue.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__venue.sql, orchestration/dags/data_gcp_dbt/models/sources.yml
This PR adds a boolean column venue_is_acessibility_synched to global_venue table if this venue is synched to an accessibility provider (contained in applicative_database_accessibility_provider)
Tag a reviewer if necessacy  @carolinemestre-passculture 
JIRA-ticket_number https://passculture.atlassian.net/browse/PC-29227?atlOrigin=eyJpIjoiYzRlYzA1OWM2MmE5NDVmNThhMzU2ZGYzNmI2MzE3NmQiLCJwIjoiaiJ9
=> Pc 29227 data venue accessibility provider ajouter linfo dans enriched venue data

orchestration/dags/data_gcp_dbt/models/analytics/diversification/items_features_ids.sql, orchestration/dags/data_gcp_dbt/models/clean/ML/item_clusters_topics_labels.sql, orchestration/dags/data_gcp_dbt/models/clean/applicative/user_pro_new_nav_state.sql, orchestration/dags/data_gcp_dbt/models/sources.yml, orchestration/dags/dependencies/import_analytics/sql/analytics/recommendable_offers_data.sql
This PR fixes recent untested pushes
=> fix: various dags failures

orchestration/dags/data_gcp_dbt/models/analytics/diversification/items_features_ids.sql, orchestration/dags/data_gcp_dbt/models/clean/ML/item_clusters_topics_labels.sql, orchestration/dags/data_gcp_dbt/models/clean/applicative/user_pro_new_nav_state.sql, orchestration/dags/data_gcp_dbt/models/sources.yml, orchestration/dags/dependencies/import_analytics/sql/analytics/recommendable_offers_data.sql
=> MEP 287.1.0

orchestration/dags/jobs/import/import_addresses.py
=> (import) feat: reduce cron for addresses import

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_event_flattened.sql
The `extract_params_string_value.sql` and `extract_params_int_value.sql` macros have been modified; we need to align the `int_firebase__pro_event` model accordingly.
=> (dbt) Align firebase pro events with updated extraction macros

orchestration/dags/dependencies/import_analytics/import_analytics.py, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_offer_metadata.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/forbidden_item_recommendation.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/recommendable_offers_data.sql, orchestration/dags/dependencies/import_analytics/sql/clean/applicative_database/titelive_gtl.sql
=> (import) fix offer_metadata and recommendable_offers_data

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_event.sql
We attempted to merge two tables and the old one had a clustering field. We need to align this clustering field in the code for the new table.
=> (dbt) Add clustering field to new firebase events model

orchestration/dags/data_gcp_dbt/macros/get_custom_alias.sql
We want the "export" folder to function like the "mart" folder for schema names. We are updating the DBT macro get_custom_alias.sql accordingly.
=> (dbt) Update dbt custom alias macro

jobs/etl_jobs/internal/export_posthog/bq.py, jobs/etl_jobs/internal/export_posthog/main.py, orchestration/dags/data_gcp_dbt/models/export/posthog/exp_posthog__adage_log.sql, orchestration/dags/data_gcp_dbt/models/export/posthog/exp_posthog__native_event.sql, orchestration/dags/data_gcp_dbt/models/export/posthog/exp_posthog__pro_event.sql, orchestration/dags/jobs/export/export_posthog.py
=> (export) feat: Update .py code with new data format

jobs/etl_jobs/internal/export_posthog/bq.py, jobs/etl_jobs/internal/export_posthog/main.py, orchestration/dags/data_gcp_dbt/macros/get_custom_alias.sql, orchestration/dags/data_gcp_dbt/models/export/posthog/exp_posthog__adage_log.sql, orchestration/dags/data_gcp_dbt/models/export/posthog/exp_posthog__native_event.sql, orchestration/dags/data_gcp_dbt/models/export/posthog/exp_posthog__pro_event.sql, orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_event.sql, orchestration/dags/jobs/export/export_posthog.py
=> MEP 288.2.0

orchestration/dags/jobs/export/export_posthog.py
=> (export) feat: update dag for posthog catchup

jobs/ml_jobs/retrieval_vector/deploy_semantic.py, orchestration/dags/dependencies/training_data/sql/retrieval_semantic_vector.sql, orchestration/dags/jobs/export/export_posthog.py
=> MEP 288.3.0 

orchestration/dags/data_gcp_dbt/models/export/posthog/exp_posthog__adage_log.sql
=> (dbt) Update wrong filter in export adage log model

orchestration/dags/data_gcp_dbt/models/export/posthog/exp_posthog__adage_log.sql
=> MEP 288.2.1

orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_home_module_conversion.sql, orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_user_home_module.sql, orchestration/dags/data_gcp_dbt/models/sources.yml
The `mrt_native__daily_user_home_module` model was timing out every time we ran it because it was taking too long. Therefore, we added an incremental strategy that allows us to perform calculations only for the previous day.
=> (dbt) Add incremental strategy to daily_user_home_module

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_venue_data.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__booking.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__deposit.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__extract_offer.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__offer.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__stock.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__user.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__venue.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/schema.yml, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__booking.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__offer.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__stock.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__user.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__venue.sql
The purpose of this PR is to migrate the `enriched_booking_data` model, the new name of the model will be `mrt_global__booking` and both tables must be identical.
We are also migrating/updating all the necessary models for the construction of this model.
=> (dbt) Migration enriched_booking_data

orchestration/dags/data_gcp_dbt/macros/generate_schema_name.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_venue_data.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__booking.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__deposit.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__extract_offer.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__offer.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__stock.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__user.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__venue.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/schema.yml, orchestration/dags/data_gcp_dbt/models/intermediate/pcapi/int_pcapi__adage_log.sql, orchestration/dags/data_gcp_dbt/models/intermediate/pcapi/int_pcapi__log.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__booking.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__offer.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__stock.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__user.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__venue.sql, orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_home_module_conversion.sql, orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_user_home_module.sql, orchestration/dags/data_gcp_dbt/models/mart/pro/mrt_pro__log.sql, orchestration/dags/data_gcp_dbt/models/sources.yml, orchestration/dags/dependencies/training_data/sql/recommendation_item_features.sql
=> MEP 288.4.0

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__booking.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__venue.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__booking.sql
…cent checks
`mrt_global__venue` is the model that will replace `enriched_venue_data`. We have conducted data quality checks on all columns of the model before making the switch between the two. In this PR, we are making some corrections to address the discrepancies detected.
Tag a reviewer if necessacy  @Jules-Arbelot 
=> (dbt) Correct data discrepancies in mrt_global__venue identified by recent data quality checks

orchestration/dags/dependencies/contentful/sql/analytics/contentful_homepages.sql
=> (analytics) fix: remove legacy firebase logic

jobs/etl_jobs/internal/export_posthog/main.py, orchestration/dags/data_gcp_dbt/models/export/posthog/exp_posthog__native_event.sql, orchestration/dags/dependencies/contentful/sql/analytics/contentful_homepages.sql, orchestration/dags/jobs/export/export_posthog.py, orchestration/dags/jobs/ml/link_offers.py
=> MEP 289.0.1

jobs/etl_jobs/internal/export_clickhouse/schema/tmp/analytics_venue_offer_statistics.sql, jobs/etl_jobs/internal/export_clickhouse/schema/tmp/intermediate_offer_consultation.sql, jobs/etl_jobs/internal/export_clickhouse/schema/tmp/intermediate_user_consultation.sql
=> (clickhouse) fix: keep S3 for import tmp

orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__stock.sql
=> (dbt) Revert to previous version of mrt_global__stock

orchestration/dags/dependencies/analytics/import_analytics.py
=> remove applicative analytics

jobs/etl_jobs/internal/export_posthog/event.py, jobs/etl_jobs/internal/export_posthog/main.py, orchestration/dags/jobs/export/export_posthog.py
=> (posthog) feat: desync jobs in multiple dags for catchup

jobs/etl_jobs/internal/cold-data/tables_config.py, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_institution_data.sql, orchestration/dags/data_gcp_dbt/models/sources.yml
=> [PC-28827](cold data) add institution type

orchestration/dags/data_gcp_dbt/macros/udf_js/dehumanize_id_function.sql, orchestration/dags/data_gcp_dbt/macros/udf_js/humanize_id_function.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_collective_offer_data.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_offer_data.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_offerer_data.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_stock_data.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_venue_data.sql, orchestration/dags/data_gcp_dbt/models/clean/offer_metadata.sql, orchestration/dags/data_gcp_dbt/models/clean/user_beneficiary.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__offerer.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__venue.sql, orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_event.sql
We are updating the targets of the routines (the functions that are generated by the `humanize_id_function` and `dehumanize_id_function` macros. Previously, they were directed to `analytics_dbt_{target_name}`, but now they are going to `analytics_{target_name}` (our goal is to permanently delete the `analytics_dbt_prod` schema).
=> (dbt) Update routines target

orchestration/dags/data_gcp_dbt/macros/get_environment_mediation_url.sql, orchestration/dags/data_gcp_dbt/models/clean/offer_metadata.sql
We are adding a macro called `get_environment_mediation_url` that retrieves the correct URL based on the environment we are in. We use this macro in the `offer_metadata` model.
=> (dbt) Add mediation url macro

orchestration/dags/data_gcp_dbt/models/analytics/diversification/diversification_raw.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_cultural_partner_data.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_local_authority_data.sql, orchestration/dags/data_gcp_dbt/models/clean/ML/properties.yml, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__user.sql, orchestration/dags/data_gcp_dbt/models/properties.yml
=> (dbt) Fix jobs failed

orchestration/dags/data_gcp_dbt/models/analytics/diversification/diversification_raw.sql, orchestration/dags/data_gcp_dbt/models/clean/ML/item_clusters_topics_labels.sql, orchestration/dags/data_gcp_dbt/models/clean/item_metadata.sql, orchestration/dags/data_gcp_dbt/models/sources.yml, orchestration/dags/jobs/ml/clusterisation_items.py
=> (clusters) :fix update default flag for clusters

orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/ml_reco__available_offer.sql
=> MEP v289.4.1

orchestration/dags/data_gcp_dbt/models/intermediate/pcapi/int_pcapi__log.sql, orchestration/dags/data_gcp_dbt/models/mart/pro/mrt_pro__log.sql
=> Add data from Beta Test (new pro nav)

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_partner_retention_data.sql
=> (dbt) Update enriched_venue_data ref

jobs/etl_jobs/internal/export_posthog/main.py, orchestration/dags/jobs/export/export_posthog.py
=> (posthog) update catchup + increase batch

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__offer.sql
=> [dbt](int_applicative__offer) move item logic to offer_item_ids during migration

jobs/etl_jobs/internal/export_posthog/main.py, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_partner_retention_data.sql, orchestration/dags/data_gcp_dbt/models/analytics/firebase/firebase_booking_origin.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__offer.sql, orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_event.sql, orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/ml_reco__available_offer.sql, orchestration/dags/jobs/export/export_posthog.py
=> MEP v289.4.1 

orchestration/dags/data_gcp_dbt/dbt_project.yml
=> (dbt) Update dbt project config

orchestration/dags/data_gcp_dbt/models/clean/applicative/opening_hours.sql, orchestration/dags/data_gcp_dbt/models/sources.yml, orchestration/dags/dependencies/applicative_database/sql/raw/opening_hours.sql
We are removing the `opening_hours` model as the timestamp conversion is not working and the format is challenging. We are temporarily removing the model to prevent a DAG failure.
=> (dbt) Delete opening hours and its dependencies

orchestration/dags/data_gcp_dbt/models/clean/applicative/opening_hours.sql, orchestration/dags/data_gcp_dbt/models/sources.yml, orchestration/dags/dependencies/analytics/sql/analytics/firebase_aggregated_search_events.sql, orchestration/dags/dependencies/applicative_database/sql/raw/opening_hours.sql
=> MEP v290.0.1

orchestration/dags/dependencies/logs/sql/analytics/app_native_logs.sql
Please include a summary of the changes: Add subscription info (current state, new subscriptions) to app native logs
Tag a reviewer if necessacy  @cdelabre @carolinemestre-passculture 
JIRA-ticket_number https://passculture.atlassian.net/browse/PC-29468
=> add subscription themes consent to app native logs

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_venue_provider_data.sql, orchestration/dags/dependencies/applicative_database/sql/raw/venue_provider.sql
=> add fields about collective synchro and add creation_date field

orchestration/dags/dependencies/analytics/sql/analytics/firebase_aggregated_search_events.sql, orchestration/dags/dependencies/logs/sql/analytics/app_native_logs.sql
=> MEP v290.1.0

orchestration/dags/data_gcp_dbt/models/clean/applicative/opening_hours.sql, orchestration/dags/data_gcp_dbt/models/sources.yml, orchestration/dags/dependencies/applicative_database/sql/raw/opening_hours.sql
=> add opening hours

orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_user_home_module.sql
Remove join on entry_id, not available for favorites logs
=> Fix join for favorites data in native_daily_user_home_module

orchestration/dags/data_gcp_dbt/models/analytics/firebase/firebase_aggregated_daily_campaign_events.sql
=> modification du champs diversification

jobs/ml_jobs/retrieval_vector/app/app.py
=> (retrieval) fix similar offer prediction

jobs/ml_jobs/retrieval_vector/app/app.py
=> (retrieval) add logs for similar offer retrieval api

jobs/ml_jobs/retrieval_vector/app/app.py, orchestration/dags/dependencies/logs/sql/analytics/app_native_logs.sql
=> MEP v292.1.0

jobs/ml_jobs/retrieval_vector/app/app.py
=> (retrieval) unify similar offer output

orchestration/dags/data_gcp_dbt/models/analytics/firebase/firebase_aggregated_daily_campaign_events.sql
=> MEP v292.1.1

jobs/ml_jobs/algo_training/requirements.txt
=> (ml_tests) fix requirements.txt

orchestration/dags/dependencies/backend/create_tables.py, orchestration/dags/dependencies/backend/sql/adage_home_playlist_new_template_offers.sql, orchestration/dags/dependencies/backend/sql/adage_home_playlist_new_venues.sql
=> PC 29726 update adage home playlists

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_collective_booking_data.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_collective_offer_data.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_institution_data.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_partner_activation_activity.sql, orchestration/dags/data_gcp_dbt/models/analytics/eple_aggregated.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__institution.sql, orchestration/dags/dependencies/applicative_database/sql/raw/collective_offer.sql, orchestration/dags/dependencies/applicative_database/sql/raw/collective_offer_template.sql, orchestration/dags/dependencies/applicative_database/sql/raw/educational_institution_program_association.sql
=> (dbt) Resolve execution failure in dbt

orchestration/dags/data_gcp_dbt/models/clean/offer_item_ids.sql
=> MEP v293.1.0

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_institution_data.sql
=> PC-29861 correction de la jointure entre les deux tables

orchestration/dags/dependencies/cold_data/sql/clean/eac_webinar.sql
=> hotfix eac_webinar cold datas

orchestration/dags/data_gcp_dbt/models/mart/collective/mrt_collective__offer.sql, orchestration/dags/data_gcp_dbt/models/mart/collective/mrt_collective__offer_unverified.sql, orchestration/dags/data_gcp_dbt/models/mart/collective/mrt_collective__stock.sql
We realized that we need two models in `analytics_prod`: `enriched_collective_offer` as it was before, but also `enriched_collective_offer_data` not filtered on `APPROVED` offers for specific cases like fraud.
Therefore, we are going to create two offer models in the global folder: `mrt_collective__offer` and `mrt_collective__offer_unverified` (for now with these names).
=> (dbt) Create mrt_collective__offer_unverified

orchestration/dags/dependencies/applicative_database/sql/raw/invoice.sql
=> Add bank_account_id to invoice table

orchestration/dags/data_gcp_dbt/models/analytics/firebase/firebase_session_origin.sql, orchestration/dags/data_gcp_dbt/models/analytics/firebase/firebase_visits.sql
=> (dbt) fix: update firebase_visits to reduce compute time

jobs/etl_jobs/external/qualtrics/main.py, jobs/etl_jobs/external/qualtrics/qualtrics_survey_answers.py, jobs/etl_jobs/external/qualtrics/utils.py, orchestration/dags/jobs/import/import_qualtrics.py
- création de la table 'clean_env.qualtrics_surveys' qui contient les metadata des enquêtes Qualtrics (nom, isActive etc...)
- création de la table 'analytics_env.qualtrics_answers' qui contient toutes les réponses des enquêtes Qualtrics. Cette table est ranged-partitionnée par le survey_id. Chaque semaine, cette table est actualisée pour les enquêtes actives. On recalcule toutes les réponses et elles sont overwrite dans la partition correspondante.
=> (qualtrics) import all survey answers

orchestration/dags/data_gcp_dbt/models/analytics/adage.sql
PR to fix a small error in the dbt query `adage.sql`.
=> (dbt) Correct analytics.adage query

orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__event.sql
=> (dbt) Fix typo error

orchestration/dags/data_gcp_dbt/dbt_project.yml, orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_event.sql
Previously, the model `int_firebase__native_event` wrote to the table `analytics_prod.firebase_events`. Now we want to modify it so that the model writes to `int_firebase_prod.native_event`.
=> (dbt) Update int_firebase__native_event config

orchestration/dags/dependencies/firebase/sql/clean/firebase_pro_visits.sql
=> modify nb_start_venue_edition

orchestration/dags/data_gcp_dbt/models/intermediate/pcreco/int_pcreco__displayed_offer_event.sql, orchestration/dags/data_gcp_dbt/models/intermediate/pcreco/int_pcreco__past_offer_context.sql, orchestration/dags/dependencies/firebase/sql/clean/firebase_pro_visits.sql
=> MEP v292.2.1

.github/workflows/base_workflow.yml, .github/workflows/reusable_dbt_compile.yml
=> add following steps to CI: install dbt, fetch dependencies & compile dbt project

orchestration/dags/data_gcp_dbt/models/mart/collective/mrt_collective__offer.sql
In this PR we are adding 3 columns to `mrt_collective__offer` that were missing.
=> (dbt) Add missing columns to mrt_collective__offer

jobs/etl_jobs/external/contentful/contentful_client.py, jobs/etl_jobs/external/contentful/main.py, jobs/etl_jobs/external/contentful/utils.py
=> (contentful) fix: keep default api for non-prod import

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__product.sql, orchestration/dags/dependencies/applicative_database/sql/raw/product.sql, orchestration/tests/data_analytics/config.py
=> switch column gcu

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__product.sql, orchestration/dags/dependencies/applicative_database/sql/raw/product.sql, orchestration/tests/data_analytics/config.py
=> fix: gcuCompatibilityType typo import field

jobs/ml_jobs/ranking_endpoint/app/model.py, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__product.sql, orchestration/dags/dependencies/applicative_database/sql/raw/product.sql, orchestration/dags/jobs/ml/ranking_endpoint_build.py, orchestration/tests/data_analytics/config.py
=> MEP v292.4.0

orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/ml_reco__available_offer.sql, orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/ml_reco__recommendable_item.sql
=> (dbt) Update model reference in ml_reco__available_offer

jobs/etl_jobs/external/qualtrics/main.py
=> (fix) qualtrics import package

orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__event.sql
=> (dbt) Add session_id and update user_current_deposit_type field

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_partner_retention_data.sql
=> (dbt) Add missing alias to enriched_partner_retention_data

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__provider.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__venue.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__provider.sql
The purpose of this PR is to migrate the `enriched_venue_provider_data` model, the new name of the model will be `mrt_global__provider` and both tables must be identical.
We are also migrating/updating all the necessary models for the construction of this model.
Tag a reviewer if necessacy @LucileRainteau
=> (dbt) Migrate enriched_venue_provider_data

jobs/etl_jobs/external/qualtrics/main.py
=> (fix) add call to get_qualtrics_survey

orchestration/dags/dependencies/applicative_database/sql/raw/educational_redactor.sql
Fix educational redactor import to update encoding after extension removal
=> [fix] educational redactor encode email

orchestration/dags/data_gcp_dbt/dbt_project.yml
We are adding these two lines in the `dbt_project.yml` file so that the documentation written in DBT is also visible in BigQuery.
=> (dbt) Add dbt documentation in BQ

jobs/etl_jobs/external/siren/scripts/import_siren.py
=> [DE](siren) fix: update Siren API to v3.11

orchestration/dags/dependencies/applicative_database/sql/raw/opening_hours.sql, orchestration/dags/jobs/import/import_applicative_database.py
=> (import) feat: applicative_database, add in opening_hours details

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_daily_user_home_module.sql, orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_user_home_module.sql, orchestration/dags/dependencies/applicative_database/sql/raw/opening_hours.sql, orchestration/dags/jobs/import/import_applicative_database.py
=>  MEP v294.1.0

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__venue_criterion.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__venue_tag.sql
The purpose of this PR is to migrate the `enriched_venue_tags_data` model, the new name of the model will be `mrt_global__venue_tag` and both tables must be identical.
Tag a reviewer if necessacy @LucileRainteau
=> (dbt) Migrate enriched_venue_tags_data

orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_home_module_conversion.sql, orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_user_home_module.sql
=> (dbt) fix: Improve daily home module conversion

orchestration/dags/data_gcp_dbt/models/clean/applicative/allocine_venue_provider_price_rule.sql, orchestration/dags/data_gcp_dbt/models/sources.yml, orchestration/dags/dependencies/applicative_database/sql/raw/allocine_venue_provider_price_rule.sql
=> (analytics) feat: remove unused applicative table

orchestration/dags/data_gcp_dbt/models/clean/applicative/allocine_venue_provider_price_rule.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__venue_criterion.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__venue_tag.sql, orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_home_module_conversion.sql, orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_user_home_module.sql, orchestration/dags/data_gcp_dbt/models/sources.yml, orchestration/dags/dependencies/applicative_database/sql/raw/allocine_venue_provider_price_rule.sql
=> MEP v295.0.0

orchestration/dags/data_gcp_dbt/models/export/posthog/exp_posthog__pro_event.sql, orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_event.sql, orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_event_flattened.sql, orchestration/dags/data_gcp_dbt/models/mart/pro/mrt_pro__event.sql, orchestration/dags/dependencies/firebase/sql/analytics/firebase_pro_events.sql
=> (dbt) Add downolad parameters to firebase pro model

jobs/etl_jobs/external/adage/requirements.txt, jobs/etl_jobs/external/addresses/requirements.txt, jobs/etl_jobs/external/appsflyer/requirements.txt, jobs/etl_jobs/external/contentful/requirements.txt, jobs/etl_jobs/external/downloads/requirements.txt, jobs/etl_jobs/external/gsheet/requirements.txt, jobs/etl_jobs/external/metabase-archiving/requirements.txt, jobs/etl_jobs/external/qualtrics/requirements.txt, jobs/etl_jobs/external/sendinblue/requirements.txt, jobs/etl_jobs/external/siren/requirements.txt, jobs/etl_jobs/internal/import_api_referentials/requirements.txt, jobs/ml_jobs/embeddings/requirements.txt, jobs/ml_jobs/record_linkage/requirements.txt
Update pandas versions to latest available 
This PR fixes the bug
- [] I have performed a self-review of my code
=> [FIX] Update pandas 

orchestration/dags/data_gcp_dbt/models/analytics/cultural_sector_bookability_frequency.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/aggregated_daily_offer_consultation_data.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_partner_activation_activity.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_partner_retention_data.sql, orchestration/dags/data_gcp_dbt/models/analytics/history/bookable_partner_history.sql, orchestration/dags/data_gcp_dbt/models/analytics/partner_type_bookability_frequency.sql, orchestration/dags/data_gcp_dbt/models/analytics/venue_siren_offers.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__product.sql, orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/ml_reco__available_offer.sql, orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/ml_reco__recommendable_item.sql, orchestration/dags/data_gcp_dbt/models/machine_learning/recommendation/ml_reco__restrained_item.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__offer.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__offer_unverified.sql, orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__event.sql, orchestration/dags/dependencies/ml/clusterisation/sql/import_item_clusters.sql, orchestration/dags/dependencies/ml/embeddings/sql/item_to_extract_embedding.sql, orchestration/dags/dependencies/ml/linkage/sql/artists_to_link.sql, orchestration/dags/dependencies/training_data/sql/recommendation_item_features.sql, orchestration/dags/dependencies/training_data/sql/training_data_bookings.sql, orchestration/dags/dependencies/training_data/sql/training_data_clicks.sql, orchestration/dags/dependencies/training_data/sql/training_data_favorites.sql
As part of the migration, we will remove the `enriched_offer_data` model and replace it with `mrt_global__offer`. To do this, we need to update the references to the old model throughout the project.
TODO : check `bookable_venue_history` 
=> (dbt) Update enriched_offer_data dependencies

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_venue_tags_data.sql
=> add partner_id to enriched_venue_tags_data

jobs/etl_jobs/external/siren/scripts/import_siren.py
=> [DE-213](siren) fix: remove error handling in case siren are not found

jobs/etl_jobs/external/contentful/contentful_client.py, jobs/etl_jobs/external/contentful/main.py
=> [DE-214](contentful) feat: add new trend and video modules 

orchestration/dags/data_gcp_dbt/models/intermediate/pcreco/int_pcreco__displayed_module_context.sql, orchestration/dags/data_gcp_dbt/models/intermediate/pcreco/int_pcreco__past_offer_context.sql
=> [DE-128](pcreco) feat: add model stats columns

.github/PULL_REQUEST_TEMPLATE/MEP_template.md
Update MEP to ensure squash and merge is not chosen for MEP
https://www.notion.so/passcultureapp/880351701699470cb129e4e0ad6bbcba?v=bfba95ea66224a80aed7b5291454389a&p=ebb03002d46f471ca565ca0494138ab4&pm=s
=> Update MEP doc by ensuring squash and merge is not chosen

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_user_data.sql, orchestration/dags/dependencies/cold_data/sql/clean/geo_iris.sql
=> (dbt) Add missing conversion in geo_iris

orchestration/dags/data_gcp_dbt/models/export/posthog/exp_posthog__native_event.sql
=> (dbt) Update wrong column name

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_cultural_partner_data.sql
=> (dbt) Fix and add fields about first offer and bookability in enriched_cultural_partner_data

orchestration/dags/data_gcp_dbt/models/clean/user_beneficiary.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__user.sql
=> (dbt) Update source table to resolve duplicates issue

jobs/etl_jobs/external/adage/requirements.txt, jobs/etl_jobs/external/addresses/requirements.txt, jobs/etl_jobs/external/appsflyer/requirements.txt, jobs/etl_jobs/external/batch/requirements.txt, jobs/etl_jobs/external/contentful/requirements.txt, jobs/etl_jobs/external/downloads/requirements.txt, jobs/etl_jobs/external/gsheet/requirements.txt, jobs/etl_jobs/external/metabase-archiving/requirements.txt, jobs/etl_jobs/external/notion/requirements.txt, jobs/etl_jobs/external/qualtrics/requirements.txt, jobs/etl_jobs/external/sendinblue/requirements.txt, jobs/etl_jobs/external/siren/requirements.txt, jobs/etl_jobs/internal/export_clickhouse/requirements.txt, jobs/etl_jobs/internal/export_posthog/requirements.txt, jobs/etl_jobs/internal/import_api_referentials/requirements.txt, jobs/ml_jobs/algo_training/requirements.txt, jobs/ml_jobs/clusterisation/requirements.txt, jobs/ml_jobs/embeddings/requirements.txt, jobs/ml_jobs/ranking_endpoint/api-requirements.txt, jobs/ml_jobs/ranking_endpoint/requirements.txt, jobs/ml_jobs/record_linkage/requirements.txt, jobs/ml_jobs/reduction/requirements.txt, jobs/ml_jobs/retrieval_vector/api-requirements.txt, jobs/ml_jobs/retrieval_vector/requirements.txt, orchestration/README.md
=> (hotfix) retrograd pandas version for python3.8

orchestration/dags/data_gcp_dbt/models/clean/applicative/venue.sql, orchestration/dags/data_gcp_dbt/models/clean/user_beneficiary.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__user.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__venue.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__offer_unverified.sql
=> (dbt) fix: update join for irises

orchestration/dags/data_gcp_dbt/models/analytics/partner_type_bookability_frequency.sql
=> (dbt) Remove wrong character in partner_type_bookability_frequency

orchestration/dags/data_gcp_dbt/models/export/clickhouse/exp_clickhouse__booking.sql, orchestration/dags/data_gcp_dbt/models/export/clickhouse/exp_clickhouse__collective_booking.sql
=> Hotfix dbt run dag

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_user_data.sql, orchestration/dags/data_gcp_dbt/models/sources.yml
Draft PR d'ajout de champs dans enriched_user_data -> Test des dépendances avec app_native_logs
=> (dbt) Add fields to enriched_user_data relative to theme subscriptions

jobs/etl_jobs/external/metabase-archiving/dependencies.py, jobs/etl_jobs/external/metabase-archiving/main.py, jobs/etl_jobs/external/metabase-archiving/utils.py, orchestration/dags/jobs/import/metabase_governance.py
=> (DE-303) automate table metabase_dependencies

orchestration/dags/data_gcp_dbt/models/clean/applicative/venue.sql, orchestration/dags/data_gcp_dbt/models/clean/user_beneficiary.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__user.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__venue.sql
=> (dbt) Add a where condition to avoid filtering null values in the iris field

jobs/etl_jobs/external/qualtrics/main.py, jobs/etl_jobs/external/qualtrics/qualtrics_survey_answers.py
=> (DE 200)(bug) fix import qualtrics 

orchestration/dags/data_gcp_dbt/models/clean/user_beneficiary.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__user.sql
=> (dbt) Remove iris_id from user dimension

orchestration/dags/data_gcp_dbt/models/clean/user_beneficiary.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__user.sql
=> MEP v296.0.2

jobs/etl_jobs/external/metabase-archiving/requirements.txt
=> (fix)(metabase) add missing package in requirements

jobs/etl_jobs/external/siren/requirements.txt
=> [HOTFIX](siren) Update requirements

jobs/etl_jobs/external/contentful/contentful_client.py, jobs/etl_jobs/external/contentful/main.py, orchestration/dags/data_gcp_dbt/models/intermediate/contentful/int_contentful__entry.sql, orchestration/dags/data_gcp_dbt/models/intermediate/contentful/int_contentful__homepage.sql, orchestration/dags/data_gcp_dbt/models/intermediate/contentful/int_contentful__relationship.sql, orchestration/dags/data_gcp_dbt/models/intermediate/contentful/int_contentful__tag.sql, orchestration/dags/data_gcp_dbt/models/sources.yml
=> [DE-316](contentful) feat: add venuesPlaylistAppV2 + fix ts error

jobs/ml_jobs/reduction/requirements.txt
=> [HOTFIX](ml_jobs) fix: update requirements

jobs/ml_jobs/embeddings/requirements.txt, orchestration/dags/dependencies/training_data/sql/item_embeddings_reduction.sql
=> [DE-323](ml_jobs) fix: requirements for embeddings extract

jobs/etl_jobs/external/metabase-archiving/metabase_api.py
=> (fix)(metabase) add get_table property to MetabaseAPI

orchestration/dags/jobs/dbt/dbt_weekly_tables.py
=> (DE-189)(bugs) fix dbt_weekly dag

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_deposit_data.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_institution_data.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_user_data.sql
=> (dbt) Update user_suspension column name

jobs/etl_jobs/external/metabase/query.py
=> (DE-330) improve metabase script logic

jobs/etl_jobs/external/metabase/query.py, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_deposit_data.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_institution_data.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_user_data.sql
=> MEP 296.3.0

orchestration/dags/data_gcp_dbt/models/export/backend/exp_backend__favorites_not_booked.sql
=> (dbt) Remove hotfix and add weekly tag in favorites_not_booked model

jobs/etl_jobs/external/metabase/main.py, jobs/etl_jobs/external/metabase/requirements.txt, jobs/etl_jobs/external/metabase/utils.py
=> (hotfix) metabase script

jobs/etl_jobs/external/metabase/main.py, jobs/etl_jobs/external/metabase/requirements.txt, jobs/etl_jobs/external/metabase/utils.py, orchestration/dags/data_gcp_dbt/models/export/backend/exp_backend__favorites_not_booked.sql
=> MEP v294.3.1

orchestration/dags/dependencies/firebase/sql/clean/firebase_pro_visits.sql
=> (fix) Revert changes in firebase_pro_visits

orchestration/dags/data_gcp_dbt/models/export/posthog/exp_posthog__pro_event.sql, orchestration/dags/data_gcp_dbt/models/mart/pro/mrt_pro__event.sql
=> (dbt) Hotfix : Update column name in mrt_pro__event

orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__offer.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__offer_unverified.sql
=> (dbt) Add venue_region_name to mrt_global_offer

.github/workflows/reusable_dbt_compile.yml, .github/workflows/reusable_deploy_composer.yml, .github/workflows/reusable_job_test.yml, .github/workflows/reusable_linter.yml, .github/workflows/reusable_test_orchestration.yml
=> [HOTFIX](CI/CD) fix: update setup-python version

jobs/etl_jobs/external/qualtrics/qualtrics_survey_answers.py, jobs/etl_jobs/external/qualtrics/utils.py, orchestration/dags/jobs/import/import_qualtrics.py
=> fix: qualtrics import type of extra_data

orchestration/dags/dependencies/qualtrics/export_qualtrics_data.py, orchestration/dags/dependencies/qualtrics/sql/clean/qualtrics_ac.sql, orchestration/dags/dependencies/qualtrics/sql/clean/qualtrics_ir_jeunes.sql
=> (DE-327) update qualtrics export for popularity index

README.md
=> update CD doc

orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__offer_unverified.sql
=> (dbt) Remove duplicated column

.github/workflows/deploy_composer.yml, .github/workflows/reusable_dbt_compile.yml, .github/workflows/reusable_deploy_composer.yml
This PR fixes the dbt workflow in the CI :
* fixes the DBT deploy so that when we deploy, we do not use the CI profile but the default profile
* fixes the DBT compile by fetching the appropriate PR
https://www.notion.so/passcultureapp/880351701699470cb129e4e0ad6bbcba?v=cfbe4b16778b47218f252bd1b5add4a0&p=3d52fd8ba43b4115aad3a5ecace092ff&pm=s
=> [DE-340](analytics): Fix DBT deploy

.github/workflows/base_workflow.yml, README.md
This PR adds conditional step for dbt compilation in ci
compilation occurs only if files have been modified in dbt project folder
=> conditional dbt compilation in CI

.github/workflows/reusable_dbt_compile.yml, .github/workflows/reusable_deploy_composer.yml, .github/workflows/reusable_job_test.yml, .github/workflows/reusable_linter.yml, .github/workflows/reusable_test_orchestration.yml
This PR replaces pip by uv in order to speedup the package installation.
For instance on dbt compile (which use many python packages) 3min10 => 1min17
=> [DE-340](analytics): Replace pip by uv in CI to speedup

orchestration/dags/jobs/dbt/dbt_monthly_tables.py
=> (DE-331) fix dbt monthly dag

.github/workflows/base_workflow.yml, .github/workflows/deploy_composer.yml, .github/workflows/reusable_dbt_compile.yml, .github/workflows/reusable_deploy_composer.yml, .github/workflows/reusable_job_test.yml, .github/workflows/reusable_linter.yml, .github/workflows/reusable_test_orchestration.yml, README.md, jobs/ml_jobs/algo_training/fraud/offer_compliance_model/api_model.py, jobs/ml_jobs/algo_training/fraud/offer_compliance_model/evaluate.py, jobs/ml_jobs/algo_training/fraud/offer_compliance_model/package_api_model.py, jobs/ml_jobs/algo_training/fraud/offer_compliance_model/preprocess.py, jobs/ml_jobs/algo_training/fraud/offer_compliance_model/train.py, jobs/ml_jobs/algo_training/requirements.txt, orchestration/dags/data_gcp_dbt/models/clean/user_item_discovery.sql, orchestration/dags/data_gcp_dbt/models/export/clickhouse/exp_clickhouse__collective_booking.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__offer_unverified.sql, orchestration/dags/jobs/dbt/dbt_monthly_tables.py, orchestration/dags/jobs/export/export_clickhouse.py, orchestration/dags/jobs/ml/algo_training_offer_compliance_model.py
=> MEP 294.5.0

orchestration/dags/jobs/dbt/dbt_monthly_tables.py, orchestration/dags/jobs/dbt/dbt_weekly_tables.py
=> (fix) dag: dbt monthly/weekly end task trigger rule

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_collective_offer_data.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__collective_offer.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__collective_offer_unverified.sql
=> (dbt) Update wrong join to fix discrepencies

orchestration/dags/data_gcp_dbt/models/export/clickhouse/exp_clickhouse__booking.sql, orchestration/dags/data_gcp_dbt/models/export/clickhouse/exp_clickhouse__collective_booking.sql, orchestration/dags/dependencies/export_clickhouse/export_clickhouse.py, orchestration/dags/jobs/export/export_clickhouse.py
=> (cleaning/feature) clickhouse export dag

jobs/etl_jobs/external/qualtrics/qualtrics_survey_answers.py
=> [HOTFIX] fix : qualtrics format columns

jobs/etl_jobs/external/metabase-archiving/dependencies.py, jobs/etl_jobs/external/metabase/data/mappings.json, jobs/etl_jobs/external/metabase/main.py, jobs/etl_jobs/external/metabase/native.py, jobs/etl_jobs/external/metabase/table.py
We have a script that updates Metabase with the new table names. We are adding a feature that allows updating column names: if you want to update the column names due to a change, add a dictionary to the `data/mappings.json` file.
=> [DE-171](metabase) Add update query function in Metabase DAG

jobs/etl_jobs/external/metabase-archiving/metabase_api.py, jobs/etl_jobs/external/metabase/table.py, orchestration/dags/data_gcp_dbt/models/mart/pro/mrt_pro__visit.sql
=> (dbt) Update firebase pro visits column names

jobs/etl_jobs/external/metabase/data/mappings.json, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_cultural_partner_data.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__venue_tag.sql
As part of the migration, we will remove the `enriched_venue_tags_data` model and replace it with `mrt_global__venue_tag`. To do this, we need to update the references to the old model throughout the project.
We also take advantage of this PR to add `partner_id`, which was missing, to `mrt_global__venue_tag` and to include the new column mappings for the Metabase update.
=> (dbt) Update enriched venue tags dependencies

orchestration/dags/data_gcp_dbt/models/analytics/history/bookable_venue_history.sql
=> [DA-3710](dbt) feat: add partition and incremental_strategy (bookable_venue_history)

orchestration/dags/data_gcp_dbt/models/analytics/history/bookable_partner_history.sql
=> [DA-3711](dbt) feat: add partition and incremental_strategy (bookable_partner_history)

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_cultural_partner_data.sql
=> (dbt) Add missing table aliases to enriched_cultural_partner_data

orchestration/dags/data_gcp_dbt/models/analytics/firebase/firebase_booking_origin.sql, orchestration/dags/data_gcp_dbt/models/analytics/firebase/firebase_bookings.sql
=> [DE-397](dbt) :feat add app_version (firebase_booking_origin)

orchestration/dags/data_gcp_dbt/dbt_project.yml, orchestration/dags/data_gcp_dbt/macros/get_environment_mediation_url.sql, orchestration/dags/data_gcp_dbt/models/intermediate/gcp/int_gcp__bigquery_cost.sql
=> [HOTFIX](dbt) fix: change project_name (bq_costs)

jobs/etl_jobs/external/appsflyer/utils.py
=> [DE-398](appsflyer) : fix pandas update comparison bug

jobs/etl_jobs/external/appsflyer/utils.py, orchestration/dags/data_gcp_dbt/dbt_project.yml, orchestration/dags/data_gcp_dbt/macros/get_environment_mediation_url.sql, orchestration/dags/data_gcp_dbt/models/intermediate/gcp/int_gcp__bigquery_cost.sql, orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__event.sql, orchestration/dags/data_gcp_dbt/models/sources.yml
=> MEP 296.2.0 

.github/workflows/scripts/find_test_intersections.py
Find job intersections was not working after recent PR
No ticket
Working workflow : https://github.com/pass-culture/data-gcp/actions/runs/9887440210/job/27309160447?pr=2780
=> (CI): Fix find job intersection

orchestration/dags/data_gcp_dbt/dbt_project.yml, orchestration/dags/data_gcp_dbt/models/intermediate/gcp/int_gcp__bigquery_cost.sql
=> (dbt) :feat update project name with default values

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_daily_user_video_module.sql, orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_video_event.sql, orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase_native_video_event.sql, orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_video_module_conversion.sql
Please include a summary of the changes: This PR adds 3 models related to the video modules displayed in app
- int_video_events, a raw table to only select video-related events
- int_firebase__native_daily_user_video_module, an intermediate table at video granularity
- mrt_native__daily_video_module_conversion, a mart table at video block granularity for dashboarding purpose
Tag a reviewer if necessacy  @carolinemestre-passculture @Jules-Arbelot 
=> add video models

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_daily_user_video_module.sql, orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_video_event.sql, orchestration/dags/data_gcp_dbt/models/intermediate/gcp/int_gcp__bigquery_cost.sql, orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_video_module_conversion.sql
=> add custom incremental config

orchestration/dags/jobs/dbt/dbt_dag_run.py
=> add snapshot dependencies in dbt dag

jobs/etl_jobs/external/gsheet/gsheet.py
=> [DE-328](gsheet) feat: add new csv sources for EPLE

orchestration/dags/data_gcp_dbt/models/intermediate/gcp/int_gcp__bigquery_cost.sql, orchestration/dags/data_gcp_dbt/models/intermediate/metabase/int_metabase__aggregated_card_activity.sql, orchestration/dags/data_gcp_dbt/models/intermediate/metabase/int_metabase__daily_query.sql, orchestration/dags/data_gcp_dbt/models/mart/monitoring/mrt_monitoring__bigquery_cost.sql, orchestration/dags/data_gcp_dbt/models/mart/monitoring/mrt_monitoring__metabase_cost.sql, orchestration/dags/data_gcp_dbt/models/sources.yml, orchestration/dags/dependencies/metabase/import_metabase.py, orchestration/dags/dependencies/metabase/sql/raw/revision.sql
=> [DE-399](dbt) feat: improve cost queries

orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_video_module_conversion.sql
=> fix sql syntax within is_incremental dbt macro

jobs/ml_jobs/artist_linkage/evaluate.py, orchestration/dags/dependencies/ml/linkage/artist_linkage_on_test_set.py, orchestration/dags/dependencies/ml/linkage/sql/artist_linkage_on_test_set.sql, orchestration/dags/jobs/ml/link_artists.py
* Add metric computatiojn at the end of artist linkage
Run on staging : 
https://www.notion.so/passcultureapp/880351701699470cb129e4e0ad6bbcba?v=cfbe4b16778b47218f252bd1b5add4a0&p=8db229c9fd754135a6d130495c400431&pm=s
=> [DE-423](analytics): Add metrics for artist linkage

orchestration/dags/dependencies/analytics/sql/analytics/firebase_aggregated_search_events.sql
=> correction-consult-offer-with-search-id

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__user.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__booking.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__deposit.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__user.sql
=> (dbt) Add missing colums to mrt_global__deposit

orchestration/dags/data_gcp_dbt/profiles.yml
=> (dbt) Update DBT sandbox dataset

Makefile, orchestration/Makefile
=> [MOB-Data](analytics): Fix Makefiles

orchestration/README.md, orchestration/docker-compose.yaml
=> [PR-DATA-DE-329-airflow-local-webserve] feat: Add GCE_SA environment variable to docker-compose.yaml

orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__booking.sql
=> (dbt) Add fields to mrt_global__booking

jobs/ml_jobs/artist_linkage/evaluate.py, jobs/ml_jobs/artist_linkage/utils/constants.py, jobs/ml_jobs/artist_linkage/utils/mlflow.py
Change how MLFlow token is generated so that it works locally and remotely
https://www.notion.so/passcultureapp/880351701699470cb129e4e0ad6bbcba?v=cfbe4b16778b47218f252bd1b5add4a0&p=8fc5aa67d25449bfb0e81253a5640484&pm=s
=> [DE-429](analytics) : Work with mlflow locally for artist linkage

orchestration/dags/jobs/import/import_batch.py
=> feat/batch fix: add retries for jobs

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_offerer_data.sql, orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__offerer.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__offerer.sql
=> (dbt) Add city to offerer table

.github/PULL_REQUEST_TEMPLATE/DS_ticket_template.md, jobs/ml_jobs/algo_training/baseline_model/train.py, jobs/ml_jobs/algo_training/evaluate.py, jobs/ml_jobs/algo_training/fraud/offer_compliance_model/evaluate.py, jobs/ml_jobs/algo_training/fraud/offer_compliance_model/package_api_model.py, jobs/ml_jobs/algo_training/fraud/offer_compliance_model/train.py, jobs/ml_jobs/algo_training/triplet_model/train.py, jobs/ml_jobs/algo_training/triplet_model/utils/callbacks.py, jobs/ml_jobs/algo_training/two_towers_model/train.py, jobs/ml_jobs/algo_training/utils/callbacks.py, jobs/ml_jobs/algo_training/utils/constants.py, jobs/ml_jobs/algo_training/utils/mlflow_tools.py
Refacto mlflow connection in algo training
https://www.notion.so/passcultureapp/880351701699470cb129e4e0ad6bbcba?v=cfbe4b16778b47218f252bd1b5add4a0&p=43a63ae68dcb40fc83a9054566d6d6fb&pm=s
Working training example : https://db0dc04fe8fd4324a0b1b356f2ce85c9-dot-europe-west1.composer.googleusercontent.com/dags/algo_training_two_towers/grid?root=&dag_run_id=manual__2024-07-19T12%3A05%3A06%2B00%3A00&task_id=evaluate&tab=logs
=> [DE-434](analytics) Refacto/use mlflow locally in algo training

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__user_offerer.sql
=> (dbt) Update gloabl user offerer

jobs/etl_jobs/external/metabase/main.py, jobs/etl_jobs/external/metabase/query.py
=> [DE-171](dbt) Correct update_dataset_query function

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_cultural_partner_data.sql, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_offerer_tags_data.sql
In this PR, we are taking several actions for `enriched_offerer_tags_data` model migration:
- Updating any calls to the old model in the code
- Removing old model code
Tag a reviewer if necessacy @LucileRainteau
=> (dbt) Update enriched_offerer_tags_data dependencies

jobs/etl_jobs/external/batch/batch_client.py
=> MEP 300.0.1

jobs/ml_jobs/embeddings/main.py, orchestration/dags/jobs/ml/embedding_extraction_item.py
- loads all the data once in order to BQ reduce costs. 
- iterates over batches for the embedding extraction part.
Tag a reviewer if necessacy  @lmontier 
=> [DE-347](ml) feat: improve embedding extraction

orchestration/dags/jobs/ml/embedding_clusterisation_item.py, orchestration/dags/jobs/ml/embedding_reduction_item.py
=> [DE-347](embeddings) feat: rename files + fixes

orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__venue_provider.sql
=> (dbt) Update mrt_global__venue_provider query

jobs/etl_jobs/internal/export_clickhouse/core/utils.py, orchestration/dags/common/config.py, orchestration/dags/common/hooks/gce.py, orchestration/dags/common/hooks/network.py, orchestration/dags/common/operators/gce.py, orchestration/dags/jobs/export/export_clickhouse.py, orchestration/dags/launch_vm.py
=> [DE-260](clickhouse) feat: add gke network for ehp logic

orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__booking.sql, orchestration/dags/data_gcp_dbt/models/mart/global/schema/mrt_global__booking.yml
=> DE-438/set-ci-warning-to-failing-tests

orchestration/dags/data_gcp_dbt/snapshots/snapshot_applicative/snapshot__applicative_collective_offer_template.sql, orchestration/dags/data_gcp_dbt/snapshots/snapshot_applicative/snapshot__applicative_stock.sql, orchestration/dags/jobs/dbt/dbt_dag_run.py
=> DE-182/hotfix-snapshots

orchestration/dags/data_gcp_dbt/snapshots/snapshot_applicative/snapshot__applicative_collective_offer_template.sql
This PR disambiguate column name in snapshot collective_offer_template
=> DE-182/hotfix-snapshot-collective-offer-template

jobs/ml_jobs/item_linkage/build_semantic_space.py, jobs/ml_jobs/item_linkage/constants.py, jobs/ml_jobs/item_linkage/link_items.py, jobs/ml_jobs/item_linkage/linkage_candidates.py, jobs/ml_jobs/item_linkage/model/semantic_space.py, jobs/ml_jobs/item_linkage/streamlits/st_linkage_analysis.py, jobs/ml_jobs/item_linkage/utils/common.py, orchestration/dags/data_gcp_dbt/snapshots/snapshot_applicative/snapshot__applicative_collective_offer_template.sql, orchestration/dags/dependencies/ml/linkage/sql/linkage_item_candidates_data.sql, orchestration/dags/dependencies/ml/linkage/sql/linkage_item_sources_data.sql
=> MEP v300.3.0

orchestration/dags/dependencies/propilote/sql/tmp/diversification/propilote_tmp_diversification.sql, orchestration/dags/dependencies/propilote/sql/tmp/montant_24_mois/propilote_tmp_montant_24_mois.sql, orchestration/dags/dependencies/propilote/sql/tmp/taux_utilisation/propilote_tmp_utilisation.sql
=> (dbt) Update mrt_global__deposit references in propilote queries

.github/workflows/CD_workflow.yml, .github/workflows/CI_workflow.yml, .github/workflows/README.md, .github/workflows/reusable_dbt_workflow.yml, README.md
=> DE-237/cicd-documentation

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__offerer.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__venue.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__venue_reimbursement_point_link.sql, orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__offerer.sql, orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__venue.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__local_authority.sql
In this PR, we are migrating the model `enriched_local_authority_data` (new model: analytics_prod.`global_local_authority`) and adding the mapping of new column names to prepare for the Metabase update.
Tag a reviewer if necessacy  @mathilde-vey 
=> [DE-320](dbt) Migrate enriched_local_authority data

jobs/ml_jobs/item_linkage/build_semantic_space.py, jobs/ml_jobs/item_linkage/link_items.py, jobs/ml_jobs/item_linkage/linkage_candidates.py, orchestration/dags/jobs/ml/link_items.py
* Set scheduler to run the Dag only once a week (task is 1h30 with n1-standard-16)
* Add task to write linked_items into bigquery in link_items dag
* Clean code
https://www.notion.so/passcultureapp/880351701699470cb129e4e0ad6bbcba?v=cfbe4b16778b47218f252bd1b5add4a0&p=0b6cc94b370c4e6ca5764279f347a9f5&pm=s
=> [DE-468](analytics) : Write linked items to bq and clean code

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/pro/int_firebase__pro_event_flattened.sql
=> (dbt) Remove wrong UNNEST in int_firebase__pro_event_flattened

.github/workflows/reusable_dbt_workflow.yml, .github/workflows/reusable_deploy_composer.yml
Propagate the Fix from the previous PR to dbt compile and deploy github action workfows
=> (fix): install requirements with no-build-isolation while setuptool package is being fixed

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__user.sql, orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__user.sql
=> [DE-320](dbt) Correct int_global__user

orchestration/dags/data_gcp_dbt/macros/custom_table_config.sql, orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__user.sql
=> DE-no-ticket-hotfix custom materialization table

orchestration/dags/data_gcp_dbt/models/export/posthog/exp_posthog__native_event.sql
=> add param origin to posthog native

orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__user.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__user.sql
=> (dbt) Update initial_deposit column name in mrt_global__user

orchestration/dags/data_gcp_dbt/models/export/backend/exp_backend__stats_display_top_3_most_consulted_offers_last_30_days.sql
=> (dbt) Fix: convert model content to lowercase

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__custom_reimbursement_rule.sql
=> (dbt) Remove int_applicative__custom_reimbursement_rule.sql

jobs/ml_jobs/algo_training/evaluate.py
=> (BSR) feat: reconnect for longer tasks

jobs/ml_jobs/record_linkage/main.py
=> [HOTFIX](record_linkage) fix: set typer main correctly

orchestration/dags/data_gcp_dbt/models/intermediate/pcreco/int_pcreco__displayed_offer_event.sql
=> (ranking) feat: add display order logic (1/2)

orchestration/dags/common/alerts.py, orchestration/dags/common/config.py, orchestration/dags/jobs/dbt/dbt_artifacts.py
=> (DE-486) feat/add alerting for warning failing tests

jobs/ml_jobs/algo_training/evaluate.py, jobs/ml_jobs/record_linkage/main.py, orchestration/dags/common/alerts.py, orchestration/dags/data_gcp_dbt/models/clean/applicative/venue.sql, orchestration/dags/data_gcp_dbt/models/export/backend/exp_backend__stats_display_top_3_most_consulted_offers_last_30_days.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__custom_reimbursement_rule.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__venue.sql, orchestration/dags/data_gcp_dbt/models/intermediate/pcreco/int_pcreco__displayed_offer_event.sql, orchestration/dags/data_gcp_dbt/models/sources.yml, orchestration/dags/dependencies/applicative_database/sql/raw/google_places_info.sql, orchestration/dags/jobs/dbt/dbt_artifacts.py
=> MEP v301.2.0

orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__event.sql
=> (analytics) Add partner_id field to mrt_native_event

orchestration/dags/jobs/dbt/dbt_artifacts.py
=> fix/dbt-artifacts remove re_data and add sleep operator

orchestration/dags/data_gcp_dbt/dbt_project.yml
This PR adds team ownership on dbt models.
This metadata is visible only in artifact manifest.json
Tag a reviewer if necessacy  @carolinemestre-passculture 
=> feat/dbt - add team owners on models

jobs/etl_jobs/external/gsheet/gsheet.py, jobs/etl_jobs/internal/cold-data/main.py, jobs/etl_jobs/internal/cold-data/tables_config.py, jobs/etl_jobs/internal/cold-data/utils.py, orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_institution_data.sql, orchestration/dags/data_gcp_dbt/models/analytics/eple_aggregated.sql, orchestration/dags/data_gcp_dbt/models/analytics/institution_locations.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__educational_institution.sql, orchestration/dags/data_gcp_dbt/models/intermediate/gsheet/int_gsheet__educational_institution_student_headcount.sql, orchestration/dags/data_gcp_dbt/models/sources.yml, orchestration/dags/dependencies/cold_data/import_cold_data.py, orchestration/dags/dependencies/cold_data/sql/analytics/eple.sql, orchestration/tests/data_analytics/config.py
=> [DE-487](analytics) feat: refactor eple logic

jobs/ml_jobs/ranking_endpoint/app/model.py, jobs/ml_jobs/ranking_endpoint/deploy_model.py
* Refacto ranking_endpoint
* Remove duplicates in data, so that training and test are dissociated
No ticket
=> [DE-501] (DS) Refacto ranking_enpoint job and remove duplicates in train/test

orchestration/dags/data_gcp_dbt/models/intermediate/gsheet/int_gsheet__educational_institution_student_headcount.sql
=> (dbt) Add fillna value and safe_cast 

jobs/etl_jobs/external/adage/scripts/utils.py, jobs/etl_jobs/external/appsflyer/core/utils.py, jobs/etl_jobs/external/batch/utils.py, jobs/etl_jobs/external/contentful/main.py, jobs/etl_jobs/external/qualtrics/utils.py, jobs/etl_jobs/external/sendinblue/sendinblue_newsletters.py
=> (DE-441)(etl_jobs) bq allow field addition for partitioned tables

jobs/etl_jobs/external/appsflyer/core/utils.py, jobs/etl_jobs/external/appsflyer/gcs_import.py
=> (appsflyer) fix: import gcs partitions

jobs/etl_jobs/external/contentful/main.py
=> fix/remove duplicates schema_update_options

orchestration/dags/data_gcp_dbt/models/intermediate/seed/int_seed__geo_iris.sql
=> fix: add mat_view for geo

orchestration/dags/data_gcp_dbt/models/intermediate/seed/int_seed__geo_iris.sql
=> MEP v301.6.0 

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__offer_criterion.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__offer_criterion.sql
=> feat: Update criterion tables and create mrt_global__offer_criterion

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_institution_data.sql, orchestration/dags/data_gcp_dbt/models/clean/applicative/beneficiary_fraud_check.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__beneficiary_fraud_check.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__collective_booking.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__collective_stock.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__educational_deposit.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__educational_institution.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__institution.sql, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__institution_program.sql, orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__collective_offer.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__collective_booking.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__educational_institution.sql
In this PR, we are migrating the model `enriched_institution_data` (new model is `mrt_global__institution`)
Tag a reviewer if necessacy @LucileRainteau @Jules-Arbelot @cdelabre 
=> [DE-320](dbt) Migrate enriched_institution_data

jobs/etl_jobs/external/metabase/native.py
We want to update the `replace_column_names` function to remove the part that updates the SQL query for the variables.
=> (metabase) Update replace_column_names function

orchestration/dags/common/config.py, orchestration/dags/common/utils.py, orchestration/dags/jobs/dbt/dbt_dag_run.py
Suite à [cette RDP](https://www.notion.so/passcultureapp/327254dc68c7484bb71d4db0f7837186?v=7afefc41e6314638aa80d96a6cbee9ca&p=115f7e3167714e76a1aa646210d1601b&pm=s)
=> (dbt) feat/add dependency to firebase raw

jobs/etl_jobs/external/qualtrics/utils.py
=> (qualtrics) fix/update write disposition

orchestration/dags/jobs/ml/algo_default_deployment.py
=> [HOTFIX](ranking) feat: add 2 min nodes as default value

orchestration/dags/data_gcp_dbt/models/analytics/firebase/firebase_visits.sql
=> Add nb_consult_venue_map to firebase_ visits

orchestration/dags/common/alerts.py, orchestration/dags/common/config.py, orchestration/dags/jobs/dbt/dbt_artifacts.py
This PR adds owners mentions to dbt quality tests alerts in a dedicated slack channel
=> DE-451/data quality dbt v2

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__consultation.sql, orchestration/dags/data_gcp_dbt/models/intermediate/metric/discovery/int_metric__discovery_daily_consultation.sql, orchestration/dags/data_gcp_dbt/models/intermediate/metric/discovery/int_metric__discovery_score.sql
This PR is linked to [this ticket](https://www.notion.so/passcultureapp/Table-granulaire-de-d-couverte-1-ligne-par-item-d-couvert-92d5f2267e2948ff8d236ea35198ebb7?pvs=4).
Tag a reviewer if necessacy  @cdelabre @Jules-Arbelot 
=> [DE-414](dbt) New Discovery calculation model

orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__educational_institution.sql, orchestration/dags/data_gcp_dbt/models/intermediate/geolocation/int_geo__institution_location.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__address.sql, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__offerer_address.sql, orchestration/dags/dependencies/applicative_database/sql/raw/address.sql, orchestration/dags/dependencies/applicative_database/sql/raw/educational_institution.sql
=> (BSR) fix: rename import fields

jobs/etl_jobs/internal/gcs_seed/tables_config.py, orchestration/dags/dependencies/qpi/sql/clean/qpi_answers_projection.sql, orchestration/dags/dependencies/qpi/sql/clean/qpi_answers_v4_clean.sql
=> [DE-530](seed) feat: migrate qpi_mapping to seed_prod

orchestration/dags/dependencies/ml/linkage/sql/items_to_link.sql
=> [HOTFIX](ml) fix: change table dependency

orchestration/dags/common/alerts.py, orchestration/dags/jobs/dbt/dbt_artifacts.py
=> (DE-513) fix/no-write-json for artifacts metrics

orchestration/dags/jobs/import/import_applicative_database.py
=> [HOTFIX] Increase Timeout + Retry to applicative-job import

orchestration/dags/data_gcp_dbt/models/analytics/enriched/enriched_local_authority_data.sql
=> (dbt) Add row_number instead of rank

orchestration/dags/dependencies/firebase/import_firebase.py, orchestration/dags/dependencies/firebase/sql/raw/firebase_events.sql, orchestration/dags/dependencies/firebase/sql/raw/firebase_pro_events.sql, orchestration/dags/jobs/import/import_firebase.py
=> (BSR) feat: add fallback retry in case we dont have data
