orchestration/dags/common/alerts.py, orchestration/dags/jobs/api/export_cloudsql_tables_to_bigquery.py, orchestration/dags/jobs/api/recommendation_cloud_sql.py, orchestration/dags/jobs/import/import_adage.py, orchestration/dags/jobs/import/import_analytics.py, orchestration/dags/jobs/import/import_contentful_home.py, orchestration/dags/jobs/import/import_logs.py, orchestration/dags/jobs/import/import_metabase.py, orchestration/dags/jobs/import/import_siren.py
- Keep alerts the same way everywhere.
- In case we are not in prod and task is manual, then no alerts (for dev)
- Add alerts for adage
=> Fix Slack alerts

recommendation/api/Dockerfile, recommendation/api/src/app.py, recommendation/api/src/pcreco/core/scoring.py, recommendation/api/src/pcreco/utils/ai_platform/get_ai_platform_service.py, recommendation/api/src/pcreco/utils/env_vars.py
- Refacto : Create object 'AI_platform_services' only once , not everytime we call 'predict()' 
-> cf. [GCP_doc](https://cloud.google.com/architecture/best-practices-for-ml-performance-cost#reuse_the_authenticated_service_object_in_the_client_object)
=> [fix-overhead-model-latency]

recommendation/api/src/app.py, recommendation/api/src/pcreco/core/scoring.py, recommendation/api/src/pcreco/core/utils/vertex_ai.py
- import model metadata from AI vertex client response (cf. [doc](https://cloud.google.com/python/docs/reference/aiplatform/latest/google.cloud.aiplatform_v1.types.PredictResponse) response content)  
- added to \recommendation route for stg testing before adding it to \playlist_recommendation
=> [fix-add-model-metadate-to-pcreco-output]

orchestration/dags/dependencies/firebase/import_firebase.py, orchestration/dags/dependencies/firebase/sql/analytics/firebase_home_events.sql
Firebase table for all events based on the Home Page (view, click, booking, favorites))
Based on [this](https://data-analytics.internal-passculture.app/question/5891-wip-conversion-playlists-v2?date=past1weeks)
When we don't have an event, we try to reconciliate it.
No module_id (for recommendation):  
- match based on naming on module_name (cf mapping_module_name_and_id)
No entry_id (home_id) (for all clicks):
- we take take the last seen home page by the user
- or the last seen (not user based) seen match module_id - home_id. (This works as we don't have much modules cross homes)
No module_index (for all clicks): 
- then we look where was the last position of the module when the user saw it
- or the last seen (not user based) position of the module
For bookings & favorites:
- We look if …
=> [PC-16608] Create firebase Home events table

orchestration/dags/dependencies/logs/sql/analytics/adage_logs.sql
- Added rules in order to integrate new adage route
- Added extra fields from Notion documentation
- Added session_id (<= 30min) for same user. Session duration can be max 72h. 
Dev table is in `raw_dev.adage_logs`.
=> [PC-16982] add adage logs

orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_booking_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_user_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/enriched_venue_data.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/offer_moderation.sql, orchestration/dags/dependencies/import_analytics/sql/analytics/recommendable_offers_data.sql, orchestration/dags/dependencies/import_analytics/sql/clean/offer.sql, orchestration/dags/dependencies/import_analytics/sql/clean/user_beneficiary.sql, orchestration/dags/dependencies/import_recommendation_cloudsql/monitoring_queries/monitor_recommendable_offers_data.sql, orchestration/tests/data_analytics/config.py, orchestration/tests/data_analytics/data.py
- ajout du filtre sur les offres ACTIVATION_THING/ACTIVATION_EVENT et jeux-concours dans la table clean offer
- calcul du champs user_activation_date dans la définition de user_beneficiary
=> (Refacto Analytics) switch activation offer filters in clean zone

.github/workflows/deploy_composer.yml, .github/workflows/reusable_deploy_composer.yml, .github/workflows/reusable_job_test.yml, .github/workflows/reusable_linter.yml, .github/workflows/reusable_test_orchestration.yml
J'ai utilisé les environnements afin de rediriger les alertes vers le bon channel en fonction de la ou on déploie.
Pour les workflows j'ai préféré ne pas les lier á un environnement et j'ai donc créé une nouvelle variable contenant le channel_id a utiliser dans ces cas là.
Dans le base workflow même une erreur ne déclenche pas d'alerte : 
https://github.com/pass-culture/data-gcp/actions/runs/6468605130/job/17560967578
En revanche une erreur dans le workflow deploy composer en déclenchera une : 
https://github.com/pass-culture/data-gcp/actions/runs/6468604761/job/17560973496
Et exemple de workflow qui notifie lors d'un déploiement réussi : https://github.com/pass-culture/data-gcp/actions/runs/6469540215/job/17564031280
https://passculture.atlassian.net/browse/PC-24987
=> (PC-24987) parametrisation alertes slack 

orchestration/dags/dependencies/import_analytics/sql/analytics/aggregated_weekly_user_data.sql
Only users credited on Monday had a weeks_since_deposit_created = 0 due to date filter
=> Fix first_week in weekly_user_data

orchestration/dags/jobs/import/import_firebase.py
Cette PR retire la dépendance au DAG contentful dans la version daily du dag firebase.
=> (fix)(firebase) Fix daily dag to not depend on contentful dag

orchestration/dags/dependencies/propilote/export_propilote.py, orchestration/dags/dependencies/propilote/sql/analytics/pilote_export.sql, orchestration/dags/dependencies/propilote/sql/analytics/propilote_kpis.sql, orchestration/dags/dependencies/propilote/sql/tmp/taux_participation_eac_ecoles/propilote_tmp_participation_eac_ecoles.sql, orchestration/dags/dependencies/propilote/sql/tmp/taux_participation_eac_jeunes/propilote_tmp_participation_eac_jeunes.sql
This PR add a dimension is_current_year to the table propilote_kpis to easily compare scholar years. 
It changes the sql kpis to always compute from today to the first day of the last scholar year.
It changes the kpi taux_participation_eac_ecoles, originally computed from enriched_collective_booking_data, and now from adage_involved_institution. 
JIRA-PC-25254-add-last-year-comparison-in-propilote-kpis
- [] Fix (non-breaking change which corrects expected behavior)
- [] New fields (non-breaking change)
- [] New table (non-breaking change)
- [] Table deletion (potentially breaking change which adds functionality/ table)
=> [PC-25254](analytics) Add last year comparison in propilote kpis

orchestration/airflow/orchestration-requirements.txt, orchestration/dags/common/access_gcp_secrets.py
!! TO merge when composer-stg is upgrade to 2.6.3
=> (fix) fix acces gcp secrets function following composer upgrade

orchestration/dags/dependencies/import_analytics/import_clean.py, orchestration/dags/jobs/import/import_analytics.py
This PR changes dependencies logic from end of dag to end of specific dag task to avoid circularity
=> Circular dependencies removal

orchestration/dags/data_gcp_dbt/dbt_project.yml
Les modèles de intermediate et mart n'avait pas de schémas précisés dans fichier `dbt_project.yml`, ils allaient donc dans `tmp_prod` et étaient supprimés automatiquement.
=> Updade dbt config file

orchestration/dags/dependencies/import_analytics/sql/clean/applicative_database/booking_history.sql, orchestration/dags/dependencies/training_data/sql/training_data_bookings.sql
Update table name in `booking_history` and `training_data_bookings` model (because the alias of `clean_prod.applicative_database_booking` has been removed).
=> Update booking table name

orchestration/dags/data_gcp_dbt/models/analytics/firebase/firebase_app_experiments.sql
Le modèle firebase_app_experiment a timeout ce qui entraine le fait que le dbt_run_dag fail. Nous ajoutons l'incremental pour ne calculer que le dernier jour de données.
=> (dbt) Add incremental to firebase_app_experiment model

orchestration/dags/data_gcp_dbt/models/intermediate/firebase/native/int_firebase__native_daily_user_home_module.sql, orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_user_home_module.sql
This PR is linked to [this ticket](https://passculture.atlassian.net/jira/software/c/projects/PC/boards/24?selectedIssue=PC-30263).
Since contentful tables can be updated in the past, the incremental strategy was not working with the model. We are splitting the model into two by adding an intermediate model (`int_firebase__native_daily_user_home_module`) that will be incremental and will retrieve the `module_id` of the relevant events from Firebase. We are transforming the final MART model (`mrt_native__daily_user_home_module`) into a view so that the data on the contenful tables is always accurate.
Tag a reviewer if necessacy  @cdelabre @MatthieuRipollPassCulture 
=> (dbt) Improve mrt_native__daily_user_home_module

orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__offer.sql
We observed that Metabase cards and models utilizing `mrt_global__offer` were slower compared to when they used `enriched_offer_data`. The only difference between the two tables is that one is partitioned and the other is not.
=> (dbt) Remove mrt_global__offer partition

orchestration/dags/data_gcp_dbt/models/mart/native/mrt_native__daily_home_recommendation_offer.sql
Changes the unique_session_id alias in order to have it for all events and not only bookings.
Tag a reviewer if necessacy  @carolinemestre-passculture 
=> [HOTFIX](mart) fix: use unique session_id from consultation for (daily-home-reco)

orchestration/dags/dependencies/applicative_database/sql/raw/beneficiary_fraud_check.sql
To keep track of users who switched adresses
This PR de-hashes address information stored in beneficiary_fraud_check_table when user completes/updates profile informations.
- [x ] I have performed a self-review of my code
=> De-hash address in beneficiary_fraud_check

jobs/ml_jobs/algo_training/offer_categorization/package_api_model.py
Update the text encoder model used in the offer categorization API from "sentence-transformers/clip-ViT-B-32-multilingual-v1" to "sentence-transformers/all-MiniLM-L6-v2". This change improves the performance of the API by using a more advanced text encoder model.
Fix sentence_transformer model name used in offer_categorization inference  
This PR fixes the bug
=> [DE-617] feat: Update text encoder model in offer categorization API

jobs/ml_jobs/algo_training/two_towers_model/models/two_towers_model.py
Update the loss function in the TwoTowersModel class to use SoftmaxLoss instead of CategoricalCrossentropy. This change improves the retrieval task in the model.
Normalize user and item embedding before computing loss 
This PR adds the feature
=> [DE-616] refactor: Update loss function in TwoTowersModel

orchestration/dags/jobs/dbt/dbt_artifacts.py
known issue - see elementary-commmunity slack:
Renee Cooper
Le 31 juil. 2023 à 17 h 08
Has anyone run into issues with their dbt docs since upgrading Elementary to the latest version?  I upgrade Elementary in packages to 0.9.0. (and the package in requirements to 0.9.1).
Post-upgrade, our published dbt docs only have the Elementary models & dbt_utils; all our models are missing.
Logging into the dbt-test kubernetes pod before it exits, I can see both the manifest.json and the catalog.json are new.  I downloaded them and while the catalog.json has our model information, the manifest only has Elementary information.
In the pod we do in this order:
dbt test
edr monitor
dbt docs generate
edr report
app deploy (of the GCP app; uploads the files)
I cannot run edr report locally to see if that's …
=> add final compile step

orchestration/dags/dependencies/propilote/sql/tmp/taux_participation_eac_ecoles/propilote_tmp_participation_eac_ecoles.sql, orchestration/dags/dependencies/propilote/sql/tmp/taux_participation_eac_jeunes/propilote_tmp_participation_eac_jeunes.sql
This PR fixes missing data for EAC Propilote KPIs for the month of september (ppg_index 9 and 10). Because adage_id was treated as a STRING rather than an INT, last_adage_id for september was 9 and not 10
Tag a reviewer if necessacy  @LucileRainteau @cdelabre 
- [ x] I have performed a self-review of my code
=> Fix Propilote KPIs for september EAC metrics

orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__user.sql
This PR fixes user_is_unemployed column (wrong string value expected)
Tag a reviewer if necessacy  @LucileRainteau @Jules-Arbelot 
=> (DA-3744) fix(bq_jobs): Fix user_is_unemployed column in user table

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/applicative_database/column__venue.md, orchestration/dags/data_gcp_dbt/models/intermediate/applicative/int_applicative__venue.sql, orchestration/dags/data_gcp_dbt/models/intermediate/global/int_global__venue.sql, orchestration/dags/data_gcp_dbt/models/mart/global/_schema/mrt_global__venue.yml, orchestration/dags/data_gcp_dbt/models/mart/global/mrt_global__venue.sql, orchestration/dags/dependencies/applicative_database/sql/raw/parallel/venue.sql
-> Le champs venue_is_open_to_public vise à remplacer progressivement le champs venue_is_permanent dans le cadre du rattrapage des lieux relatifs au chantier offre-adresse. 
A date :
=> (DA-3536) feat(analytics): Add field venue_is_open_to_public to venue tables

orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/tracking/column__collective_adage_log.md, orchestration/dags/data_gcp_dbt/models/_dbt_docs/glossary/tracking/column__pro_event.md, orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/collective/description__mrt_collective__adage_log.md, orchestration/dags/data_gcp_dbt/models/_dbt_docs/models/mart/pro/description__mrt_pro__event.md
<details>
* DA
* DE
* AE
* DS
* HF
* BSR
* PC
* type :
* build
* lint
* ci
* docs
* feat
* fix
* perf
* refactor
* test
* core
* dbt …
=> (DA) feat(Analytics): Add table and column descriptions on pro_event and collective_adage_logs
